### ISSUE TITLE
Support for ".. only:: latex" blocks are incomplete in Jupinx 

### ISSUE THREAD

**Issue by fkazemian** [QuantEcon/lecture-source-py#10]
It seems for ".. only:: latex" blocks, Jupinx has some problem and it wouldn't able to generate them correctly 
![1](https://user-images.githubusercontent.com/20714542/44771608-d28e4b00-abae-11e8-884a-b1e649b220b0.png)
.

**Comment by mmcky** [comment]
thanks @fkazemian. they should be completely ignored by ``jupinx`` so I will look into this.

**Comment by mmcky** [comment]
support for ``only`` has now been implemented in ``jupinx``

**Comment by mmcky** [comment]
this is associated with #19

**Comment by mmcky** [comment]
we either need to add ``.. only:: jupyter`` in the RST source or we add support to allow jupinx to capture html targeted only blocks as an option. See PR https://github.com/QuantEcon/sphinxcontrib-jupyter/pull/91 which is in work.

**Comment by mmcky** [comment]
all ``.. only:: latex`` will be ignored. The only option I have allowed in the extension is to include ``html`` only blocks to mirror the html lecture set. Fixed by PR: https://github.com/QuantEcon/sphinxcontrib-jupyter/pull/92

**Comment by mmcky** [comment]
- [ ] @fkazemian can you please confirm.

**Comment by mmcky** [comment]
- [ ] @fkazemian would you mind rechecking this and close if fixed. Thanks.

**Comment by fkazemian** [comment]
Hi @mmcky , I'll check them now
- [ ] ./stationary_densities.rst:.. only:: latex
- [ ] ./index_undergrad.rst:.. only:: latex
- [ ] ./index_undergrad.rst:.. only:: latex
- [ ] ./linear_algebra.rst:.. only:: latex
- [ ] ./arma.rst:.. only:: latex
- [ ] ./pandas.rst:.. only:: latex
- [ ] ./pandas.rst:.. only:: latex
- [ ] ./pandas.rst:.. only:: latex
- [ ] ./mle.rst:.. only:: latex
- [ ] ./linear_models.rst:.. only:: latex
- [ ] ./index_postgrad.rst:.. only:: latex
- [ ] ./index_postgrad.rst:.. only:: latex
- [ ] ./optgrowth.rst:.. only:: latex
- [ ] ./ifp.rst:.. only:: latex
- [ ] ./ifp.rst:.. only:: latex
- [ ] ./ifp.rst:.. only:: latex
- [ ] ./ifp.rst:.. only:: latex
- [ ] ./index.rst:.. only:: latex
- [ ] ./index.rst:.. only:: latex
- [ ] ./lqramsey.rst:.. only:: latex
- [ ] ./lqramsey.rst:.. only:: latex
- [ ] ./lqramsey.rst:.. only:: latex
- [ ] ./pandas_panel.rst:.. only:: latex
- [ ] ./pandas_panel.rst:.. only:: latex
- [ ] ./pandas_panel.rst:.. only:: latex
- [ ] ./aiyagari.rst:.. only:: latex

**Comment by fkazemian** [comment]
@mmcky , All of them fixed but the only thing is ` index_postgrad `, `index_undergrad` and `index` are used two times .. only:: latex, 
```
.. only:: latex

    Quantitative Economics
```

and 

```
.. only:: latex

    Acknowledgements:  These lectures have benefitted greatly from comments and
    suggestion from our colleagues, students and friends.  Special thanks go to
    Anmol Bhandari, Long Bui, Jeong-Hun Choi, Chase Coleman, David Evans, Shunsuke Hori, 
    Chenghan Hou, Doc-Jin Jang, Spencer Lyon, Qingyin Ma, Akira Matsushita, 
    Matthew McKay, Tomohito Okabe, Alex Olssen, Nathan Palmer and Yixiao Zhou.

```
the first one is Ok, but I can't find the second one. so, I change the label to `Question` instead of `fixed`, and remove the label `bug`, If you think it's alright and index files is not an issue here for this specific problem, every thing is fine and it's ready to close. Thanks

**Comment by mmcky** [comment]
@fkazemian the ``latex`` blocks should be completely ignored. Is there an ``html`` with the first box in the rst file?

**Comment by mmcky** [comment]
thanks @fkazemian the Acknowledgements are treated differently in the `html` side and there is no corresponding ``html`` section. I think this can be closed.
