### ISSUE TITLE
FEAT: Add PDF Support

### ISSUE THREAD

**Issue by mmcky** [QuantEcon/lecture-source-py#113]
We will need to focus on PDF support.

It would be nice if PDF could be supported for individual lectures (in addition to the whole site). 

- [ ] use current RST to PDF route and hope recent changes haven't broken the LaTeX compilation

- [ ] write a custom LaTeXWriter for sphinx to build individual lectures - and a global pdf file.

**Comment by mmcky** [comment]
the biggest problem here is that we have removed `output` from the source `RST` files. So if we compile from `RST` using sphinx builder then it will be without output blocks. 

I have tried the conversion tool `wkhtmltopdf` as attached, but it does not produce good output.

[arma.pdf](https://github.com/QuantEcon/lecture-source-py/files/2564553/arma.pdf)

`nbconvert` is also not an option. The issue with using our `ipynb` layer is that it includes `html` to get support working for more advanced items like (equation numbering etc.).

**Comment by mmcky** [comment]
it looks like the issues are related to javascript load times. 

I will implement:
1. build `_build_website` in quantecon.build.lectures
2. sync `_build_website` to `s3`
3. run `wkhtmltopdf` using `s3` public address as a source (to save having to launch a local non-blocking python server in a threaded process and to use the same web server architecture)
4. sync pdf to `s3`

**Comment by mmcky** [comment]
@DrDrij can we get another badge for PDF download? We are now generating PDF's on a per lecture basis.

The files are currently located in ``_static/pdf/py/`` for `python` lectures.

**Comment by DrDrij** [comment]
@mmcky Thought 4 badges would be a bit excessive. How about something like this:

![image](https://user-images.githubusercontent.com/5886045/48503830-e6f7f080-e84b-11e8-9289-7e13a1503249.png)

**Comment by DrDrij** [comment]
Will we continuing to supply a full PDF link in the primary navigation?

**Comment by mmcky** [comment]
@DrDrij I will see if we can concatenate the PDF's together. I think Tom would like the ability to download the full site as PDF.

**Comment by mmcky** [comment]
lets assume we will concatenate so we can keep the general PDF button

**Comment by mmcky** [comment]
Issue with version numbers of `wkhtmltopdf`

https://github.com/mmcky/quantecon.build.lectures/issues/37

http://compare-lectures.quantecon.org/_static/pdf/py/arma.pdf

**Comment by mmcky** [comment]
hey @DrDrij the concensus (@natashawatkins and @jstac) liked the previous look. Perhaps we can keep this layout just change the `download` style to be similar to a tag (but with `pdf` and `ipynb` options)?

**Comment by DrDrij** [comment]
Will do!

**Comment by mmcky** [comment]
this is going to be an issue until we figure out how to include executed output in for `html` and `pdf` targets. The best solution for now is to use `wkhtmltopdf`

**Comment by jstac** [comment]
Note that @AnjuJoon is working on this.

@AnjuJoon, please reference this issue when you make your PR to add PDF files.

**Comment by jstac** [comment]
Much of the above discussion is redundant so I'm closing the issue.  In future, let's keep discussion of creating PDFs in the repo of the build system itself.
