### ISSUE TITLE
FEAT: Add QuantEcon Banner as Header in Notebooks

### ISSUE THREAD

**Issue by mmcky** [QuantEcon/lecture-source-py#114]
It would be great to add the QuantEcon banner at the top of every download notebook. @DrDrij can you advise on this. 

I am thinking of building a `download` set of notebooks that would include a header cell with

```html
<link rel="stylesheet" href="_static/css/qe-menubar.css">

<div class="qe-menubar">
        
<p class="qe-menubar-logo"><a href="https://quantecon.org/" title="quantecon.org"><img src="_static/img/qe-menubar-logo.png" alt="QuantEcon logo"> Quant<span>Econ</span></a></p>
        
<ul class="qe-menubar-nav">
                <li><a href="https://lectures.quantecon.org/" title="Lectures"><span>Lectures</span></a></li>
                <li><a href="https://quantecon.org/python_index.html" title="QuantEcon.py"><span>QuantEcon.py</span></a></li>
                <li><a href="https://quantecon.org/julia_index.html" title="QuantEcon.jl"><span>QuantEcon.jl</span></a></li>
                <li><a href="http://notebooks.quantecon.org/" title="Notebooks"><span>Notebooks</span></a></li>
                <li><a href="http://cheatsheets.quantecon.org/" title="Cheatsheets"><span>Cheatsheets</span></a></li>
                <li><a href="http://blog.quantecon.org/" title="Blog"><span>Blog</span></a></li>
                <li><a href="http://discourse.quantecon.org/" title="Forum"><span>Forum</span></a></li>
                <li><a href="https://github.com/QuantEcon/" title="Repository"><span class="show-for-sr">Repository</span></a></li>
                <li><a href="https://twitter.com/quantecon" title="Twitter"><span class="show-for-sr">Twitter</span></a></li>
            </ul>
</div>
```

but it doesn't seem to work. 

It looks like

![image](https://user-images.githubusercontent.com/8263752/48238620-b49b5d00-e41f-11e8-9074-e3a99e6bcf16.png)

perhaps I don't have all the assets in the right spot. Could you experiment and let me know what would be required?

**Comment by DrDrij** [comment]
@mmcky The notebook file is standalone right?

If a user downloads a lecture notebook file from the site how is the notebook to access images/css etc?

I'm thinking in your above example possibly putting the the whole of the css file inline inside a `<style type="text/css">...</style>` element. However, will still need access to the icons image.

**Comment by mmcky** [comment]
hey @DrDrij -- happy for the header to make internet calls for now. In the future (we can use the ``cell attachments`` to add assets for standalone notebooks)

**Comment by mmcky** [comment]
this has been added as a PR so closing issue
