### ISSUE TITLE
Support for 'note' blocks is incomplete in Jupinx

### ISSUE THREAD

**Issue by fkazemian** [QuantEcon/lecture-source-py#13]
![1](https://user-images.githubusercontent.com/20714542/44963550-b273d880-af6e-11e8-8bf9-be94e399e224.png)

amss.html

**Comment by mmcky** [comment]
I have added this as a feature request on the extension to allow for specific styling

https://github.com/QuantEcon/sphinxcontrib-jupyter/issues/80

@jstac do you mind if notes are just simple block quotes titled as a `Note`?

**Comment by mmcky** [comment]
Notes are now added but their contents are not being parsed with markup

![image](https://user-images.githubusercontent.com/8263752/45196376-3d224380-b29f-11e8-8ace-29c63d8eef81.png)

**Comment by mmcky** [comment]
This should be fixed by PR https://github.com/QuantEcon/sphinxcontrib-jupyter/pull/90

**Comment by fkazemian** [comment]
Hi @mmcky , Thanks
I saw something which is strange for me, 
in hist_dep_policies:
![screenshot from 2018-09-07 13-25-56](https://user-images.githubusercontent.com/20714542/45198193-a3f82a80-b2a8-11e8-8a58-9fe6a5bb4245.png)
![screenshot from 2018-09-07 14-10-31](https://user-images.githubusercontent.com/20714542/45198195-a5295780-b2a8-11e8-8191-7a3d1e463a3a.png)

As you can see Note is fine but citation failed, while its code is fine and when I run them locally I realised Note disappear and citation is fine! 

when I run it locally:
![screenshot from 2018-09-07 14-15-18](https://user-images.githubusercontent.com/20714542/45198236-e28de500-b2a8-11e8-9bfe-66c6e1e9c572.png)

code:
```
.. note::
      We occasionally hear confusion about the consequences of  recursive
      representations of government policies under our two timing protocols.
      It is incorrect to regard a recursive representation of the Ramsey plan
      as in any way 'solving a time-inconsistency problem'.  On the contrary,
      the evolution of the auxiliary state variable that augments the
      authentic ones under our first timing protocol ought to be viewed as
      *expressing* the time-inconsistency of a Ramsey plan.  Despite that, in
      literatures about practical monetary policy one sometimes hears
      interpretations that sell Ramsey plans in settings where our sequential
      timing protocol is the one that more accurately characterizes  decision
      making.  Please beware of discussions that toss around claims about
      credibility if you don't also see recursive representations of policies
      with the complete list of state variables appearing in our :cite:`chang1998credible` -like analysis that we present :ref:`below <sec:credible>`.
```

**Comment by mmcky** [comment]
this "should" be fixed also by the PR above. I will re-run now to test with latest extension. ``Jupinx`` in QuantEcon.lectures is static and not updating as we move to an installable extension.

**Comment by fkazemian** [comment]
Thanks @mmcky , I just changed the label

**Comment by mmcky** [comment]
thanks @fkazemian - just reran ``hist_dep_policies`` and looks like this is fixed. Closing.
