### ISSUE TITLE
badges in lecture are out of alignment

### ISSUE THREAD

**Issue by mmcky** [QuantEcon/lecture-source-py#130]
Badges are out of alignment

![image](https://user-images.githubusercontent.com/8263752/48881920-f38fd080-ee6b-11e8-9736-3d2bc40f2d0f.png)

I think this is becuase `nbconvert` is adding each of them in a separate `<p>` environment. 

- [ ] wait for theme change in https://github.com/QuantEcon/lecture-source-py/issues/113 before fixing

**Comment by DrDrij** [comment]
Alignment CSS and badge file added. Should be visible on next compilation.

**Comment by mmcky** [comment]
thanks @DrDrij I will test this out now

**Comment by mmcky** [comment]
they seem to be aligned vertically now and in the centre on my local build. Building for compare-lectures now.

![image](https://user-images.githubusercontent.com/8263752/49119357-21f22d80-f2fc-11e8-88cc-5fcf7b5a425f.png)

**Comment by DrDrij** [comment]
@mmcky Do you have qe.css version 2.9 on your local? The styles are present here: https://github.com/mmcky/quantecon.build.lectures/blob/master/theme/qe/css/qe.css

If you do, please inspect the badges, they should be in a markup similar to:

```
<ul class="badges">
<li>...</li>
<li>...</li>
<li>...</li>
</ul>
```

**Comment by mmcky** [comment]
Just needed the PR. Looking good now

![image](https://user-images.githubusercontent.com/8263752/49195963-35c19080-f3dd-11e8-8cf4-024e4fb5b52d.png)
