### ISSUE TITLE
Footer Navigation is Broken

### ISSUE THREAD

**Issue by mmcky** [QuantEcon/lecture-source-py#131]
![image](https://user-images.githubusercontent.com/8263752/49046863-b3dd3600-f229-11e8-97f7-0492261860b3.png)

Stuck on these two lectures -- must be hard coded in the `tpl` file?

**Comment by DrDrij** [comment]
https://github.com/mmcky/quantecon.build.lectures/pull/45

**Comment by mmcky** [comment]
@DrDrij is this now fixed? or have we just decided to hide them for now?

**Comment by mmcky** [comment]
removing priority as we currently aren't that concerned about `next` and `prev`

**Comment by jstac** [comment]
Can we close this @mmcky ?

**Comment by mmcky** [comment]
@jstac this functionality hasn't passed through `sphinx` to `sphinxcontrib-jupyter` so `next` and `prev` are not supported in the theme. I don't them we need them but I may transfer this to `sphinxcontrib-jupyter` as a missing feature
