### ISSUE TITLE
Syntax highlighting for errors

### ISSUE THREAD

**Issue by natashawatkins** [QuantEcon/lecture-source-py#133]
@DrDrij is it possible to implement highlighting for errors in the output? Ie. in the debugging lecture we are demonstrating errors, which in Jupyter are highlighted, but on our website just appear as plain text: http://compare-lectures.quantecon.org/py/debugging.html#

Thanks!

**Comment by DrDrij** [comment]
Looks like the markup is there. I will add some styles today.

**Comment by DrDrij** [comment]
Added to new build process CSS. Highlighting should be visible on next compilation.

**Comment by DrDrij** [comment]
@natashawatkins Ok to close? Highlighting appearing for me now: http://compare-lectures.quantecon.org/py/debugging.html

**Comment by natashawatkins** [comment]
Looks great! Thanks
