### ISSUE TITLE
It seems Jupinx has problem with some basic syntax

### ISSUE THREAD

**Issue by fkazemian** [QuantEcon/lecture-source-py#14]
in this picture you can see `** bold **` is working everywhere expect `** par value **`
![screenshot from 2018-09-03 13-08-24](https://user-images.githubusercontent.com/20714542/44966172-f8d03400-af7c-11e8-8aa9-b13723db722c.png)

amss2.html

**Comment by mmcky** [comment]
here is the source. It looks like `jupinx` has mistaken ``In this special case`` to be a title and interrupted the list. 

```
* In this special case

  - the **par value** :math:`b_{t+1}(s_t) = \bar b`  of government debt at time :math:`t` and Markov state :math:`s_t`  is constant across time and states,
     but :math:`\ldots`

  - the **market value** :math:`\frac{\bar b}{R_t(s_t)}` of government debt at time :math:`t`  varies as a time-invariant function of the Markov state :math:`s_t`
```

**Comment by mmcky** [comment]
@fkazemian it looks like this might be an issue in the source with the first element of the list being indented only 2 spaces when it should be 3. Can you see if that adjustment fixes this issue and then put together a PR to fix?

**Comment by fkazemian** [comment]
Hi @mmcky 
I was checking it now :D I'll make a PR for that
![screenshot from 2018-09-18 11-06-51](https://user-images.githubusercontent.com/20714542/45658576-23042300-bb33-11e8-9f94-b28aa4a70582.png)

**Comment by fkazemian** [comment]
Hi @mmcky PR #43. I change the label to Fixed and remove other labels.

**Comment by mmcky** [comment]
thanks @fkazemian
