### ISSUE TITLE
Install linearmodels on server

### ISSUE THREAD

**Issue by natashawatkins** [QuantEcon/lecture-source-py#140]
We need the `linearmodels` package for the OLS lecture - see here:  http://compare-lectures.quantecon.org/py/ols.html#Endogeneity

**Comment by mmcky** [comment]
thanks @natashawatkins would you mind collating a list of dependencies for `python` so we can document this?

**Comment by mmcky** [comment]
This is now done and will be updated in the next run.

**Comment by natashawatkins** [comment]
how should I do that?
