### ISSUE TITLE
Should we get rid of pip installs via bash commands?

### ISSUE THREAD

**Issue by natashawatkins** [QuantEcon/lecture-source-py#142]
![image](https://user-images.githubusercontent.com/21038129/49199132-707df580-f3ea-11e8-8556-0da2102b6721.png)

Looks not too great - from chang_ramsey.rst

**Comment by mmcky** [comment]
I don't mind them. We could use a `:hide-output:` if you like?

**Comment by natashawatkins** [comment]
Hi @mmcky, I think we should keep the pip installs but it would be nice to have the hide-output class you mentioned above
