### ISSUE TITLE
BUG: Issues with math

### ISSUE THREAD

**Issue by mmcky** [QuantEcon/lecture-source-py#146]
- [ ] ``discrete_dp``

![image](https://user-images.githubusercontent.com/8263752/49267095-d6cb4c80-f4ac-11e8-948e-b5c032d90225.png)

**Comment by mmcky** [comment]
check if this is resolved by: https://github.com/QuantEcon/lecture-source-py/pull/165

**Comment by natashawatkins** [comment]
Doesn't appear that #165 fixed this issue - I think we might not be able to combine lists and math environments on the site? It works in Jupyter

**Comment by mmcky** [comment]
hey @natashawatkins would you have time to see if changes to the source RST can fix this?

**Comment by AnjuJoon** [comment]
@mmcky,  this is fixed
