### ISSUE TITLE
replace bivariate_normal in kalman.rst

### ISSUE THREAD

**Issue by natashawatkins** [QuantEcon/lecture-source-py#150]
`bivariate_normal` will soon be deprecated - need something to replace with

**Comment by duncanhobbs** [comment]
You might be able to replace it with `scipy.stats.multivariate.normal`. I also saw that the QuantEcon/rvlib repository has a branch with some code for drawing from multivariate distributions [here](https://github.com/QuantEcon/rvlib/tree/multivariate).

**Comment by natashawatkins** [comment]
Thanks @duncanhobbs - will look into it.

**Comment by AnjuJoon** [comment]
@natashawatkins we have defined a function bivariate_normal in this lecture. So we will not face this problem again. Can we close this issue?
