### ISSUE TITLE
Hashes at the end of URLs?

### ISSUE THREAD

**Issue by natashawatkins** [QuantEcon/lecture-source-py#167]
Why do links from the index now have hashes at the end? ie. https://lectures.quantecon.org/py/python_essentials.html#

**Comment by mmcky** [comment]
this is an issue with ``sphinxcontrib-jupyter``. I will work on a fix when generating links to remove `#` when there are none.

**Comment by mmcky** [comment]
this PR will fix this issue: https://github.com/QuantEcon/sphinxcontrib-jupyter/pull/162

**Comment by mmcky** [comment]
this is now fixed
