### ISSUE TITLE
Example in Numba lecture is wrong?

### ISSUE THREAD

**Issue by natashawatkins** [QuantEcon/lecture-source-py#185]
![image](https://user-images.githubusercontent.com/21038129/51497434-143dbd80-1dfe-11e9-86c8-6955e0bec7ef.png)

**Comment by mmcky** [comment]
@natashawatkins do you know why this has changed?

**Comment by natashawatkins** [comment]
When I ran it a second time, the vectorised code seemed to run fast. I would recommend replacing with `%%timeit`

**Comment by jstac** [comment]
@shizejin and @DianaTZhu, might you have time to look at this?  

It seems surprising!

Perhaps we just need to increase `n` to get more realistic timings.

**Comment by shizejin** [comment]
Hi @jstac sure I would love to! But it seems I could not replicate this on my computer.

<img width="392" alt="Screen Shot 2019-06-28 at 7 44 39" src="https://user-images.githubusercontent.com/22466278/60307869-0fff6880-9979-11e9-978a-4be50c75b0d9.png">

Could this have been solved by the updates of numpy?

**Comment by jstac** [comment]
Thanks @shizejin. 

We use a recent version of numpy.  @mmcky, do you think this is something hardware specific?

I just tested on my machine and got a speed up but only factor 2.  

I'm going to increase `n` by x10, which does help stabilize on my machine and lead to significant speed gain.  @mmcky, please check the speed gain on the production machine once I've set `n` to `1_000_000`.

**Comment by DianaTZhu** [comment]
Hi @jstac, I tried and it doesn't seem to be a problem for me either. (I was using np version 1.15.4, different from @shizejin )

<img width="712" alt="Screen Shot 2019-06-27 at 8 11 41 PM" src="https://user-images.githubusercontent.com/46862343/60308632-d6e2dc00-9917-11e9-9082-0cd46286c6f8.png">

And yes -- increase n by 10 gives a speed-up of about 20 times when I tried it, so it should be better.

**Comment by jstac** [comment]
Thanks @DianaTZhu, I appreciate your review.  

@mmcky, I've pushed that change to master so please review when you have time.

**Comment by jstac** [comment]
@mmcky, can you please close when ready?
