### ISSUE TITLE
Images in short_path.rst are blurry + oversized

### ISSUE THREAD

**Issue by natashawatkins** [QuantEcon/lecture-source-py#186]
https://lectures.quantecon.org/jl/short_path.html

**Comment by mmcky** [comment]
Have you tried scaling them to 80%?

**Comment by natashawatkins** [comment]
This seems to be a rendering issue.. the image is scaled to 100% and it looks fine when I open the image file on my computer. @DrDrij do you have any ideas?

**Comment by DrDrij** [comment]
So using "scale" appears to set the html as `<img ... style="width:100%;height:100%;">`.

```
.. figure:: {{ figures_dir }}/graph2.png
   :scale: 100%
```

This isn't optimal as the scale value is relative to the container (content area width). So a 100% or 80% value will stretch/shrink the image to use that percentage of the content area. This isn't a problem if the image is wider than the content area. But here where the images are quite small they become stretched.

I'd recommend removing the scale directive for the graphs in this lecture.

**Comment by natashawatkins** [comment]
@mmcky I'm not sure how to preview the html once I changed this - would you be able to try the above solution?

**Comment by jstac** [comment]
Fixed.
