### ISSUE TITLE
Support for '.. only:: html' blocks is incomplete in Jupinx

### ISSUE THREAD

**Issue by fkazemian** [QuantEcon/lecture-source-py#19]
![screenshot from 2018-09-04 12-23-03](https://user-images.githubusercontent.com/20714542/45006635-59bf4100-b03d-11e8-8393-3b864edaa2bd.png)

 '.. only:: html' is used in 
```
./stationary_densities.rst:.. only:: html
./index_dynamic_programming.rst:.. only:: html
./index_time_series_models_grad.rst:.. only:: html
./index_undergrad.rst:.. only:: html
./index_undergrad.rst:.. only:: html
./index_dynamic_programming_squared.rst:.. only:: html
./linear_algebra.rst:.. only:: html
./index_tools_and_techniques_grad.rst:.. only:: html
./index_tools_and_techniques.rst:.. only:: html
./arma.rst:.. only:: html
./pandas.rst:.. only:: html
./pandas.rst:.. only:: html
./pandas.rst:.. only:: html
./zreferences.rst:.. only:: html
./mle.rst:.. only:: html
./linear_models.rst:.. only:: html
./index_advanced_python_programming.rst:.. only:: html
./index_multi_agent_models.rst:.. only:: html
./index_tools_and_techniques_undergrad.rst:.. only:: html
./index_learning_python.rst:.. only:: html
./index_postgrad.rst:.. only:: html
./index_postgrad.rst:.. only:: html
./optgrowth.rst:.. only:: html
./index_multi_agent_models_undergrad.rst:.. only:: html
./index_time_series_models.rst:.. only:: html
./ifp.rst:.. only:: html
./ifp.rst:.. only:: html
./ifp.rst:.. only:: html
./ifp.rst:.. only:: html
./index_dynamic_programming_grad.rst:.. only:: html
./index.rst:.. only:: html
./index.rst:.. only:: html
./index_multi_agent_models_grad.rst:.. only:: html
./index_python_scientific_libraries.rst:.. only:: html
./lqramsey.rst:.. only:: html
./lqramsey.rst:.. only:: html
./lqramsey.rst:.. only:: html
./pandas_panel.rst:.. only:: html
./pandas_panel.rst:.. only:: html
./pandas_panel.rst:.. only:: html
./index_data_and_empirics.rst:.. only:: html
./aiyagari.rst:.. only:: html
./index_dynamic_programming_undergrad.rst:.. only:: html
```

I checked randomly and realised Jupinx is not able to support '.. only:: html' blocks

**Comment by mmcky** [comment]
this should be fixed by: https://github.com/QuantEcon/sphinxcontrib-jupyter/pull/85

**Comment by mmcky** [comment]
- [ ] test this will latest version of sphinxcontrib-jupyter once PR is merged.

**Comment by mmcky** [comment]
OK - thinking this through given jupyter notebooks essentially support the paradigms associated with `html` I will add a config to jupinx that allows jupinx to register ``.. only:: html`` elements during compilation.

**Comment by fkazemian** [comment]
Thanks, (ifp):
![screenshot from 2018-09-07 13-52-39](https://user-images.githubusercontent.com/20714542/45198626-cb4ff700-b2aa-11e8-94dd-2fbc53a68e3f.png)

code:
```
.. only:: html

    In particular, it :download:`can be shown </_static/pdfs/pi2.pdf>` that the path :math:`\{c_t\}`
    generated from :math:`(a_0,z_0) \in S` using policy function :math:`c^*` is
    the unique optimal path from :math:`(a_0,z_0) \in S`

.. only:: latex

    In particular, it `can be shown <https://lectures.quantecon.org/_downloads/pi2.pdf>`__ that the path :math:`\{c_t\}`
    generated from :math:`(a_0,z_0) \in S` using policy function :math:`c^*` is
    the unique optimal path from :math:`(a_0,z_0) \in S`
```
![screenshot from 2018-09-07 13-52-20](https://user-images.githubusercontent.com/20714542/45198647-ecb0e300-b2aa-11e8-8607-04014cc1b17a.png)
```

.. only:: html

    It is :download:`known </_static/pdfs/pi2.pdf>` that

```
![screenshot from 2018-09-07 13-51-51](https://user-images.githubusercontent.com/20714542/45198652-f5a1b480-b2aa-11e8-8f77-99258830853e.png)
```
.. only:: html

    Given our assumptions, it is :download:`known </_static/pdfs/pi2.pdf>` that

.. only:: latex

    Given our assumptions, it is `known <https://lectures.quantecon.org/_downloads/pi2.pdf>`__ that

```
![screenshot from 2018-09-07 13-50-44](https://user-images.githubusercontent.com/20714542/45198679-19fd9100-b2ab-11e8-9fa3-b52270ca593d.png)
```

.. only:: html

    * For further details on economic intuition, implication and models, see :cite:`Ljungqvist2012`
    * Proofs of all mathematical results stated below can be found in :download:`this paper </_static/pdfs/pi2.pdf>`

.. only:: latex

    * For further details on economic intuition, implication and models, see :cite:`Ljungqvist2012`
    * Proofs of all mathematical results stated below can be found in `this paper <https://lectures.quantecon.org/_downloads/pi2.pdf>`__
```

**Comment by fkazemian** [comment]
linear_algebra
![screenshot from 2018-09-10 09-59-12](https://user-images.githubusercontent.com/20714542/45270833-e1e19280-b4e4-11e8-8231-3efb00a76826.png)
```
.. only:: html

    The solution is known to be :math:`\hat x = (A'A)^{-1}A'y` --- see for example
    chapter 3 of :download:`these notes </_static/pdfs/course_notes.pdf>`

.. only:: latex

    The solution is known to be :math:`\hat x = (A'A)^{-1}A'y` --- see for example
    chapter 3 of `these notes <https://lectures.quantecon.org/_downloads/course_notes.pdf>`__
```

**Comment by fkazemian** [comment]
linear_models
![screenshot from 2018-09-10 10-58-19](https://user-images.githubusercontent.com/20714542/45271302-430b6500-b4e9-11e8-9c86-64e91e5e1767.png)
```

.. only:: html

    This is the *globally stable case* --- see :download:`these notes </_static/pdfs/iteration_notes.pdf>` for more a theoretical treatment

.. only:: latex

    This is the *globally stable case* --- see `these notes <https://lectures.quantecon.org/_downloads/iteration_notes.pdf>`__ for more a theoretical treatment  
```

**Comment by fkazemian** [comment]
lqramsey
![screenshot from 2018-09-10 15-46-38](https://user-images.githubusercontent.com/20714542/45278767-ec665100-b511-11e8-9317-31bd6e39dcf0.png)

```
.. only:: html

    See the original :download:`manuscript </_static/pdfs/firenze.pdf>` for comments and interpretation

.. only:: latex

    See the original `manuscript <https://lectures.quantecon.org/_downloads/firenze.pdf>`__ for comments and interpretation

```
![screenshot from 2018-09-10 15-45-39](https://user-images.githubusercontent.com/20714542/45278772-f2f4c880-b511-11e8-861d-08f69e577ae5.png)
```
.. only:: html

    See the original :download:`manuscript </_static/pdfs/firenze.pdf>` for comments and interpretation

.. only:: latex

    See the original `manuscript <https://lectures.quantecon.org/_downloads/firenze.pdf>`__ for comments and interpretation
```

**Comment by fkazemian** [comment]
optgrowth

![screenshot from 2018-09-11 17-10-36](https://user-images.githubusercontent.com/20714542/45344176-56502a80-b5e6-11e8-864e-29f091b28c26.png)

```
.. only:: html

    One good choice from both respects is continuous piecewise linear interpolation (see :download:`this paper </_static/pdfs/3ndp.pdf>` for further discussion)

.. only:: latex

    One good choice from both respects is continuous piecewise linear interpolation (see `this paper <https://lectures.quantecon.org/_downloads/3ndp.pdf>`__ for further discussion)
```

**Comment by fkazemian** [comment]
pandas

![screenshot from 2018-09-12 09-58-53](https://user-images.githubusercontent.com/20714542/45394370-91e50600-b673-11e8-830e-a007a0375c2d.png)
```
.. only:: html

    A dataset of daily closing prices for the above firms can be found in ``pandas/data/ticker_data.csv``, and can be downloaded
    :download:`here </_static/code/pandas/data/ticker_data.csv>`

.. only:: latex

    A dataset of daily closing prices for the above firms can be found in ``pandas/data/ticker_data.csv``, and can be downloaded
    `here <https://lectures.quantecon.org/_downloads/pandas/data/ticker_data.csv>`__

```

**Comment by fkazemian** [comment]
pandas_panel:

![screenshot from 2018-09-12 10-08-51](https://user-images.githubusercontent.com/20714542/45394950-de7e1080-b676-11e8-81e8-e4c2f89daa0b.png)
```
.. only:: html

    The csv file can be found in ``pandas_panel/countries.csv``, and can be downloaded 
    :download:`here </_static/code/pandas_panel/countries.csv>`

.. only:: latex

    The csv file can be found in ``pandas_panel/countries.csv``, and can be downloaded 
    `here <https://lectures.quantecon.org/_downloads/pandas_panel/countries.csv>`__

```
![screenshot from 2018-09-12 10-07-57](https://user-images.githubusercontent.com/20714542/45394954-e1790100-b676-11e8-8373-ad05d7b45e3e.png)
```
.. only:: html

    The dataset ``pandas_panel/realwage.csv`` can be downloaded 
    :download:`here </_static/code/pandas_panel/realwage.csv>`

.. only:: latex

    The dataset ``pandas_panel/realwage.csv`` can be downloaded 
    `here <https://lectures.quantecon.org/_downloads/pandas_panel/realwage.csv>`__
```

**Comment by mmcky** [comment]
OK - the https://github.com/QuantEcon/sphinxcontrib-jupyter/pull/92 PR should fix this issue.  This allows the `conf.py` to be setup to allow passthrough of `html` only blocks to prevent duplication. This is a convenient option in our case as we can then support `html`, `jupyter`, and `latex`

**Comment by mmcky** [comment]
- [ ] review latest on compare-lectures.quantecon.org (@fkazemian I have just updated the comparison site can you check if these are fixed now). Thanks.

**Comment by fkazemian** [comment]
Hi @mmcky , Thanks, I checked and realised it is not skipping the content when we are using html and latex tags anymore, but it seems to have some problems with links: 
![screenshot from 2018-09-12 17-20-06](https://user-images.githubusercontent.com/20714542/45459115-30d43580-b73a-11e8-8be3-034f6a087f78.png)

![screenshot from 2018-09-12 17-19-30](https://user-images.githubusercontent.com/20714542/45459117-33368f80-b73a-11e8-9b5b-170e94c4e557.png)

![screenshot from 2018-09-12 17-19-06](https://user-images.githubusercontent.com/20714542/45459119-35005300-b73a-11e8-9bc2-998feb647c6b.png)

![screenshot from 2018-09-12 17-17-55](https://user-images.githubusercontent.com/20714542/45459124-3762ad00-b73a-11e8-81ed-ffeee21ed1d6.png)

![screenshot from 2018-09-12 17-16-51](https://user-images.githubusercontent.com/20714542/45459126-3893da00-b73a-11e8-8799-0192e8b64cd6.png)

![screenshot from 2018-09-12 17-16-14](https://user-images.githubusercontent.com/20714542/45459128-3a5d9d80-b73a-11e8-9030-c3f25210e079.png)

![screenshot from 2018-09-12 17-20-48](https://user-images.githubusercontent.com/20714542/45459129-3b8eca80-b73a-11e8-9a71-0394a2f223b8.png)

**Comment by mmcky** [comment]
@fkazemian upon inspection I think these are special links types `:download:`. 
This PR should fix the download links. 

https://github.com/QuantEcon/sphinxcontrib-jupyter/pull/106

@fkazemian can you let me know if any of these are not `:download:` type links

**Comment by mmcky** [comment]
- [ ] @fkazemian would you mind reviewing this issue and letting me know if I can close?

**Comment by fkazemian** [comment]
Hi @mmcky It is fixed and I change the label to fixed

**Comment by mmcky** [comment]
thanks @fkazemian
