### ISSUE TITLE
scale of figures

### ISSUE THREAD

**Issue by fkazemian** [QuantEcon/lecture-source-py#20]
Figures with the scale of 100% is too big and  it seems a little bit unusual, shall we change the size? 

(for example: career)
![screenshot from 2018-09-05 10-38-15](https://user-images.githubusercontent.com/20714542/45064882-a2d4cb00-b0f9-11e8-9d72-9917f489af13.png)

**Comment by mmcky** [comment]
thanks @fkazemian - I agree. Can you post the source from career.rst.

**Comment by fkazemian** [comment]
Hi @mmcky 
```

.. figure:: /_static/figures/career_solutions_ex3_py.png
   :scale: 100%

```

**Comment by fkazemian** [comment]
![screenshot from 2018-09-05 14-36-06](https://user-images.githubusercontent.com/20714542/45071787-513d3800-b11b-11e8-9257-ef713abe5743.png)
(coleman_policy_iter)
code:
```
.. figure:: /_static/figures/col_pol_bij1.png
    :scale: 50%
```

```
.. figure:: /_static/figures/col_pol_bij2.png
    :scale: 50%
```

**Comment by fkazemian** [comment]
finite_markov
![screenshot from 2018-09-07 11-19-03](https://user-images.githubusercontent.com/20714542/45193411-3096ee80-b291-11e8-9f7a-be9fd6eb066d.png)
```
.. figure:: /_static/figures/web_graph.png
   :scale: 60%
```

![screenshot from 2018-09-07 11-17-25](https://user-images.githubusercontent.com/20714542/45193428-486e7280-b291-11e8-9339-7fac73b16d2f.png)
```
.. figure:: /_static/figures/mc_aperiodicity2.png
    :scale: 100%

```
![screenshot from 2018-09-07 11-14-35](https://user-images.githubusercontent.com/20714542/45193444-58865200-b291-11e8-9d94-ab049d648256.png)
```
.. figure:: /_static/figures/hamilton_graph.png
   :scale: 80%

```
![screenshot from 2018-09-07 11-16-35](https://user-images.githubusercontent.com/20714542/45193458-689e3180-b291-11e8-8520-1d90608e2712.png)
```
.. figure:: /_static/figures/mc_irreducibility1.png
    :scale: 100%

```
![screenshot from 2018-09-07 11-16-56](https://user-images.githubusercontent.com/20714542/45193468-76ec4d80-b291-11e8-9395-15e25a924038.png)
```
.. figure:: /_static/figures/mc_irreducibility2.png
    :scale: 100%
```
![screenshot from 2018-09-07 11-17-09](https://user-images.githubusercontent.com/20714542/45193484-8f5c6800-b291-11e8-9de1-f3b6f340322d.png)
```
.. figure:: /_static/figures/mc_aperiodicity1.png
    :scale: 100%
```

**Comment by fkazemian** [comment]
Figures in most of the lectures have a serious problem about their size
![screenshot from 2018-09-12 13-55-54](https://user-images.githubusercontent.com/20714542/45401411-d5e80300-b693-11e8-9796-ee615970b21c.png)

**Comment by mmcky** [comment]
@fkazemian can you check the generated `html` to see what the source of this issue is. Is `jupinx` ignoring the ``:scale:`` setting?

**Comment by fkazemian** [comment]
Hi @mmcky 
I just checked coleman_policy_iter again, 
it was like: 
https://user-images.githubusercontent.com/20714542/45071787-513d3800-b11b-11e8-9257-ef713abe5743.png

I tried to change the scale of firs figure to 10% instead of 50% and it became like this:
![screenshot from 2018-09-17 14-50-11](https://user-images.githubusercontent.com/20714542/45606539-483c5700-ba89-11e8-9127-68dd646d3293.png)
so I realised Jupinx is not ignoring the :scale: 

This problem is not for all figures but there are some figures which need to fix.
now the question is why in the live version they are alright but in the generated version not, while Jupinx is not ignoring the scale.

**Comment by mmcky** [comment]
good question @fkazemian.

**Comment by mmcky** [comment]
@fkazemian taking a closer look at `career`. If we specify

```html
<img src="_static/figures/career_solutions_ex3_py.png" style="width:100%;height:100%">
```

in html is the scale interpreted as 100% of the figure size or 100% of the page size? Do you know?

**Comment by mmcky** [comment]
@fkazemian ok I think the issue here is that we have specified `:scale: 100%` in the source and our extension is making the figure larger than its original size to fit the page width. I think that is the correct behaviour for `:scale:` so perhaps we need to update our source RST? What do you think?

**Comment by fkazemian** [comment]
some of the figure like career.rst has the scale of 50% which has the same problem, I think we should change RST or If the problem is about what I told in previous comment, we should solve that. right?

**Comment by mmcky** [comment]
@fkazemian would you mind having a look at figures in general with the latest adjustments to theme. I think they look pretty good now and we can always adjust via `:scale:` if needed in the rst.

**Comment by fkazemian** [comment]
@mmcky 

career    **is fixed**
it was 
![1](https://user-images.githubusercontent.com/20714542/45854409-4e367e80-bd8e-11e8-9db1-b74dd288f5f6.png)

and now it is  like:
![screenshot from 2018-09-21 11-02-07](https://user-images.githubusercontent.com/20714542/45854312-de27f880-bd8d-11e8-92b5-a0428201b218.png)

coleman_policy_iter  **is not fixed**
it was 
![2](https://user-images.githubusercontent.com/20714542/45854419-5f7f8b00-bd8e-11e8-959a-4a7784bc44ac.png)
and now is
![screenshot from 2018-09-21 11-03-23](https://user-images.githubusercontent.com/20714542/45854353-07e11f80-bd8e-11e8-818f-9cb6a7362ee6.png)

finite_markov **is not fixed**
it was 
![3](https://user-images.githubusercontent.com/20714542/45854435-6f976a80-bd8e-11e8-811f-77d7495c8d12.png)

and now is 

![screenshot from 2018-09-21 11-04-29](https://user-images.githubusercontent.com/20714542/45854386-2e9f5600-bd8e-11e8-836b-2bb1097b9cdd.png)

**Comment by mmcky** [comment]
thanks @fkazemian -- the only thing I can think of is that markdown image scaling is working without constraints to the ``html`` page. The aspect ration of the graph in ``finite_markov`` seems better than what we had before. Does changing the scale affect the output. Should we just update the RST for these two cases?
- [ ] ``finite_markov``
- [ ] ``coleman_policy_iter``

**Comment by fkazemian** [comment]
Hi @mmcky  I just checked finite_markov, It is not changing by different scales!

**Comment by fkazemian** [comment]
@mmcky I also test

```
.. figure:: /_static/figures/web_graph.png
   :scale: 100%

<img src=_static/figures/web_graph.png style="width:100%;height:100%">

```
and 

```
.. figure:: /_static/figures/web_graph.png
   :scale: 100%

<img src=_static/figures/web_graph.png style="width:50%;height:50%">

```

both of them are the same:
![screenshot from 2018-09-24 15-59-55](https://user-images.githubusercontent.com/20714542/45939105-518e6c00-c013-11e8-85d5-5d2d85648912.png)

**Comment by natashawatkins** [comment]
Yeah I'm confused about why jupinx now is inserting really large figures in the jupyter notebooks, which is wasn't doing in the old repository. Was there some change in the settings?

**Comment by mmcky** [comment]
hey @DrDrij what about using ``:scale:`` which preserves the aspect ratio? I don't think we will want to be contained to just setting based on class options.

**Comment by DrDrij** [comment]
@mmcky No worries. I'll reverse the CSS for overriding width.

**Comment by DrDrij** [comment]
I've kept a `max-width:100%;` style on images - so images shouldn't be larger than their parent element (images shouldn't break out of the content area).

So images can now be adjusted manually - but will never extend the content area.

**Comment by mmcky** [comment]
perfect - thanks @DrDrij

**Comment by mmcky** [comment]
I think we can now close this issue. Any further issues relating to scale of figures can be identified in the next comparison review.
