### ISSUE TITLE
error after following instructtions

### ISSUE THREAD

**Issue by jstac** [QuantEcon/lecture-source-py#200]
@DrDrij 

Following the instructions on a fresh install led to an error after `make notebooks` --- complains about a
missing sphinx extesion
 
![screenshot_2019-02-25_16-48-36](https://user-images.githubusercontent.com/3887684/53316627-b597c200-391c-11e9-96e6-4469c1ae4628.png)

**Comment by DrDrij** [comment]
@jstac Looks like you may have possibly missed `make setup`? You've written it in the installation section of the Readme but left it out of the workflow section. Please try `make setup` and let me know if you get the same issue.


**➜  Projects git clone https://github.com/QuantEcon/lecture-source-py.git**
Cloning into 'lecture-source-py'...
remote: Enumerating objects: 131, done.
remote: Counting objects: 100% (131/131), done.
remote: Compressing objects: 100% (90/90), done.
remote: Total 2576 (delta 68), reused 87 (delta 37), pack-reused 2445
Receiving objects: 100% (2576/2576), 30.02 MiB | 3.72 MiB/s, done.
Resolving deltas: 100% (1330/1330), done.
**➜  Projects cd lecture-source-py** 
**➜  lecture-source-py git:(master) make setup**
pip install -r requirements.txt
Requirement already satisfied: sphinxcontrib-bibtex in /Users/acs/anaconda3/lib/python3.7/site-packages (from -r requirements.txt (line 1)) (0.4.1)
Requirement already satisfied: quantecon in /Users/acs/anaconda3/lib/python3.7/site-packages (from -r requirements.txt (line 2)) (0.4.3)
...
**➜  lecture-source-py git:(master) make notebooks**
make jupyter
Running Sphinx v1.7.8
making output directory...
...
writing output... [100%] zreferences                                                                   
copying static files... done
build succeeded, 1 warnings.
**➜  lecture-source-py git:(master) make view**
make preview
cd _build/jupyter/ && jupyter notebook
...
The Jupyter Notebook is running at:
http://localhost:8888/?token=87f32769c421c144e15653c98de90258f9b1e80daa79dd18
...

**Comment by mmcky** [comment]
The PR #200 should have fixed this issue. Closing.
