### ISSUE TITLE
Support for ordered lists with unicode symbols is incomplete in Jupinx

### ISSUE THREAD

**Issue by fkazemian** [QuantEcon/lecture-source-py#21]
(chang_credible)

![screenshot from 2018-09-05 10-57-33](https://user-images.githubusercontent.com/20714542/45066727-09aab200-b103-11e8-896e-1ec72cfb81c3.png)

```
A government strategy :math:`\sigma` and an allocation rule
:math:`\alpha` are said to constitute a *sustainable plan* (SP) if

i.   :math:`\sigma` is admissible

ii.  Given :math:`\sigma`, :math:`\alpha` is competitive

iii. After any history :math:`\vec h^{t-1}`, the continuation of :math:`\sigma` 
     is optimal for the government; i.e., the sequence :math:`\vec h_t` induced 
     by :math:`\sigma` after :math:`\vec h^{t-1}` maximizes over :math:`CE_\pi` 
     given :math:`\alpha`

```

![screenshot from 2018-09-05 10-57-33 copy](https://user-images.githubusercontent.com/20714542/45066732-0d3e3900-b103-11e8-8421-a51de8b5bfaf.png)

```

i.   A period :math:`0` action :math:`\hat h \in \Pi` that the public
     expects the government to take, together with subsequent within-period
     consequences :math:`m(\hat h), x(\hat h)` when the government acts as
     expected

ii.  For any first period action :math:`h \neq \hat h` with
     :math:`h \in CE_\pi^0`, a pair of within-period consequences
     :math:`m(h), x(h)` when the government does not act as the public had
     expected

iii. For every :math:`h \in \Pi`, a pair
     :math:`(w'(h), \theta'(h))\in S` to carry into next period
```

![screenshot from 2018-09-05 10-58-09](https://user-images.githubusercontent.com/20714542/45066736-10392980-b103-11e8-97db-2f05abb5d184.png)
```

**Proposition:**

i.  If :math:`Z \subset \tilde D(Z)`, then :math:`\tilde D(Z) \subset S` (‘self-generation’)

ii. :math:`S = \tilde D(S)` (‘factorization’)


**Proposition:**

i.  Monotonicity of :math:`\tilde D`: :math:`Z \subset Z'` implies :math:`\tilde D(Z) \subset \tilde D(Z')`

ii. :math:`Z` compact implies that :math:`\tilde D(Z)` is compact
```

**Comment by fkazemian** [comment]
(chang_ramsey)

![screenshot from 2018-09-05 12-16-24](https://user-images.githubusercontent.com/20714542/45067657-6f00a200-b107-11e8-9394-8684d08247c8.png)

```
**Proposition:**

i.  If :math:`Z \subset \tilde D(Z)`, then :math:`\tilde D(Z) \subset S` (‘self-generation’)

ii. :math:`S = \tilde D(S)` (‘factorization’)


**Proposition:**

i.  Monotonicity of :math:`\tilde D`: :math:`Z \subset Z'` implies :math:`\tilde D(Z) \subset \tilde D(Z')`

ii. :math:`Z` compact implies that :math:`\tilde D(Z)` is compact

```

**Comment by mmcky** [comment]
@jstac are you happy for these lists to be `enumerated` lists? Technically `sphinx` only supports enumerated and bullet so html writer must be intercepting these are keeping the `i` etc. I can dig a bit further if you like. 

@fkazemian there are some math formatting collisions (issue #12) - is this what you mean by `unicode`?

**Comment by jstac** [comment]
@mmcky Yes, that's fine.  No big deal.

**Comment by mmcky** [comment]
thanks @jstac. @fkazemian can you review these cases you have reported. If they are well formed lists we can close this issue.

**Comment by fkazemian** [comment]
Hi @mmcky I just checked them, theyre well formed lists, So I change the label to Fixed. Thanks

**Comment by mmcky** [comment]
thanks @fkazemian
