### ISSUE TITLE
Add GitHub source link to lectures

### ISSUE THREAD

**Issue by natashawatkins** [QuantEcon/lecture-source-py#218]
@AakashGC

Add a GitHub button to the lectures (right-aligned) that links to the source rst (this repo) so that people find it easier to make contributions.

On this note, maybe we should have a section on the website with instructions on how to contribute to the lectures?

**Comment by jstac** [comment]
Thanks guys.  Let's get that GH button up for starters.  It would be great if the button on lecture X led to the rst file for lecture X.

**Comment by AakashGfude** [comment]
@DrDrij @natashawatkins @jstac I have added a github button which points to the file in this repository.  Do tell me if it looks ok 
![image](https://user-images.githubusercontent.com/6542997/55522178-933d5500-56cf-11e9-99e7-6947cea5533d.png)

**Comment by jstac** [comment]
Perfect, thanks :-)
