### ISSUE TITLE
Remove index lectures from testing status page

### ISSUE THREAD

**Issue by natashawatkins** [QuantEcon/lecture-source-py#219]
https://lectures.quantecon.org/status.html

**Comment by mmcky** [comment]
@AakashGfude can we add a filter to the `coverage` report generator to skip files which fit a set of patterns such as `index*`. We should supply this as an option: `jupyter_coverage_skip = []`

**Comment by shlff** [comment]
Thanks, @natashawatkins , @mmcky and @AakashGfude  , I find that the index lecture above has been removed.

I am wondering whether this issue has been solved? Shall we close this issue?

**Comment by mmcky** [comment]
thanks @shlff
