### ISSUE TITLE
Support for comment with '..' is incomplete in Jupinx

### ISSUE THREAD

**Issue by fkazemian** [QuantEcon/lecture-source-py#23]
I think Jupinx is not able to support comment with `..` . 

As you can see in classical_filtering
![screenshot from 2018-09-05 13-56-19](https://user-images.githubusercontent.com/20714542/45071016-9a8b8880-b117-11e8-9f4c-bc6d8a05cab4.png)
 
 and in  arellano
![1](https://user-images.githubusercontent.com/20714542/45071065-d0c90800-b117-11e8-92e3-d753782c5a7a.png)

I think the text after `..` is a comment and I just delete them in #18 and #22.

**Comment by fkazemian** [comment]
Thanks @mmcky , shall I close both PRs?

**Comment by fkazemian** [comment]
Hi @mmcky I just checked this, It works fine. I change the label bug to fixed

**Comment by mmcky** [comment]
great - thanks @fkazemian
