### ISSUE TITLE
Support for '.. epigraph::' is incomplete in Jupinx

### ISSUE THREAD

**Issue by fkazemian** [QuantEcon/lecture-source-py#24]
`.. epigraph::` is used only in these lectures:

```
./rst_files/numpy.rst:.. epigraph::
./rst_files/rational_expectations.rst:.. epigraph::
./rst_files/markov_asset.rst:.. epigraph::
./rst_files/markov_asset.rst:.. epigraph::
./rst_files/mccall_model.rst:.. epigraph::
./rst_files/debugging.rst:.. epigraph::
./rst_files/linear_models.rst:.. epigraph::

```

which seems Jupinx is not able to support this markdown very well. 
debugging:
![screenshot from 2018-09-05 15-00-33](https://user-images.githubusercontent.com/20714542/45072409-23a5be00-b11e-11e8-9643-5dd5b57d2a98.png)

numpy:
![screenshot from 2018-09-05 15-06-43](https://user-images.githubusercontent.com/20714542/45072432-3c15d880-b11e-11e8-81cb-a3196e41d476.png)

rational_expectations:
![screenshot from 2018-09-05 15-07-10](https://user-images.githubusercontent.com/20714542/45072444-5354c600-b11e-11e8-97ed-db0220c99303.png)

markov_asset:
![screenshot from 2018-09-05 15-07-46](https://user-images.githubusercontent.com/20714542/45072457-69fb1d00-b11e-11e8-8a79-538264787d9f.png)

mccall_model:
![screenshot from 2018-09-05 15-08-07](https://user-images.githubusercontent.com/20714542/45072479-7d0ded00-b11e-11e8-87e9-fa073634b074.png)

linear_models:
![screenshot from 2018-09-05 15-08-39](https://user-images.githubusercontent.com/20714542/45072498-8e56f980-b11e-11e8-95f0-2456548e105d.png)

**Comment by mmcky** [comment]
@fkazemian this has been updated in the `jupinx` extension to recognise ``epigraph`` so that they are now all complete at the notebook level. However the ``nbconvert`` to ``html`` step from the notebook is producing the grey around the text.

@DrDrij the `nbconvert` step produces the following html

```html
<div class="cell border-box-sizing text_cell rendered"><div class="prompt input_prompt">
</div><div class="inner_cell">
<div class="text_cell_render border-box-sizing rendered_html">

<pre><code>“Let’s be clear: the work of science has nothing whatever to do with consensus.
Consensus is the business of politics. Science, on the contrary, requires only one
investigator who happens to be right, which means that he or she has results that are
verifiable by reference to the real world. In science consensus is irrelevant.
What is relevant is reproducible results.” – Michael Crichton</code></pre>

</div>
```

**Comment by mmcky** [comment]
@DrDrij let me know if we should setup a class pass through for this as well.

**Comment by mmcky** [comment]
- [ ] @mmky work on injecting `html` into markdown cells with the correct class assignment for @DrDrij to edit in the theme. I think I will try:

```
.. only:: html

   <class={}>
```
and wrap the epigraph object?

**Comment by DrDrij** [comment]
@mmcky It appears you have already fixed this? The mentioned lectures on the compare site are no longer being wrapped in <pre><code> elements - and thus displaying without the gray background.

**Comment by mmcky** [comment]
Fixed.
