### ISSUE TITLE
Support for footnote is incomplete in Jupinx

### ISSUE THREAD

**Issue by fkazemian** [QuantEcon/lecture-source-py#25]
It seems footnotes are failed in Jupinx.
For example dyn_stack:
![screenshot from 2018-09-07 10-27-24](https://user-images.githubusercontent.com/20714542/45192259-a9df1300-b28a-11e8-84d9-dc2f8b83909f.png)
code:
`Define the government's one-period loss function [#f1]_`

![screenshot from 2018-09-07 10-31-47](https://user-images.githubusercontent.com/20714542/45192261-aba8d680-b28a-11e8-8c3e-7ef284ce6955.png)

![screenshot from 2018-09-07 10-32-08](https://user-images.githubusercontent.com/20714542/45192262-ad729a00-b28a-11e8-9ed4-ebfbe21d647f.png)

![screenshot from 2018-09-07 10-32-55](https://user-images.githubusercontent.com/20714542/45192266-b06d8a80-b28a-11e8-83ce-3c5aae897c9e.png)
```

.. rubric:: Footnotes

.. [#f1] The problem assumes that there are no cross products between states and controls in the return function.  A simple transformation  converts a problem whose return function has cross products into an equivalent problem that has no cross products. For example, see :cite:`HansenSargent2008` (chapter 4, pp. 72-73).

.. [#f2] The government would make different choices were it to choose sequentially, that is,  were it to select its time :math:`t` action at time :math:`t`. See the lecture on :doc:`history dependent policies <hist_dep_policies>`

.. [#f8] :cite:`HansenSargent2008` (chapter 16), uses this model as a laboratory to illustrate an equilibrium concept featuring robustness in which at least one of the agents has doubts about the stochastic specification of the demand shock process.

.. [#f9] They used this method to compute a rational expectations competitive equilibrium.  Their key step was to eliminate price and output by substituting from the inverse demand curve and the production function into the firm's first-order conditions to get a difference equation in capital.

.. [#f10] These calculations were performed by functions located in `dyn_stack/oligopoly.py <https://github.com/QuantEcon/QuantEcon.lectures.code/blob/master/dyn_stack/oligopoly.py>`_.

.. [#f12] For another application of the techniques in this lecture and how they related to the method recommended by :cite:`KydlandPrescott1980`, please see :doc:`this lecture <hist_dep_policies>` .

```

**Comment by mmcky** [comment]
This PR should fix this issue: https://github.com/QuantEcon/sphinxcontrib-jupyter/pull/99

**Comment by mmcky** [comment]
- [ ] ``jupinx`` should be updated to include clickable footnotes to return to the actual footnote location in the text.

**Comment by mmcky** [comment]
@DrDrij still not sure how to support rendering of the footnotes (within the text). The ``<sup>`` markup is passing through but the markdown (which is embedded in the html) is clearly not rendering via ``nbconvert``. Is there a way to fix this in ``html`` -- otherwise I may need to add ``html`` links in the sup. Could you let me know what you would need (just a ``<aref>``) and I will update jupinx.

**Comment by DrDrij** [comment]
@mmcky No way to reliably do it with the HTML that is generated.

So a footnote reference such as `<sup>[2](#f2)</sup>`

Should be rendered as `<sup><a href="#f2">[2]</a></sup>`

**Comment by mmcky** [comment]
this should be fixed by: https://github.com/QuantEcon/sphinxcontrib-jupyter/pull/119

**Comment by mmcky** [comment]
@fkazemian would you be able to check the footnotes fix? It should now be live on compare.

**Comment by fkazemian** [comment]
Hi @mmcky sure

**Comment by fkazemian** [comment]
in the lecture they are fine:
![screenshot from 2018-10-03 08-58-02](https://user-images.githubusercontent.com/20714542/46381813-30044300-c6eb-11e8-86e7-854276799fec.png)

but we can't have access to the related text by footnotes: 
![screenshot from 2018-10-03 08-58-13](https://user-images.githubusercontent.com/20714542/46381827-3db9c880-c6eb-11e8-85d3-97575fbc7988.png)

(amss)

**Comment by mmcky** [comment]
@jstac do you want click back capability from a footnote to the referenced location in the text?
@fkazemian can you let me know what the ``html`` is for the click backs?

**Comment by DrDrij** [comment]
@mmcky Here's my suggestion:

**Current inline footnote link:**
`<p>That would let us reduce the beginning-of-period indebtedness for some other history <sup><a href="#fn-b">[2]</a></sup></p>`

**Current footnote:**
`<p><a id="fn-b"></a><strong>[2]</strong> From the first-order conditions for the Ramsey problem, there exists another realization s̃ t with the same history up until the previous period, i.e., s̃ t−1=st−1, but where the multiplier on constraint (11) takes a positive value, so γt(s̃ t)>0.</p>`

**Proposed inline footnote link:**
`<p>That would let us reduce the beginning-of-period indebtedness for some other history <sup><a href="#fn-b" id="fn-b-link">[2]</a></sup></p>`

**Proposed footnote:**
`<p><a id="fn-b" href="#fn-b-link"><strong>[2]</strong></a> From the first-order conditions for the Ramsey problem, there exists another realization s̃ t with the same history up until the previous period, i.e., s̃ t−1=st−1, but where the multiplier on constraint (11) takes a positive value, so γt(s̃ t)>0.</p>`

**Comment by fkazemian** [comment]
Hi 

It's ```

<p><a id="pm"></a>
<em>[1]</em> ........
```
I add` [1]` inside `<a>` tags: 
![screenshot from 2018-10-04 11-36-42](https://user-images.githubusercontent.com/20714542/46448412-0a01a000-c7ca-11e8-8f46-aa55dd4d49c7.png)

I think If we delete `<em>[1]</em>` and add` [1] `inside `<a>` tags it should be fine.

**Comment by mmcky** [comment]
thanks @DrDrij and @fkazemian. This issue should now by fixed by: https://github.com/QuantEcon/sphinxcontrib-jupyter/pull/126. Rerunning compiler now and will upload to compare-lectures shortly.

**Comment by mmcky** [comment]
@fkazemian can you please check this now. Thanks.

**Comment by fkazemian** [comment]
Hi @mmcky , sure

**Comment by fkazemian** [comment]
@mmcky , Thanks it just works fine, in compare with the live version,  index in footnotes are bold and you use tag <strong> for them, It which is not an issue, I change the label to fixed. 

![screenshot from 2018-10-05 11-46-13](https://user-images.githubusercontent.com/20714542/46511902-b0b27300-c894-11e8-8e7c-280090408be9.png)

**Comment by mmcky** [comment]
thanks @fkazemian this is great. I will close the issue. 
@jstac are you happy with the bold footnote numbers here?
