### ISSUE TITLE
Some images are right shifted instead of centre in the lectures 

### ISSUE THREAD

**Issue by AnjuJoon** [QuantEcon/lecture-source-py#252]

**Comment by jstac** [comment]
@AakashGfude Please consult with @AnjuJoon regarding this issue when you have a moment.

(Or @DrDrij if you have time.  @AnjuJoon will need to explain.)

**Comment by AnjuJoon** [comment]
@DrDrij the images in lectures in main website appears to be more inclined towards right. Can we have them exactly at centre of the page?
