### ISSUE TITLE
 Support for '.. code-block:: none'  is incomplete in Jupinx

### ISSUE THREAD

**Issue by fkazemian** [QuantEcon/lecture-source-py#26]
'.. code-block:: none' is used in these files:
```
./rst_files/python_advanced_features.rst:.. code-block:: none
./rst_files/python_advanced_features.rst:.. code-block:: none
./rst_files/python_advanced_features.rst:.. code-block:: none
./rst_files/python_advanced_features.rst:.. code-block:: none
./rst_files/python_advanced_features.rst:.. code-block:: none
./rst_files/python_advanced_features.rst:.. code-block:: none
./rst_files/python_advanced_features.rst:.. code-block:: none
./rst_files/python_advanced_features.rst:.. code-block:: none
./rst_files/python_advanced_features.rst:.. code-block:: none
./rst_files/python_advanced_features.rst:.. code-block:: none
./rst_files/python_advanced_features.rst:.. code-block:: none
./rst_files/python_advanced_features.rst:.. code-block:: none
./rst_files/python_advanced_features.rst:.. code-block:: none
./rst_files/python_advanced_features.rst:.. code-block:: none
./rst_files/python_advanced_features.rst:.. code-block:: none
./rst_files/python_advanced_features.rst:.. code-block:: none
./rst_files/python_advanced_features.rst:.. code-block:: none
./rst_files/python_advanced_features.rst:.. code-block:: none
./rst_files/python_advanced_features.rst:.. code-block:: none
./rst_files/python_advanced_features.rst:.. code-block:: none
./rst_files/python_advanced_features.rst:.. code-block:: none
./rst_files/python_advanced_features.rst:.. code-block:: none
./rst_files/python_advanced_features.rst:.. code-block:: none
./rst_files/schelling.rst:.. code-block:: none
./rst_files/schelling.rst:.. code-block:: none
./rst_files/python_essentials.rst:.. code-block:: none
./rst_files/python_essentials.rst:.. code-block:: none
./rst_files/python_essentials.rst:.. code-block:: none
./rst_files/pandas.rst:.. code-block:: none
./rst_files/pandas.rst:.. code-block:: none
./rst_files/debugging.rst:.. code-block:: none
./rst_files/debugging.rst:.. code-block:: none
./rst_files/debugging.rst:.. code-block:: none
./rst_files/finite_markov.rst:.. code-block:: none
./rst_files/python_by_example.rst:.. code-block:: none
./rst_files/oop_intro.rst:.. code-block:: none

```
I checked them randomly and realised it's incomplete in Jupinx, For example: finite_markov:
![screenshot from 2018-09-07 11-19-37](https://user-images.githubusercontent.com/20714542/45193793-4e655300-b293-11e8-88f2-f644f62fee82.png)
```
.. code-block:: none

    d -> h;
```

**Comment by mmcky** [comment]
We have used this in our `html` writer to tag `Out` blocks. This shouldn't be required in the new build process as output blocks will be generated. 

@natashawatkins can you confirm - are many of these cases `output` blocks?

**Comment by mmcky** [comment]
- [ ] check replacement output blocks exist when we compile the lectures (with execution)

**Comment by natashawatkins** [comment]
Sorry what is the question? These were cases where the output was meant to be an error generated, so we use code blocks that don't execute and manually put in the output as before.

**Comment by natashawatkins** [comment]
I might check a couple of them however

**Comment by natashawatkins** [comment]
@mmcky Just checked and they all seem valid - most are either errors generated, psuedocode, or showing the contents of a raw file

**Comment by mmcky** [comment]
@natashawatkins we now have the capability to use a``.. jupyter`` directive in the extension. So I think for preformated output it would be most clear to use:

```rst
.. jupyter::
   :out-cell:

```

or 

```rst
.. jupyter::
   :cell-type: out
```

rather than hijacking `none`. I can work on this support today.

**Comment by mmcky** [comment]
I think I will use:

```rst
.. jupyter:: 
   :type: output
```
for now I will assume this follows from the last ``code-block`` immediately above it.

**Comment by mmcky** [comment]
status of this ability can be tracked https://github.com/QuantEcon/sphinxcontrib-jupyter/pull/115

**Comment by mmcky** [comment]
As this approach may take some time -- I will look at implementing code block ``none`` and see if we can passthrough the class to the html.

**Comment by mmcky** [comment]
- [ ] @mmcky too first check if we can continue execution to generate error output

**Comment by mmcky** [comment]
Continued execution of notebook has been added to the builder. This means the Traceback output can be generated (assuming the logic in the notebook doesn't require a reset kernel). 

- [ ] remove relevant ``.. code-block:: none`` with output 
- [ ] remove ``:no-execute:`` tags in RST for cells that produce an error

**Comment by mmcky** [comment]
@fkazemian as per above comments can you look through the lectures for ``.. code-block:: none`` and ``:no-execute:`` flags on code-blocks to remove error output (it can now be generated without blocking the rest of the notebooks execution. Please open a single PR per lecture (to minimise the potential for collisions and ease of resolving conflicts). PR #70 is not complete as the ``.. code-block:: none`` output has not been removed, but I have removed the ``:no-execute:`` items. You will need to be careful as there may be some ``.. code-block::none `` items that are demonstration code  but if that is the case it would be good to document as we will remove the use of ``none`` as a highlighter. (https://github.com/mmcky/quantecon.build.lectures/pull/12). 

@natashawatkins can you then please audit the PRs as a double check.

**Comment by fkazemian** [comment]
- [ ] ./rst_files/python_advanced_features.rst:.. code-block:: none
- [ ] ./rst_files/python_advanced_features.rst:.. code-block:: none
- [ ] ./rst_files/python_advanced_features.rst:.. code-block:: none
- [ ] ./rst_files/python_advanced_features.rst:.. code-block:: none
- [ ] ./rst_files/python_advanced_features.rst:.. code-block:: none
- [ ] ./rst_files/python_advanced_features.rst:.. code-block:: none
- [ ] ./rst_files/python_advanced_features.rst:.. code-block:: none
- [ ] ./rst_files/python_advanced_features.rst:.. code-block:: none
- [ ] ./rst_files/python_advanced_features.rst:.. code-block:: none
- [ ] ./rst_files/python_advanced_features.rst:.. code-block:: none
- [ ] ./rst_files/python_advanced_features.rst:.. code-block:: none
- [ ] ./rst_files/python_advanced_features.rst:.. code-block:: none
- [ ] ./rst_files/python_advanced_features.rst:.. code-block:: none
- [ ] ./rst_files/python_advanced_features.rst:.. code-block:: none
- [ ] ./rst_files/python_advanced_features.rst:.. code-block:: none
- [ ] ./rst_files/python_advanced_features.rst:.. code-block:: none
- [ ] ./rst_files/python_advanced_features.rst:.. code-block:: none
- [ ] ./rst_files/python_advanced_features.rst:.. code-block:: none
- [ ] ./rst_files/python_advanced_features.rst:.. code-block:: none
- [ ] ./rst_files/python_advanced_features.rst:.. code-block:: none
- [ ] ./rst_files/python_advanced_features.rst:.. code-block:: none
- [ ] ./rst_files/python_advanced_features.rst:.. code-block:: none
- [ ] ./rst_files/python_advanced_features.rst:.. code-block:: none
- [ ] ./rst_files/schelling.rst:.. code-block:: none
- [ ] ./rst_files/schelling.rst:.. code-block:: none
- [ ] ./rst_files/python_essentials.rst:.. code-block:: none
- [ ] ./rst_files/python_essentials.rst:.. code-block:: none
- [ ] ./rst_files/python_essentials.rst:.. code-block:: none
- [ ] ./rst_files/pandas.rst:.. code-block:: none
- [ ] ./rst_files/pandas.rst:.. code-block:: none
- [ ] ./rst_files/debugging.rst:.. code-block:: none
- [ ] ./rst_files/debugging.rst:.. code-block:: none
- [ ] ./rst_files/debugging.rst:.. code-block:: none
- [ ] ./rst_files/finite_markov.rst:.. code-block:: none
- [ ] ./rst_files/python_by_example.rst:.. code-block:: none
- [ ] ./rst_files/oop_intro.rst:.. code-block:: none

**Comment by fkazemian** [comment]
I leave some` .. code-block:: none` unchanged in those lectures which I mentioned them by a pic.

**Comment by mmcky** [comment]
I think this issue can now be closed as we have changed a lot of these cases using `:class: no-execute` etc. Any further issues will need to be identified in next review round.
