### ISSUE TITLE
In the lecture "Cass-Koopmans  Optimal Growth Model" corresponding rst file "cass_coopmans.rst"  the link - "karush-kuhn-tucker conditions" is not working 

### ISSUE THREAD

**Issue by AnjuJoon** [QuantEcon/lecture-source-py#265]

**Comment by AnjuJoon** [comment]
@mmcky @AakashGfude In the lecture, the link

```
See `Karush-Kuhn-Tucker conditions <https://en.wikipedia.org/wiki/Karush-Kuhn-Tucker_conditions>`__
```

https://lectures.quantecon.org/py/en.wikipedia.org/wiki/Karush-Kuhn-Tucker_conditions

Obviously this is an error.  I'm not sure why it's happening.

**Comment by AakashGfude** [comment]
Hi @AnjuJoon @jstac . This issue does not seem to be occurring in the current master branch.
Notice the html and the corresponding link in the screenshot below.

![image](https://user-images.githubusercontent.com/6542997/60476287-642e8380-9cbe-11e9-93d0-0fdba9083629.png)

**Comment by AnjuJoon** [comment]
Thanks @AakashGfude
