### ISSUE TITLE
Various Errors and warnings for outputs (Code Issues, Missing Files, CellMagics)

### ISSUE THREAD

**Issue by fkazemian** [QuantEcon/lecture-source-py#28]
(finite_markov)

![screenshot from 2018-09-07 11-20-10](https://user-images.githubusercontent.com/20714542/45194121-03e4d600-b295-11e8-99e6-ab7ee4e82bfc.png)

also the address is:
`The data for this graph is in the ``web_graph_data.txt`` file --- you can also view it `here <https://github.com/QuantEcon/QuantEcon.lectures.code/blob/master/finite_markov/web_graph_data.txt>`__
`

which I checked and realised the text file is in this adresse as well:
```
https://github.com/QuantEcon/lecture-source-py/tree/master/rst_files/_static/code/finite_markov/web_graph_data.txt
```
shall we change it in finite_markov.rst?

~~- [ ] https://github.com/QuantEcon/sphinxcontrib-jupyter/issues/107~~
~~- [x] fixed by https://github.com/QuantEcon/sphinxcontrib-jupyter/pull/110~~
passthrough to the notebook as an executable cell is fixed but ``nbconvert`` is not running the cells properly that contain cell magics
https://github.com/ipython/ipython/issues/3707/

**Comment by fkazemian** [comment]
(mle)
![screenshot from 2018-09-11 10-26-17](https://user-images.githubusercontent.com/20714542/45340889-bf7e7080-b5db-11e8-82ca-41ef753c8089.png)
![screenshot from 2018-09-11 10-25-59](https://user-images.githubusercontent.com/20714542/45340890-bf7e7080-b5db-11e8-89aa-8b5098c6e8b2.png)
![screenshot from 2018-09-11 10-25-45](https://user-images.githubusercontent.com/20714542/45340891-bf7e7080-b5db-11e8-9cb7-957bae84eef0.png)

**Comment by fkazemian** [comment]
odu
![screenshot from 2018-09-11 16-40-33](https://user-images.githubusercontent.com/20714542/45342579-bdb7ab80-b5e1-11e8-87e5-f98558d06afd.png)

![screenshot from 2018-09-11 16-40-13](https://user-images.githubusercontent.com/20714542/45342580-bdb7ab80-b5e1-11e8-8e07-885431d03cc4.png)

![screenshot from 2018-09-11 16-39-26](https://user-images.githubusercontent.com/20714542/45342582-be504200-b5e1-11e8-9a76-fdbbc338f19e.png)

**Comment by fkazemian** [comment]
ols:
![screenshot from 2018-09-11 16-44-23](https://user-images.githubusercontent.com/20714542/45342826-7120a000-b5e2-11e8-9d67-35b26593a6c7.png)

**Comment by fkazemian** [comment]
opt_tax_recur:
![screenshot from 2018-09-11 16-59-05](https://user-images.githubusercontent.com/20714542/45343545-90b8c800-b5e4-11e8-8c43-27613edc1354.png)

**Comment by fkazemian** [comment]
pandas:
![screenshot from 2018-09-12 09-58-34](https://user-images.githubusercontent.com/20714542/45394291-39156d80-b673-11e8-8b96-288dede75aaa.png)

**Comment by fkazemian** [comment]
in python_advanced_features we have some output which is too much in generated version so that they are edited in the live version, shall we edit them as well or it's alright?
![screenshot from 2018-09-12 10-52-01](https://user-images.githubusercontent.com/20714542/45396190-551e0c80-b67d-11e8-84bb-8bcfb4f16d9f.png)

**Comment by fkazemian** [comment]
python_essentials
![screenshot from 2018-09-12 11-47-23](https://user-images.githubusercontent.com/20714542/45397211-5aca2100-b682-11e8-97b9-33fdc8509ac0.png)

**Comment by fkazemian** [comment]
robustness
![screenshot from 2018-09-12 13-01-39](https://user-images.githubusercontent.com/20714542/45399894-43446580-b68d-11e8-8640-bf4fe82fce81.png)

**Comment by fkazemian** [comment]
sci_libs
![screenshot from 2018-09-12 13-35-20](https://user-images.githubusercontent.com/20714542/45400797-fe223280-b690-11e8-8298-b0a45b551ad9.png)

**Comment by mmcky** [comment]
thanks @fkazemian this is becuase I haven't handled `_static` assets well yet.

**Comment by mmcky** [comment]
It looks like `robustness` and `mle` are now fixed.
