### ISSUE TITLE
beta: discount factor vs. discount rate

### ISSUE THREAD

**Issue by oyamad** [QuantEcon/lecture-source-py#281]
`beta` is in many cases referred (correctly) to as "discount factor", but sometimes referred to as "discount rate". The usage should be consistent.

**Comment by jstac** [comment]
Thanks @oyamad, indeed `beta` should be the discount factor.

@AnjuJoon , could you please change any instance of "discount rate" to "discount factor" in this lecture?

**Comment by AnjuJoon** [comment]
@jstac I will make the required changes
