### ISSUE TITLE
mccall_model_with_separation.rst: "Don't compare boolean values to True or False using =="

### ISSUE THREAD

**Issue by oyamad** [QuantEcon/lecture-source-py#282]
`if return_values == False:` should be `if not return_values:`.

See https://www.python.org/dev/peps/pep-0008/

**Comment by jstac** [comment]
Thanks @oyamad .

@AnjuJoon Could you please make this change?

**Comment by AnjuJoon** [comment]
@jstac, yeah I will fix this.
