### ISSUE TITLE
 Support for creating tables with pipes, hyphens and... is not complete in HTML output

### ISSUE THREAD

**Issue by fkazemian** [QuantEcon/lecture-source-py#30]
![screenshot from 2018-09-07 12-34-56](https://user-images.githubusercontent.com/20714542/45195667-157dac00-b29c-11e8-801e-c10fb0084a83.png)

```
+-----------------------+------+------+
|      :math:`s_t`      |  0   |  1   |
+=======================+======+======+
| :math:`p_a`           | 1.33 | 1.22 |
+-----------------------+------+------+
| :math:`p_b`           | 1.45 | 1.91 |
+-----------------------+------+------+
| :math:`p_o`           | 1.85 | 2.08 |
+-----------------------+------+------+
| :math:`p_p`           |    1 |    1 |
+-----------------------+------+------+
| :math:`\hat{p}_a`     | 1.85 | 1.69 |
+-----------------------+------+------+
| :math:`\hat{p}_b`     | 1.69 | 2.08 |
+-----------------------+------+------+


```
![screenshot from 2018-09-07 12-37-22](https://user-images.githubusercontent.com/20714542/45195669-16aed900-b29c-11e8-813d-17fc88a7645d.png)
```

+-----------------------+------+------+
|      :math:`s_t`      |  0   |  1   |
+=======================+======+======+
| :math:`p_a`           | 1.33 | 1.22 |
+-----------------------+------+------+
| :math:`p_b`           | 1.45 | 1.91 |
+-----------------------+------+------+
| :math:`p_o`           | 1.85 | 2.08 |
+-----------------------+------+------+
| :math:`p_p`           |    1 |    1 |
+-----------------------+------+------+
| :math:`\hat{p}_a`     | 1.85 | 1.69 |
+-----------------------+------+------+
| :math:`\hat{p}_b`     | 1.69 | 2.08 |
+-----------------------+------+------+
```

**Comment by mmcky** [comment]
@fkazemian do you remember what lecture this is from?

**Comment by fkazemian** [comment]
it's in harrison_kreps.rst, but I think I saw at least one more table like this.

**Comment by mmcky** [comment]
Looking at ``harrison_kreps`` it looks like the table is in fact properly built in markdown
![image](https://user-images.githubusercontent.com/8263752/45662743-6c11a280-bb46-11e8-95c9-9c595ad5b67b.png)
This appears to be an issue with ``nbconvert``

**Comment by mmcky** [comment]
@DrDrij the above table that doesn't seem to be converting properly during the `nbconvert` is encoded in html as:

```html
<h3 id="Summary-Table">Summary Table<a class="anchor-link" href="#Summary-Table">&#182;</a></h3><p>The following table gives a summary of the findings obtained in the remainder of the lecture
(you will be asked to recreate the table in an exercise)</p>
<p>It records implications of Harrison and Kreps’s specifications of $ P_a, P_b, \beta $</p>
<table>
<thead><tr>
<th style="text-align:center">$ s_t $</th>
<th style="text-align:center">0</th>
<th style="text-align:center">1</th>
</tr>
</thead>
<tbody>
<tr>
<td style="text-align:center">$ p_a $</td>
<td style="text-align:center">1.33</td>
<td style="text-align:center">1.22</td>
</tr>
<tr>
<td style="text-align:center">$ p_b $</td>
<td style="text-align:center">1.45</td>
<td style="text-align:center">1.91</td>
</tr>
<tr>
<td style="text-align:center">$ p_o $</td>
<td style="text-align:center">1.85</td>
<td style="text-align:center">2.08</td>
</tr>
<tr>
<td style="text-align:center">$ p_p $</td>
<td style="text-align:center">1</td>
<td style="text-align:center">1</td>
</tr>
<tr>
<td style="text-align:center">$ \hat{p}_a $</td>
<td style="text-align:center">1.85</td>
<td style="text-align:center">1.69</td>
</tr>
<tr>
<td style="text-align:center">$ \hat{p}_b $</td>
<td style="text-align:center">1.69</td>
<td style="text-align:center">2.08</td>
</tr>
</tbody>
</table>
```

**Comment by mmcky** [comment]
@mmcky look at adding a tag / metadata for tables. ``<table border=“1” class=“docutils”>`` should render with the old css we have

**Comment by mmcky** [comment]
ok -- so the problem here is that we build `markdown` tables not `html` tables so `nbconvert` is building the table in `html` for us. @DrDrij would it be useful if I injected an `html` comment before the table that could be used to change the class?

**Comment by mmcky** [comment]
ultimately we will probably need to write an html table (as an option) to pass through the class information. This is a big task so will try and think of a short term solution. 

These are the methods we use to build the markdown

```python
def visit_table(self, node):
        self.table_builder = dict()
        self.table_builder['column_widths'] = []
        self.table_builder['lines'] = []
        self.table_builder['line_pending'] = ""

        if 'align' in node:
            self.table_builder['align'] = node['align']
        else:
            self.table_builder['align'] = "center"

    def depart_table(self, node):
        table_lines = "".join(self.table_builder['lines'])
        self.markdown_lines.append(table_lines)
        self.table_builder = None

    def visit_thead(self, node):
        """ Table Header """
        self.table_builder['current_line'] = 0

    def depart_thead(self, node):
        """ create the header line which contains the alignment for each column """
        header_line = "|"
        for col_width in self.table_builder['column_widths']:
            header_line += self.generate_alignment_line(
                col_width, self.table_builder['align'])
            header_line += "|"

        self.table_builder['lines'].append(header_line + "\n")

    def generate_alignment_line(self, line_length, alignment):
        left = ":" if alignment != "right" else "-"
        right = ":" if alignment != "left" else "-"
        return left + "-" * (line_length - 2) + right

    def visit_colspec(self, node):
        self.table_builder['column_widths'].append(node['colwidth'])

    def visit_row(self, node):
        self.table_builder['line_pending'] = "|"

    def depart_row(self, node):
        finished_line = self.table_builder['line_pending'] + "\n"
        self.table_builder['lines'].append(finished_line)

    def visit_entry(self, node):
        pass

    def depart_entry(self, node):
        self.table_builder['line_pending'] += "|"
```

**Comment by mmcky** [comment]
https://github.com/QuantEcon/sphinxcontrib-jupyter/issues/54

**Comment by mmcky** [comment]
for the example above the html should be

```html
<table border="1" class="docutils">
<colgroup>
<col width="66%" />
<col width="17%" />
<col width="17%" />
</colgroup>
<thead valign="bottom">
<tr class="row-odd"><th class="head"><span class="math">\(s_t\)</span></th>
<th class="head">0</th>
<th class="head">1</th>
</tr>
</thead>
<tbody valign="top">
<tr class="row-even"><td><span class="math">\(p_a\)</span></td>
<td>1.33</td>
<td>1.22</td>
</tr>
<tr class="row-odd"><td><span class="math">\(p_b\)</span></td>
<td>1.45</td>
<td>1.91</td>
</tr>
<tr class="row-even"><td><span class="math">\(p_o\)</span></td>
<td>1.85</td>
<td>2.08</td>
</tr>
<tr class="row-odd"><td><span class="math">\(p_p\)</span></td>
<td>1</td>
<td>1</td>
</tr>
<tr class="row-even"><td><span class="math">\(\hat{p}_a\)</span></td>
<td>1.85</td>
<td>1.69</td>
</tr>
<tr class="row-odd"><td><span class="math">\(\hat{p}_b\)</span></td>
<td>1.69</td>
<td>2.08</td>
</tr>
</tbody>
</table>
```

**Comment by DrDrij** [comment]
One temporary possibility is if possible to append a element. eg. `<div class="content-table"></div>...<table>`

I can then hook onto the the table using `.content-table + table {...}`

This CSS selector looks for the next sibling element in the HTML.

**Comment by mmcky** [comment]
thanks @DrDrij I think that will be best way to go in the short term.

**Comment by fkazemian** [comment]
Thanks @mmcky , I can go through lectures and document lectures which have table and add this tag.

**Comment by fkazemian** [comment]
- [ ] - py_source/about_py.rst
- [ ] - py_source/additive_functionals.rst
- [ ] - py_source/aiyagari.rst
- [ ] - py_source/amss.rst
- [ ] - py_source/amss2.rst
- [ ] - py_source/amss3.rst
- [ ] - py_source/arellano.rst
- [ ] - py_source/arma.rst
- [ ] - py_source/calvo.rst
- [ ] - py_source/career.rst
- [ ] - py_source/chang_credible.rst
- [ ] - py_source/chang_ramsey.rst
- [ ] - py_source/classical_filtering.rst
- [ ] - py_source/coleman_policy_iter.rst
- [ ] - py_source/debugging.rst
- [ ] - py_source/discrete_dp.rst
- [ ] - py_source/dyn_stack.rst
- [ ] - py_source/egm_policy_iter.rst
- [ ] - py_source/estspec.rst
- [ ] - py_source/finite_markov.rst
- [ ] - py_source/getting_started.rst
- [ ] - py_source/harrison_kreps.rst
- [ ] - py_source/hist_dep_policies.rst
- [ ] - py_source/ifp.rst
- [ ] - py_source/jv.rst
- [ ] - py_source/kalman.rst
- [ ] - py_source/lake_model.rst
- [ ] - py_source/linear_algebra.rst
- [ ] - py_source/linear_models.rst
- [ ] - py_source/lln_clt.rst
- [ ] - py_source/lqcontrol.rst
- [ ] - py_source/lqramsey.rst
- [ ] - py_source/lu_tricks.rst
- [ ] - py_source/lucas_model.rst
- [ ] - py_source/markov_asset.rst
- [ ] - py_source/markov_perf.rst
- [ ] - py_source/matplotlib.rst
- [ ] - py_source/matsuyama.rst
- [ ] - py_source/mccall_model.rst
- [ ] - py_source/mccall_model_with_separation.rst
- [ ] - py_source/mle.rst
- [ ] - py_source/multiplicative_functionals.rst
- [ ] - py_source/numba.rst
- [ ] - py_source/numpy.rst
- [ ] - py_source/odu.rst
- [ ] - py_source/ols.rst
- [ ] - py_source/oop_intro.rst
- [ ] - py_source/opt_tax_recur.rst
- [ ] - py_source/optgrowth.rst
- [ ] - py_source/orth_proj.rst
- [ ] - py_source/pandas.rst
- [ ] - py_source/pandas_panel.rst
- [ ] - py_source/perm_income.rst
- [ ] - py_source/perm_income_cons.rst
- [ ] - py_source/python_advanced_features.rst
- [ ] - py_source/python_by_example.rst
- [ ] - py_source/python_essentials.rst
- [ ] - py_source/python_oop.rst
- [ ] - py_source/rational_expectations.rst
- [ ] - py_source/rob_markov_perf.rst
- [ ] - py_source/robustness.rst
- [ ] - py_source/samuelson.rst
- [ ] - py_source/schelling.rst
- [ ] - py_source/sci_libs.rst
- [ ] - py_source/scipy.rst
- [ ] - py_source/short_path.rst
- [ ] - py_source/smoothing.rst
- [ ] - py_source/stationary_densities.rst
- [ ] - py_source/uncertainty_traps.rst
- [ ] - py_source/wald_friedman.rst
- [ ] - py_source/writing_good_code.rst

**Comment by fkazemian** [comment]
harrison_kreps
![screenshot from 2018-09-24 11-17-43](https://user-images.githubusercontent.com/20714542/45935146-943c4e00-bfeb-11e8-9ef7-6a6c8d838ebb.png)
![screenshot from 2018-09-24 11-17-21](https://user-images.githubusercontent.com/20714542/45935147-943c4e00-bfeb-11e8-89fd-ccde2e850af3.png)

**Comment by fkazemian** [comment]
mle
(table as output)
![screenshot from 2018-09-24 11-52-16](https://user-images.githubusercontent.com/20714542/45935624-7b826700-bff0-11e8-87fd-f48a9be378be.png)

**Comment by fkazemian** [comment]
ols
 (table as output)
![screenshot from 2018-09-24 12-01-07](https://user-images.githubusercontent.com/20714542/45935732-b1741b00-bff1-11e8-882f-5aa37c12efe5.png)

**Comment by fkazemian** [comment]
pandas
(table as output)
![screenshot from 2018-09-24 12-11-17](https://user-images.githubusercontent.com/20714542/45935853-19773100-bff3-11e8-95ad-a39f0e3f6b4c.png)
![screenshot from 2018-09-24 12-11-01](https://user-images.githubusercontent.com/20714542/45935854-1a0fc780-bff3-11e8-93aa-0fb607123cf6.png)

**Comment by fkazemian** [comment]
pandas_panel
 (table as output)
![screenshot from 2018-09-24 12-13-28](https://user-images.githubusercontent.com/20714542/45935895-88ed2080-bff3-11e8-847e-fb360d6ca6ca.png)

![screenshot from 2018-09-24 12-13-20](https://user-images.githubusercontent.com/20714542/45935896-88ed2080-bff3-11e8-87fe-813322ea0377.png)

![screenshot from 2018-09-24 12-13-42](https://user-images.githubusercontent.com/20714542/45935901-8db1d480-bff3-11e8-8f23-ee946a14f14c.png)
and so on.

**Comment by fkazemian** [comment]
Hi @mmcky 

you mean I have to change 

```
   +-----------------------+------+------+
   |      :math:`s_t`      |  0   |  1   |
   +=======================+======+======+
   | :math:`p_a`           | 1.33 | 1.22 |
   +-----------------------+------+------+
   | :math:`p_b`           | 1.45 | 1.91 |
   +-----------------------+------+------+
   | :math:`p_o`           | 1.85 | 2.08 |
   +-----------------------+------+------+
   | :math:`p_p`           |    1 |    1 |
   +-----------------------+------+------+
   | :math:`\hat{p}_a`     | 1.85 | 1.69 |
   +-----------------------+------+------+
   | :math:`\hat{p}_b`     | 1.69 | 2.08 |
   +-----------------------+------+------+

```

to 
```
.. only:: html

   <div class="content-table">
   <style>
   table {
       border-collapse: collapse;
   }

   th, td {
       text-align: center;
       border-bottom: 1px solid #ddd;
   }
   </style>
   <table>
     <tr>
       <th> :math:`s_t` </th>
       <th>0</th>
       <th>1</th>
     </tr>
     <tr>
       <td> :math:`p_a` </td>
       <td>1.33</td>
       <td>1.22</td>
     </tr>
     <tr>
       <td> :math:`p_b` </td>
       <td>1.45</td>
       <td>1.91</td>
     </tr>
     <tr>
       <td> :math:`p_o` </td>
       <td>1.85</td>
       <td>2.08</td>
     </tr>
     <tr>
       <td> :math:`p_p` </td>
       <td>1</td>
       <td>1</td>
     </tr>
     <tr>
       <td> :math:`\hat{p}_a` </td>
       <td>1.85</td>
       <td>1.69</td>
     </tr>
     <tr>
       <td> :math:`\hat{p}_b` </td>
       <td>1.69</td>
       <td>2.08</td>
     </tr>

   </table>
   </div>
```
? 
I try this,  but it's not working.

**Comment by DrDrij** [comment]
Hi @fkazemian the tables in pandas_panel appear to be PNG images in the live lectures. Is there a reason they can't be used on the new renderings?

**Comment by fkazemian** [comment]
Hi @DrDrij That's interesting because I never pay attention to that and I didn't know it's PNG file, in the generated version is not PNG and It's an output of for example this code:

```
realwage = realwage.pivot_table(values='value',
                                index='Time',
                                columns=['Country', 'Series', 'Pay period'])
realwage.head()
```

**Comment by mmcky** [comment]
@fkazemian what I mean is that we should only need to add the html I listed above just before each table so that the theme can identify certain tables to markup. You shouldn't need to touch the markdown just prepend the table (written in markdown that is translated to html) with the ``div`` above contained in an only html cell.

**Comment by mmcky** [comment]
@DrDrij the png images would have been from showing the static output. This is probably going to be a style issue with the new tables being generated in the `out` blocks and then converted to html using nbconvert

**Comment by fkazemian** [comment]
Hi @mmcky , @DrDrij 
I just checked it and It is not fixed:

![screenshot from 2018-10-03 16-00-20](https://user-images.githubusercontent.com/20714542/46392698-9443f880-c725-11e8-9fc5-2f29ddcc16de.png)

**Comment by mmcky** [comment]
@fkazemian does the output `html` contain the `<div class="content-table"></div>` line? It may not be fully implemented in the css yet.

**Comment by DrDrij** [comment]
@fkazemian Can you add the markup as suggested by Matt to your example table? I can then do my testing and write CSS. Once confirmed we could then go through and adjust every table.

lecture: harrison_kreps

**Comment by mmcky** [comment]
@DrDrij I have uploaded a ``harrison_kreps.html`` file on slack that has the additional ``only html`` block added to the ``rst`` file.

**Comment by DrDrij** [comment]
@mmcky Added the styles to your repo and compare subdomain. However - jupinx needs a small update - can you please switch out the curly quotes for standard quotes on the `<div class="content-table"></div>` markup? Currently the HTML there is invalid.

![image](https://user-images.githubusercontent.com/5886045/46533503-84efb700-c8ad-11e8-86b1-1dbb114689f7.png)

**Comment by mmcky** [comment]
thanks @DrDrij I have made some adjustments to ``jupinx`` and sent through ``harrison_kreps`` via slack on the solution suggested above.

**Comment by mmcky** [comment]
@DrDrij looks like the tables are now getting rendered correctly. Neat!

<img width="1853" alt="image" src="https://user-images.githubusercontent.com/8263752/46773501-755aed00-cd49-11e8-9870-1676a60fc83e.png">

@fkazemian can you look at the PR #87 as an example and add the raw directive (on a lecture-by-lecture basis) to other tables contained in the lectures?

**Comment by fkazemian** [comment]
Hi @mmcky in the other lectures as you can see above, tables are png images as an output in live version and they're an output. when I'm running them locally they're totally fine, but as html not. I think this rule is not practical for these kind of tables. we have to fix them or 

- [ ] 1. I can make a png table exactly like the live version and ignore output
- [ ] 2. I can make tables like the table in `harrison_kreps` and again ignore the output
am I right? what do you think?

**Comment by mmcky** [comment]
thanks @fkazemian would you mind posting an example?

If the table is generated by code then it should be generated when we execute the notebook and we can remove the png file. however if the png file is referenced within text then we will have to think about this a bit further.

**Comment by mmcky** [comment]
@fkazemian from looking at `pandas_panel` they are now rendered in the notebook (during execution) as output. 

![image](https://user-images.githubusercontent.com/8263752/48177961-7e9ca100-e36b-11e8-9c22-295ad2f3ab19.png)

therefore these tables may look different to the ones used on `live` as it will depend on `pandas` output settings etc. Is this what you mean by your comment above?

**Comment by fkazemian** [comment]
Hi @mmcky yes exactly, I thought I have to change them to make them more neat I didn't know it's depend on Pandas.

**Comment by mmcky** [comment]
I think this issue can now be closed. Thanks @fkazemian for your help during this review.
