### ISSUE TITLE
Issues in the lecture "A Problem that Stumped Milton Friedman"

### ISSUE THREAD

**Issue by Yuya-Furusawa** [QuantEcon/lecture-source-py#303]
1. Some packages that are not used are imported.

> from scipy.stats import beta
> import quantecon as qe

2. Typos in the explanation of Bellman Equation.

<img width="545" alt="BellmanEquation" src="https://user-images.githubusercontent.com/35675799/58421515-15903700-80cb-11e9-8cf0-ad59e0d3e056.png">

In the equation, minimum is taken in outside the integral, but we took it inside.
In addition, we have to replace **f_0(z')** with **f(z')**.

3. In the function `Q` in `operator_factory`, using parallel computing is hard-coded.

```
def operator_factory(wf, parallel_flag=True):

 ...

 @njit(parallel=True)
 def Q(h):
     h_new = np.empty_like(π_grid)
     h_func = lambda p: interp(π_grid, h, p)

 ...
```

However, if there is no intention in this hard coding, we should rewrite

```
 @njit(parallel=parallel_flag)
 def Q(h):
```

**Comment by jstac** [comment]
Thanks @Yuya-Furusawa !

All good points.  

@shizejin Would you mind to make those adjustments?  I prefer that parallelization is optional.

**Comment by shizejin** [comment]
Thanks @Yuya-Furusawa . 

Regarding the second point, since we believe z' follows fπ, I guess we should replace f0(z') with fπ(z') rather than f(z'). What do you think?

**Comment by Yuya-Furusawa** [comment]
@shizejin Exactly. fπ(z') is suitable because z follows fπ from the decision maker's point of view.
