### ISSUE TITLE
some internal references are failing -- missing link to previously existing output

### ISSUE THREAD

**Issue by fkazemian** [QuantEcon/lecture-source-py#32]
in (linear_algebra) some references to figures are failed.
![screenshot from 2018-09-10 09-58-45](https://user-images.githubusercontent.com/20714542/45270765-46e8b880-b4e4-11e8-88b5-1e2b2c998c96.png)

To see why, recall the :ref:`figure above <la_3dvec>`, where :math:`k=2` and :math:`n=3`

![screenshot from 2018-09-10 09-56-56](https://user-images.githubusercontent.com/20714542/45270767-4a7c3f80-b4e4-11e8-8942-431c31cf345b.png)

To illustrate the idea, recall :ref:`the figure <la_3dvec>` that showed the span of vectors :math:`\{a_1, a_2\}` in :math:`\mathbb R ^3` as a plane through the origin

**Comment by mmcky** [comment]
@fkazemian I think the issue here is there is no figure `la_3dvec` in that `rst` file anymore. Perhaps the figure was removed when output was removed (@natashawatkins was this figure an output figure?). This will be a difficult one to solve -- I think we need to include any figures that require labels in the `rst`.

**Comment by fkazemian** [comment]
Hi @mmcky  I checked, yes there is no figure `la_3dve`c  but there is figure `3dvec` which exactly same as `la_3dve`and it was the output figure.

**Comment by natashawatkins** [comment]
@mmcky Yeah I think there are a few issues with references now.

I noticed that code blocks from jinja could be used to add references... as in you could reference the code block name and `.. code-block-name` would be inserted. Is this a possible solution? Adding a block around the figure?

**Comment by mmcky** [comment]
@natashawatkins I don't follow what you're suggesting here. Can you provide an example.

**Comment by mmcky** [comment]
One solution to this problem would be to insert an internal ``RST`` link to where the figure is generated by the code. This can be done by adding:

```rst
.. _la_3dvec:

.. code-block::

   <code here>
```

**Comment by mmcky** [comment]
The above is the easiest fix for now. It would be good to support `:name:` attribute for ``code-block`` directives in ``jupinx``

**Comment by natashawatkins** [comment]
Yeah that is what I meant

**Comment by mmcky** [comment]
I think this has been implemented now. thanks @natashawatkins -- I will close this issue.
