### ISSUE TITLE
'.. note::' has conflict with other tags in Jupinx

### ISSUE THREAD

**Issue by fkazemian** [QuantEcon/lecture-source-py#33]
`.. note:: ` has conflict with other tags in Jupinx.
(linear_algebra):
![screenshot from 2018-09-10 10-00-56](https://user-images.githubusercontent.com/20714542/45270974-5963f180-b4e6-11e8-92a4-4240d86f579f.png)
![screenshot from 2018-09-10 09-57-32](https://user-images.githubusercontent.com/20714542/45270975-5b2db500-b4e6-11e8-94ab-603f1e0f7b10.png)
(perm_income):
![screenshot from 2018-09-10 10-35-31](https://user-images.githubusercontent.com/20714542/45270984-6d0f5800-b4e6-11e8-8902-698391ad88d5.png)
amss:
![screenshot from 2018-09-10 10-38-18](https://user-images.githubusercontent.com/20714542/45270991-81ebeb80-b4e6-11e8-8cb3-e0b50f9710e8.png)
linear_model:
![screenshot from 2018-09-10 10-39-15](https://user-images.githubusercontent.com/20714542/45270997-962fe880-b4e6-11e8-8402-217e95ec2091.png)
robustness:
![screenshot from 2018-09-10 10-40-22](https://user-images.githubusercontent.com/20714542/45271014-b5c71100-b4e6-11e8-8ffa-4cd7288f0717.png)

**Comment by mmcky** [comment]
thanks @fkazemian I think this one is now semi-fixed. 
I think the remaining issue is collision of math and words as per issue #12. Also some links won't resolve as they point to ``ipynb`` (as per #37)

**Comment by fkazemian** [comment]
Hi @mmcky I just checked them. It is fixed and I change the label.

**Comment by mmcky** [comment]
thanks @fkazemian
