### ISSUE TITLE
Jupinx has conflict with some litera-include

### ISSUE THREAD

**Issue by fkazemian** [QuantEcon/lecture-source-py#34]
multiplicative_functionals:
![screenshot from 2018-09-11 16-02-34](https://user-images.githubusercontent.com/20714542/45341330-99f26680-b5dd-11e8-8775-cdb0c4fc9a89.png)
![screenshot from 2018-09-11 16-02-00](https://user-images.githubusercontent.com/20714542/45341332-99f26680-b5dd-11e8-9b13-9a06dbec7fea.png)
` .. literalinclude:: /_static/code/multiplicative_functionals/amflss_scalar.py`
but I've already replaced literal-include with the actual code in a code-block::python3 in this PR:  #3 I think It should be fixed, so I add a check-fix label to this Issue.

**Comment by fkazemian** [comment]
rob_markov_perf
![screenshot from 2018-09-12 12-21-22](https://user-images.githubusercontent.com/20714542/45399257-b7c9d500-b68a-11e8-8937-c1ea3919208c.png)
![screenshot from 2018-09-12 12-21-05](https://user-images.githubusercontent.com/20714542/45399258-b8626b80-b68a-11e8-8cb5-47dfe558ae49.png)

**Comment by mmcky** [comment]
@fkazemian I haven't merged that PR yet -- and it looks like this issue is fixed? Can you re-check for me. Thanks.

**Comment by fkazemian** [comment]
Hi @mmcky yes I just checked and  it seems it's ok, so I change the label to fixed.

![screenshot from 2018-09-13 14-29-22](https://user-images.githubusercontent.com/20714542/45467185-a56e9a80-b761-11e8-8c9c-416c528d6ae7.png)

![screenshot from 2018-09-13 14-28-30](https://user-images.githubusercontent.com/20714542/45467186-a56e9a80-b761-11e8-9361-68ef14b8f608.png)

![screenshot from 2018-09-13 14-27-20](https://user-images.githubusercontent.com/20714542/45467187-a6073100-b761-11e8-96b8-a66f06496028.png)

**Comment by mmcky** [comment]
thanks @fkazemian
