### ISSUE TITLE
To suppress output of !pip install command while conversion to pdf 

### ISSUE THREAD

**Issue by AnjuJoon** [QuantEcon/lecture-source-py#399]
@AakashGfude  and @mmcky 
For example, the output of "! pip install polytope" in this lecture  
![Screenshot from 2019-06-11 19-41-44](https://user-images.githubusercontent.com/50222412/59261565-0ee3f100-8c81-11e9-890d-ffeda6242f4c.png)

**Comment by jstac** [comment]
Thanks for opening this @AnjuJoon.

It would be nice to have this fixed, although I would not be in favor of any solution that specializes to this particular problem.  

On the other hand, it would be nice to see a solution that prevents pdf output of all cells marked `hide-output`

**Comment by mmcky** [comment]
hi @AnjuJoon the executed notebooks from `sphinxcontrib-jupyter` should be sanitised in the `jupyter` folder if the `pip` cell is tagged to suppress output with `hide-output`. The output will be generated however if you re-run the notebook.

**Comment by jstac** [comment]
Hi @AnjuJoon , do you understand what @mmcky is saying?  Feel free to ask if not.

**Comment by AnjuJoon** [comment]
@mmcky thanks! this will solve this issue then.
