### ISSUE TITLE
Support for nested lists is incomplete in Jupinx

### ISSUE THREAD

**Issue by mmcky** [QuantEcon/lecture-source-py#4]
It looks like support for nested lists is incomplete in ``sphinxcontrib-jupyter``

![image](https://user-images.githubusercontent.com/8263752/44702308-2711c780-aad6-11e8-9c64-48d4ccb1b0c4.png)

this example is from ``py/getting_started.rst``

**Comment by mmcky** [comment]
this appears to be an issue with the source RST file as ``sphinxcontrib-jupyter`` does support nested lists. https://github.com/QuantEcon/sphinxcontrib-jupyter/pull/75. It looks like there are two many spaces where 4 spaces should be 2 spaces in the source RST

**Comment by fkazemian** [comment]
![1](https://user-images.githubusercontent.com/20714542/44962967-ff08e500-af69-11e8-81c4-523be1b0469b.png)

amss.html have the same problem. The numbers of items also are failed.

**Comment by fkazemian** [comment]
![1](https://user-images.githubusercontent.com/20714542/44967085-2f5c7d80-af82-11e8-9f82-0804a7d026e7.png)

![2](https://user-images.githubusercontent.com/20714542/44967089-33889b00-af82-11e8-86e4-ba0d0f7010b6.png)

![3](https://user-images.githubusercontent.com/20714542/44967092-36838b80-af82-11e8-8f26-3399a0ae3259.png)

![4](https://user-images.githubusercontent.com/20714542/44967097-3c796c80-af82-11e8-877e-b61b5239da6c.png)

![5](https://user-images.githubusercontent.com/20714542/44967101-3f745d00-af82-11e8-8fca-a7235cdac4a6.png)

![6](https://user-images.githubusercontent.com/20714542/44967103-426f4d80-af82-11e8-9339-9bc24e88e00d.png)

![7](https://user-images.githubusercontent.com/20714542/44967106-456a3e00-af82-11e8-9fac-306497856015.png)

amss3.html

**Comment by fkazemian** [comment]
(arellano) :
![1](https://user-images.githubusercontent.com/20714542/45006162-e0265380-b03a-11e8-98c4-f6c8a0b036b1.png)

![2](https://user-images.githubusercontent.com/20714542/45006163-e3214400-b03a-11e8-8a12-6d4ccdde018c.png)

![3](https://user-images.githubusercontent.com/20714542/45006167-e4eb0780-b03a-11e8-86b6-b353a4c2d7fd.png)

**Comment by fkazemian** [comment]
(calvo)

![screenshot from 2018-09-04 16-35-26](https://user-images.githubusercontent.com/20714542/45014317-74a3ac80-b061-11e8-9229-ef83d32c9fbb.png)

**Comment by fkazemian** [comment]
(career)
![screenshot from 2018-09-05 10-36-43](https://user-images.githubusercontent.com/20714542/45064810-335edb80-b0f9-11e8-9aa0-f60291af469a.png)

![screenshot from 2018-09-05 10-37-41](https://user-images.githubusercontent.com/20714542/45064812-35c13580-b0f9-11e8-92e1-7cc040f7f4a6.png)

**Comment by fkazemian** [comment]
(chang_credible)
![screenshot from 2018-09-05 10-53-53](https://user-images.githubusercontent.com/20714542/45065640-b124e600-b0fd-11e8-813e-616d95c16ae3.png)

**Comment by fkazemian** [comment]
(dyn_stack)
![screenshot from 2018-09-07 10-31-17](https://user-images.githubusercontent.com/20714542/45192465-ca5b9d00-b28b-11e8-80db-cf5ed70bf408.png)

![screenshot from 2018-09-07 10-31-33](https://user-images.githubusercontent.com/20714542/45192466-ccbdf700-b28b-11e8-92fe-0a5538aabbbc.png)

![screenshot from 2018-09-07 10-30-54](https://user-images.githubusercontent.com/20714542/45192468-ce87ba80-b28b-11e8-8310-c4a7d519f6f5.png)

**Comment by fkazemian** [comment]
(jv)
![screenshot from 2018-09-07 14-49-10](https://user-images.githubusercontent.com/20714542/45199144-89748000-b2ad-11e8-96ff-9125eba543cf.png)

**Comment by fkazemian** [comment]
(kalman)
![screenshot from 2018-09-07 14-55-29](https://user-images.githubusercontent.com/20714542/45199402-c7be6f00-b2ae-11e8-894c-725e4446908f.png)
![screenshot from 2018-09-07 14-55-41](https://user-images.githubusercontent.com/20714542/45199403-c8ef9c00-b2ae-11e8-8aee-be88b09d3618.png)
![screenshot from 2018-09-07 14-53-40](https://user-images.githubusercontent.com/20714542/45199404-ca20c900-b2ae-11e8-8238-882d11b813de.png)

**Comment by fkazemian** [comment]
(linear_models)
![screenshot from 2018-09-10 10-54-27](https://user-images.githubusercontent.com/20714542/45271247-f758bb80-b4e8-11e8-800b-a7bc04fd884b.png)

**Comment by fkazemian** [comment]
lqcontrol
![screenshot from 2018-09-10 11-51-09](https://user-images.githubusercontent.com/20714542/45272877-23793a00-b4f3-11e8-9c8d-31ee006c9ef3.png)

**Comment by fkazemian** [comment]
lqramsey:
![screenshot from 2018-09-10 15-44-02](https://user-images.githubusercontent.com/20714542/45278652-6f3adc00-b511-11e8-9c0d-286c436a2733.png)

**Comment by fkazemian** [comment]
(lu_tricks)
![screenshot from 2018-09-10 15-57-11](https://user-images.githubusercontent.com/20714542/45279106-4fa4b300-b513-11e8-80d8-4cfb7e6029e5.png)

**Comment by fkazemian** [comment]
(lucas_model)
![screenshot from 2018-09-10 16-07-25](https://user-images.githubusercontent.com/20714542/45279374-4d8f2400-b514-11e8-9936-e20ebb02f79d.png)

![screenshot from 2018-09-10 16-06-46](https://user-images.githubusercontent.com/20714542/45279377-4ff17e00-b514-11e8-8756-1134d717ceb1.png)

**Comment by fkazemian** [comment]
(markov_perf)
![screenshot from 2018-09-11 09-57-20](https://user-images.githubusercontent.com/20714542/45330666-d6a46a80-b5a9-11e8-9311-e8f9481ea0db.png)

**Comment by fkazemian** [comment]
(multiplicative_functionals)
![screenshot from 2018-09-11 16-04-48](https://user-images.githubusercontent.com/20714542/45341174-f99c4200-b5dc-11e8-852b-70b922d352bd.png)
![screenshot from 2018-09-11 16-04-08](https://user-images.githubusercontent.com/20714542/45341175-fa34d880-b5dc-11e8-897c-281dd3fbcde8.png)

**Comment by fkazemian** [comment]
opt_tax_recur:
![screenshot from 2018-09-11 16-58-34](https://user-images.githubusercontent.com/20714542/45343587-a4fcc500-b5e4-11e8-81f9-f7d8ede4e879.png)
![screenshot from 2018-09-11 16-58-02](https://user-images.githubusercontent.com/20714542/45343588-a4fcc500-b5e4-11e8-8600-a6b8e868c2e1.png)
![screenshot from 2018-09-11 16-52-06](https://user-images.githubusercontent.com/20714542/45343591-a5955b80-b5e4-11e8-9447-7ffc5bd9d070.png)

**Comment by fkazemian** [comment]
optgrowth:
![screenshot from 2018-09-11 17-09-47](https://user-images.githubusercontent.com/20714542/45344249-8dbed700-b5e6-11e8-8554-ba7161e8dc50.png)
![screenshot from 2018-09-11 17-09-34](https://user-images.githubusercontent.com/20714542/45344250-8dbed700-b5e6-11e8-8437-2148bc47856a.png)

**Comment by fkazemian** [comment]
pandas:
![screenshot from 2018-09-12 09-55-57](https://user-images.githubusercontent.com/20714542/45394229-fb184980-b672-11e8-8f76-a61c7502458e.png)

**Comment by fkazemian** [comment]
perm_income
![screenshot from 2018-09-12 10-34-53](https://user-images.githubusercontent.com/20714542/45395133-f2764200-b677-11e8-8960-f9171b4ba91b.png)

**Comment by fkazemian** [comment]
perm_income_cons
![screenshot from 2018-09-12 10-43-44](https://user-images.githubusercontent.com/20714542/45395351-15edbc80-b679-11e8-8726-7dbc7fcc7c6b.png)

**Comment by fkazemian** [comment]
python_advanced_features
![screenshot from 2018-09-12 10-56-24](https://user-images.githubusercontent.com/20714542/45396117-fc4e7400-b67c-11e8-88d1-b393a5f407e1.png)
![screenshot from 2018-09-12 10-52-53](https://user-images.githubusercontent.com/20714542/45396119-fc4e7400-b67c-11e8-87d6-93ffe675b287.png)

**Comment by fkazemian** [comment]
python_by_example
![screenshot from 2018-09-12 11-20-57](https://user-images.githubusercontent.com/20714542/45396731-6ae10100-b680-11e8-9d90-ec3ff3a949ee.png)
![screenshot from 2018-09-12 11-20-01](https://user-images.githubusercontent.com/20714542/45396732-6b799780-b680-11e8-997a-321fb73946ef.png)
![screenshot from 2018-09-12 11-19-40](https://user-images.githubusercontent.com/20714542/45396733-6b799780-b680-11e8-894f-86abb12c0476.png)
![screenshot from 2018-09-12 11-19-20](https://user-images.githubusercontent.com/20714542/45396734-6c122e00-b680-11e8-902b-ef3e5d8081a8.png)

**Comment by fkazemian** [comment]
python_essentials
![screenshot from 2018-09-12 11-48-09](https://user-images.githubusercontent.com/20714542/45397186-3706db00-b682-11e8-961b-2eacbaf76f02.png)

**Comment by fkazemian** [comment]
python_oop
![screenshot from 2018-09-12 11-54-25](https://user-images.githubusercontent.com/20714542/45397400-2f940180-b683-11e8-8b38-7dcf6e1e9fb8.png)
![screenshot from 2018-09-12 11-53-57](https://user-images.githubusercontent.com/20714542/45397401-2f940180-b683-11e8-8e49-388aec9c1ad1.png)

**Comment by fkazemian** [comment]
rational_expectations
![screenshot from 2018-09-12 12-11-23](https://user-images.githubusercontent.com/20714542/45397857-34f24b80-b685-11e8-8d5c-2c3dee19f594.png)

**Comment by fkazemian** [comment]
rob_markov_perf:

![screenshot from 2018-09-12 12-21-53](https://user-images.githubusercontent.com/20714542/45399201-88b36380-b68a-11e8-8922-89962e953751.png)
![screenshot from 2018-09-12 12-21-40](https://user-images.githubusercontent.com/20714542/45399202-894bfa00-b68a-11e8-90b6-09bc7e7a328d.png)
![screenshot from 2018-09-12 12-20-24](https://user-images.githubusercontent.com/20714542/45399203-894bfa00-b68a-11e8-8751-5bdc19a6af01.png)
![screenshot from 2018-09-12 12-18-49](https://user-images.githubusercontent.com/20714542/45399205-89e49080-b68a-11e8-8cba-8a6849f192d9.png)
![screenshot from 2018-09-12 12-14-33](https://user-images.githubusercontent.com/20714542/45399206-89e49080-b68a-11e8-8a3f-0ca895d7a480.png)
![screenshot from 2018-09-12 12-14-10](https://user-images.githubusercontent.com/20714542/45399207-8a7d2700-b68a-11e8-9679-7adfdcaf01b8.png)

**Comment by fkazemian** [comment]
robustness:
![screenshot from 2018-09-12 13-01-01](https://user-images.githubusercontent.com/20714542/45399821-fbbdd980-b68c-11e8-85b5-027691b84fb5.png)
![screenshot from 2018-09-12 12-57-54](https://user-images.githubusercontent.com/20714542/45399822-fc567000-b68c-11e8-8166-a67f71c3acf9.png)
![screenshot from 2018-09-12 12-57-26](https://user-images.githubusercontent.com/20714542/45399823-fc567000-b68c-11e8-987c-755a5a1bd99f.png)
![screenshot from 2018-09-12 12-55-50](https://user-images.githubusercontent.com/20714542/45399824-fc567000-b68c-11e8-9e81-c5913c6f8c60.png)
![screenshot from 2018-09-12 12-55-31](https://user-images.githubusercontent.com/20714542/45399825-fcef0680-b68c-11e8-935d-dbe79960ec69.png)

**Comment by fkazemian** [comment]
scipy
![screenshot from 2018-09-12 13-47-52](https://user-images.githubusercontent.com/20714542/45401188-d764fb80-b692-11e8-93b3-cf35d6648b66.png)
![screenshot from 2018-09-12 13-47-33](https://user-images.githubusercontent.com/20714542/45401189-d764fb80-b692-11e8-80aa-4e7f117b40d8.png)

**Comment by fkazemian** [comment]
smoothing
![screenshot from 2018-09-12 14-00-48](https://user-images.githubusercontent.com/20714542/45401806-bc47bb00-b695-11e8-90ab-d6ab153c4fab.png)

**Comment by fkazemian** [comment]
stationary_densities
![screenshot from 2018-09-12 14-13-08](https://user-images.githubusercontent.com/20714542/45402322-6d4f5500-b698-11e8-88bb-8beb9d10e8bc.png)
![screenshot from 2018-09-12 14-12-15](https://user-images.githubusercontent.com/20714542/45402324-6de7eb80-b698-11e8-8532-2f8edae219ed.png)

**Comment by mmcky** [comment]
well formatted lists (as per RST specification) seem to render just fine. I will look at the ``html`` writer to see how they make it more robust to malformed input.

IF I fix the `getting_started.rst` source file it looks like

![image](https://user-images.githubusercontent.com/8263752/45403324-1730e080-b69d-11e8-8adb-0943cdb719da.png)

**Comment by mmcky** [comment]
it looks like the extension was injecting an odd number of spaces into the markdown when generating sublists which broke the rendering in markdown. This PR hopefully addresses this issue:

https://github.com/QuantEcon/sphinxcontrib-jupyter/pull/93

- [ ] update ``compare-lectures.quantecon.org``
- [ ] @fkazemian to check if fixed.

**Comment by mmcky** [comment]
@fkazemian I checked the first one but it would be great if you could do a comprehensive check for me. Thanks.

**Comment by fkazemian** [comment]
Hi @mmcky 
some of them are fixed but some of them not, such as (dyn_stack.rst): 
it was
![45192466-ccbdf700-b28b-11e8-92fe-0a5538aabbbc](https://user-images.githubusercontent.com/20714542/45408146-d80b8b00-b6ae-11e8-8393-37aa580567e7.png)
but now it's 
![screenshot from 2018-09-12 17-09-34](https://user-images.githubusercontent.com/20714542/45408152-dcd03f00-b6ae-11e8-8e21-08564987f224.png)

**Comment by mmcky** [comment]
thanks @fkazemian

**Comment by mmcky** [comment]
@fkazemian I think the `dyn_stack.rst` is as a result of malformed input. We can fix this by removing the initial white space at the front of the list items. Would you mind submitting a PR and reference this issue?

```rst
That choice implies that

    * :math:`i_1=0.25`, and

    * :math:`z_1 = \begin{bmatrix} 1 &  v_1 & Q_1 & \overline {q}_1 \end{bmatrix}  =  \begin{bmatrix} 1 & 0 & 21.83 & 47.43 \end{bmatrix}`

```

should be 

```rst
That choice implies that

* :math:`i_1=0.25`, and

* :math:`z_1 = \begin{bmatrix} 1 &  v_1 & Q_1 & \overline {q}_1 \end{bmatrix}  =  \begin{bmatrix} 1 & 0 & 21.83 & 47.43 \end{bmatrix}`
```

**Comment by fkazemian** [comment]
Hi @mmcky, thanks I just submit a PR "fix malformed inputs #38 "

**Comment by mmcky** [comment]
I have just pushed a PR that will make the lists more robust to this spacing issue in the source RST. Before I merge the PR to fix the source:

- [ ] see if these are still an issue in the comparison.

**Comment by mmcky** [comment]
@fkazemian would you mind checking if these are still an issue for me. There was adjustments made to made spacing more robust.

**Comment by fkazemian** [comment]
Hi @mmcky I checked some of them randomly and they were fine. Thanks I change the label to fixed.

**Comment by mmcky** [comment]
thanks @fkazemian.
