### ISSUE TITLE
No Margin for code blocks is a problem while converison to pdf

### ISSUE THREAD

**Issue by AnjuJoon** [QuantEcon/lecture-source-py#400]
For example 
![Screenshot from 2019-06-11 19-48-10](https://user-images.githubusercontent.com/50222412/59262107-f4f6de00-8c81-11e9-8526-c0c69b25739c.png)

**Comment by jstac** [comment]
Thanks for opening this issue @AnjuJoon .

I think we need to enforce a maximum of 80 characters per line in all Python code on the entire website, including comments.  This is, in any case, the PEP8 standard.

The rule needs to be added to the style guide.

**Comment by AnjuJoon** [comment]
@jstac I will try to do this and will edit the style guide as well. Thanks!

**Comment by AnjuJoon** [comment]
Moving the code closer to the PEP 8 conventions will solve this issue. This problem will be tracked by issue #470  hence closing this issue
