### ISSUE TITLE
Handle figues through Markdown and local files?

### ISSUE THREAD

**Issue by jstac** [QuantEcon/lecture-source-py#430]
Hi @mmcky and @AakashGfude, 

There are a couple of issues with the way we handle figures included via the `.. figure::` directive.

First, it's hard for the user to work with them during the "edit rsts --- view ipynb" loop because they are pulled in from a remote source.  This isn't really a workable solution from the editor's perspective.  Is there a fix we can come up with?

Second, and perhaps this can be fixed more quickly, can we please embed those figures into the ipynb file via markdown rather than html?  

There are some suggestions of how this might be done [here](https://stackoverflow.com/questions/32370281/how-to-embed-image-or-picture-in-jupyter-notebook-either-from-a-local-machine-o/32370538#32370538) although there might be better methods.

Actually this last one is kind of urgent because html is ignored by pandoc when converting ipynb files to tex files.  I'm CCing @AnjuJoon because she can't get the images included in the PDFs until this is fixed.

**Comment by mmcky** [comment]
hi @jstac if you're using the `lecture-source-py` repository then you can use `make local` which triggers images to be local by forcing the option ` -D jupyter_images_urlpath=0`. This was setup for Natasha to do local editing. In the future I would like this to be replaced with `make ipynb` which is all about local editing and conversion to notebook format and `make jupyter` which will allow the full build approach.

**Comment by mmcky** [comment]
@jstac one issue with adding images via markdown is the `:scale:` parameter can't be used which is the main reason they are included as `html` at the moment.

**Comment by jstac** [comment]
Hi @mmcky, thanks for the quick reply!

On the second point, good news.  We got rid of all the `:scale:` directives on @DrDrij 's advice `:-)`

A grep shows a couple of `:scale:`s left in the index files but I'm sure they could be tidied up.  Could we please proceed with this and switch to Markdown, so @AnjuJoon can finish up producing the pdfs?

On the first point, we talked about this yesterday to some degree, but 

* I wouldn't be in favor of those two names (`make ipynb` and `make jupyter`) because the distinction wouldn't be clear to a new user.  See [here](https://github.com/QuantEcon/sphinxcontrib-jupyter/issues/192) for more discussion.
*  I'm not sure why we need something in between a `make jupyter`, that is all about local editing (what you refer to as `make ipynb` but I'd prefer not to change the name so we don't break the workflow of people like Tom), and `make website`, which is all about generating a website ready for publishing.  Isn't that what we agreed or did I get it wrong?  I'm happy to be corrected, but it seems to me that anything in between is beyond the scope of the regular user and should be controlled with flags.

Finally, in my view, `make jupyter` should take over `make local` as well, since it's all about local editing.

**Comment by jstac** [comment]
@mmcky  Can we close this?

**Comment by jstac** [comment]
@mmcky ping

**Comment by mmcky** [comment]
@jstac this can be closed. @AakashGfude let's check this afternoon that https://github.com/QuantEcon/sphinxcontrib-jupyter/pull/194 is adhered to in the PR for improved `UX` commands.
