### ISSUE TITLE
Reorganize _static folder

### ISSUE THREAD

**Issue by jstac** [QuantEcon/lecture-source-py#431]
I think we had this in our last issue tracker and somehow put it in the too hard basket, but the problem is only getting worse.

Let's say figure `xyz.png` in `_static/figures` is found to have an error and we need to fix it.  But where did it come from and where is the code that generated it?  Sometimes this question has easy answers but often it doesn't.  The generating code can be hard to find or nowhere to be found.  (@AnjuJoon had this problem when she needed to resize figures.)

We need to change conventions.

What I suggest is that immediately under static we have a folder called `lecture_specific` that itself contains folders `about_py`, `getting_started`, ..., one for each lecture.

Each of these is a flat directory containing *all* supporting files specific to the lecture, including

* any `*.py` files
* any figures, such as `*.png` files, as well as the code that generated them (e.g., a `.py` file of the same name or a tikz file).
* anything that's pulled in from a `:download:` directive, like pdfs.

If we happen to reference a static asset from a second or third lecture -- which is rare -- we can do it via a symbolic link.

I know this is a pain because its tedious and we have to change the paths in the files too, as well as match figures to lectures.  But the task gets harder and more urgent the more that time goes by.  Can we find a day over the next few weeks and get this done?

CC @mmcky @AakashGfude @AnjuJoon

**Comment by jstac** [comment]
@AnjuJoon This is yet another big job, and lower priority than some of the others but it would be great if we could get it done before you go.  Let's try to discuss it next time we meet.

**Comment by AnjuJoon** [comment]
@jstac yeah sure. I can try to complete that before I go.

**Comment by jstac** [comment]
@mmcky @AakashGfude Please note that @AnjuJoon has implemented these changes to the structure of the source repo.

A big thanks to @AnjuJoon once again.
