### ISSUE TITLE
Empty tikz figures

### ISSUE THREAD

**Issue by jstac** [QuantEcon/lecture-source-py#434]
Some of our tikz figure source files are empty:

https://github.com/QuantEcon/lecture-source-py/blob/master/source/_static/figures/tikz_figures/orth_proj2D.tex

@AnjuJoon, I remember that you worked on these figures recently.  Are you able to find the contents that makes the current figures and add it in?  It's important we keep track of the source files for the next time that we need to edit the figures.

**Comment by AnjuJoon** [comment]
@jstac when I tried to generate the figures, I was not able to generate png's but instead pdf's of the figures. I can try once again to generate png's.

**Comment by jstac** [comment]
I don't mind if it's pdf or PNG.  I only care that we keep source files (in this case Tex files) so we can adjust figures in the future.

**Comment by AnjuJoon** [comment]
@jstac Can we close this issue now?
