### ISSUE TITLE
IPython Blocks not running in the code executor

### ISSUE THREAD

**Issue by mmcky** [QuantEcon/lecture-source-py#44]
python_essentials
![screenshot from 2018-09-12 11-47-23](https://user-images.githubusercontent.com/20714542/45397211-5aca2100-b682-11e8-97b9-33fdc8509ac0.png)

- [x] add language synonyms to allow individual highlighting of code-blocks and include as executable blocks in the output

**Comment by mmcky** [comment]
https://github.com/QuantEcon/sphinxcontrib-jupyter/pull/110 will fix this issue

**Comment by mmcky** [comment]
@fkazemian when I update the compare-lectures.quantecon.org later this afternooon -- would you mind checking that handling of ``.. code-block:: ipython`` is working properly. The above PR should fix these types of errors.

**Comment by fkazemian** [comment]
Hi @mmcky sure. I keep eyes on that.

**Comment by mmcky** [comment]
these are now included in the notebook but it appears they still don't get executed by our notebook runner. Here is a screenshot of ``python_essentials`` on the compare server

![image](https://user-images.githubusercontent.com/8263752/45810390-e5a7bd00-bd0d-11e8-85d7-9a3d7e07274a.png)

**Comment by mmcky** [comment]
might have to transform executed notebooks to include calls to the magic functions when running on the ``python3`` executor

```python
get_ipython().magic('matplotlib inline')
```

https://nbconvert.readthedocs.io/en/5.x/customizing.html

**Comment by mmcky** [comment]
- [ ] updated on compare

**Comment by mmcky** [comment]
@fkazemian would you be able to check the ``ipython`` blocks in the newly updated set of files?

**Comment by fkazemian** [comment]
Hi @mmcky this issue is fixed. I change the label to fixed. Thanks

**Comment by mmcky** [comment]
thanks!
