### ISSUE TITLE
undefined control sequence in latex

### ISSUE THREAD

**Issue by AnjuJoon** [QuantEcon/lecture-source-py#445]
@jstac could you please help to fix this?
**orth_proj.rst**

! Undefined control sequence.
l.472 \hat y := \argmin
                       _{z \in S} \|y - z\|
? 

! Undefined control sequence.
l.775 ...span}} X := \mathop{\mathrm{span}} \{\col
                                                  _1 X, \ldots, \col_k X \}
? 

! Undefined control sequence.
l.992 \argmin
             _{b \in \mathbb R^K} \sum_{n=1}^N (y_n - b' x_n)^2
? 

! Undefined control sequence.
l.1124   \(x_j := \col
                      _j (X)\)\\
?

**rational_expectations.rst**

! Undefined control sequence.
l.655 h(y, Y) := \argmax
                        _{y'}
?

**Comment by mmcky** [comment]
@AnjuJoon are these latex warnings or errors? Are those lines contained inside of a `math` environment of some kind?

**Comment by AnjuJoon** [comment]
adding these commands in preamble solves the issue-

\newcommand{\argmax}{\operatornamewithlimits{argmax}}
\newcommand{\argmin}{\operatornamewithlimits{argmin}}
\DeclareMathOperator{\col}{col}
