### ISSUE TITLE
Index Pages are Currently Not Supported

### ISSUE THREAD

**Issue by mmcky** [QuantEcon/lecture-source-py#45]
It would be nice for the extension to build the whole site (including all the index pages) via IPYNB.

The index pages should just be a simple notebook with a single markdown cell. 

![image](https://user-images.githubusercontent.com/8263752/45667125-31663500-bb5b-11e8-80d3-de0c1491344d.png)

**Comment by mmcky** [comment]
@DrDrij this PR adds support for top level ``toctree`` objects. I haven't tested on internal toctree objects yet but so far so good `:-)`.

https://github.com/QuantEcon/sphinxcontrib-jupyter/pull/111

I have update the ``index*.ipynb`` files that are generated on the branch for the PR in the ``jupinx`` extension on compare-lectures.quantecon.org

**Comment by mmcky** [comment]
``toc`` elements within lectures need some work

![image](https://user-images.githubusercontent.com/8263752/45670723-dc302080-bb66-11e8-8a19-886d5ba2ac11.png)

**Comment by DrDrij** [comment]
Hmm. There isn't anything specific enough in the HTML (classes etc) to hook onto with CSS.

**Comment by mmcky** [comment]
@fkazemian I have put together a PR that should fix the index issues during compilation.
https://github.com/QuantEcon/sphinxcontrib-jupyter/pull/111

However it changes the internal implementation when writing lists. @fkazemian  I am in the process of updating the lecture set on compare-lectures.quantecon.org to be from this branch of ``jupinx``. When I let you know on slack that the site is updated would you mind looking at some lists at random to see if they have changed?

**Comment by mmcky** [comment]
@fkazemian 

- [ ] `amss2` is not fixed on compare-lectures.quantecon.org as that is a fix that happened at the rst level and I have not updated my source files in the build repository. 

When you have a chance to check other lists that would be great. Thanks

**Comment by mmcky** [comment]
- [ ] @fkazemian would you mind checking the index objects that have been created this afternoon and are now live on compare-lectures.quantecon.org

**Comment by fkazemian** [comment]
Hi @mmcky , I'm checking them ...

**Comment by fkazemian** [comment]
about_py
index is fine but there is a tag div here
![screenshot from 2018-09-21 11-20-49](https://user-images.githubusercontent.com/20714542/45854833-7f17b300-bd90-11e8-91bd-62f19a563a6a.png)

there is no problem with aiyagari, but you don't think it should have an index? ( the live version dosen't have it as well)
![screenshot from 2018-09-21 11-23-55](https://user-images.githubusercontent.com/20714542/45854933-f9e0ce00-bd90-11e8-8c3a-8598487cc039.png)
also amss3 doesn't have any index:
![screenshot from 2018-09-21 11-25-34](https://user-images.githubusercontent.com/20714542/45854965-2399f500-bd91-11e8-8fb4-5153be0a2aac.png)
chang_credible 
`Calculating set of sustainable (w,θ) pairs-$-pairs) `should be `Calculating set of sustainable (w,θ) pairs`
![screenshot from 2018-09-21 11-27-16](https://user-images.githubusercontent.com/20714542/45856260-1f70d600-bd97-11e8-9342-5e8a208819c7.png)

chang_ramsey
`Calculating all  (w,θ)  pairs in  CE -−pairs−in−-CE-$)` should be `Calculating all  (w,θ)  pairs in  CE`
![screenshot from 2018-09-21 12-09-24](https://user-images.githubusercontent.com/20714542/45856322-547d2880-bd97-11e8-9027-d75cdcff4be8.png)

**Comment by mmcky** [comment]
@DrDrij it looks like you modify the local `toc` in the theme to drop `Contents` and the top level, as I just build off of the `toc` branch and it seems that within lectures `toc` objects are fixed. If this is the case I will remove my patch from ``jupinx`` to drop a level.

**Comment by mmcky** [comment]
![image](https://user-images.githubusercontent.com/8263752/45858777-50a2d380-bda2-11e8-9009-439326cb6f5f.png)

**Comment by mmcky** [comment]
ahh - I see. https://github.com/mmcky/quantecon.build.lectures/commit/24756155a016f856031f7103dc86d4120e2bf45f#diff-c45e43ff5986a2189468b78b4c57c2c8R915. I will remove the patch I made to ``jupinx`` this is much better

**Comment by mmcky** [comment]
ok - the python index pages should now be working.

**Comment by mmcky** [comment]
@fkazemian would you mind checking the python related index pages and let me know if they are ok?

**Comment by fkazemian** [comment]
Hi @mmcky they are now like 
![screenshot from 2018-09-21 17-18-55](https://user-images.githubusercontent.com/20714542/45865952-88217800-bdc2-11e8-958f-5c918aa2abea.png)

but we can see the problems I mentioned above.

**Comment by mmcky** [comment]
@fkazemian so is the only issue now clickable titles?

**Comment by mmcky** [comment]
@fkazemian can you add a PR to add a `toc` to these lectures. 

@jstac can you advise if you wish there to be no `toc` elements for these lectures.

- [ ] `uncertainty_traps`
- [ ] `rob_markov_perf`
- [ ] `markov_perf`
- [ ] `amss3`
- [ ] `aiyagari`

**Comment by fkazemian** [comment]
- [ ] `uncertainty_traps`
- [ ] `rob_markov_perf`
- [ ] `markov_perf`
- [ ] `amss3`
- [ ] `aiyagari`

**Comment by DrDrij** [comment]
> @DrDrij would you mind checking out `nbconvert` on the `chang_credible` lecture at the `html` stage of `nbconvert`?

It appears what is happening is nbconvert is stumbling with the markdown in the ipynb file. You see in the below link from the TOC list there are brackets within brackets. So link value is being terminated at the first closing bracket.

`    "  - [Calculating  set of sustainable $ (w,\\theta) $ pairs](#Calculating--set-of-sustainable-$-(w,\\theta)-$-pairs)  "`

This results in the href anchor being cut too soon and the remaining part of the string is being appended after the `</a>` as shown below.

`<li><a href="#Calculating--set-of-sustainable-$-(w,\theta">Calculating  set of sustainable $ (w,\theta) $ pairs</a>-$-pairs)  </li>`

The way to fix this in the markdown is to escape the first closing bracket with `%29`. I've tested this locally and can confirm this works with nbconvert.

![image](https://user-images.githubusercontent.com/5886045/46806018-2aec6700-cd6f-11e8-9227-55857f1cddfa.png)


The heading in the body of the page however works fine as it doesn't have the double brackets.

`    "## Calculating  set of sustainable $ (w,\\theta) $ pairs\n",
`

@mmcky Is there a tweak you could make in jupinx to escape brackets within markdown links?

**Comment by mmcky** [comment]
thanks @DrDrij - love your work. If we change closing brackets with `%29` should we also adjust opening brackets for consistency?

**Comment by mmcky** [comment]
@DrDrij with PR https://github.com/QuantEcon/sphinxcontrib-jupyter/pull/132 I have done that for all inline math that is contained in a topic when targeting `html`.

**Comment by mmcky** [comment]
this is fixed. thanks @DrDrij and @fkazemian for your input no this.
