### ISSUE TITLE
Placement of In and Out text for code-blocks

### ISSUE THREAD

**Issue by mmcky** [QuantEcon/lecture-source-py#47]
@DrDrij Are we able to alter the placement of In and Out text for the code-blocks to mimic more closely what we had on the website? It would be neat if we could have them in the margin and in our QuantEcon orange text :)

<img width="318" alt="image" src="https://user-images.githubusercontent.com/8263752/45721324-fc092800-bbea-11e8-9c98-e2c293c283df.png">

**Comment by mmcky** [comment]
Class for input prompt in generated `nbconvert` output

```html
<div class="prompt input_prompt">In&nbsp;[2]:</div>
```

**Comment by DrDrij** [comment]
Styles have been added!

![image](https://user-images.githubusercontent.com/5886045/45764606-c2acd880-bc3b-11e8-9394-57c882ee474b.png)

**Comment by jstac** [comment]
@DrDrij Looks great

**Comment by DrDrij** [comment]
@jstac Thanks. Note: I've hidden the numbering that was being outputted as it didn't fit when put in the margin:

![image](https://user-images.githubusercontent.com/5886045/45781515-e0dcfd80-bc68-11e8-9114-307a7f4f6325.png)

**Comment by jstac** [comment]
All good.

**Comment by mmcky** [comment]
thanks @DrDrij this looks good.

**Comment by mmcky** [comment]
This is being picky - can the `Out` text be aligned with the first line of text?

Also it seems in some multiline output cases the Out doesn't show up

<img width="748" alt="image" src="https://user-images.githubusercontent.com/8263752/45789273-27ab1180-bcc2-11e8-827b-8ac1da31a85e.png">

**Comment by DrDrij** [comment]
Out label now aligned with first row - thanks for picking this up @mmcky 

qe.css is now at v2.4 - I've updated on your repo

**Comment by mmcky** [comment]
thanks @DrDrij does this also resolve `out` not showing up for multiline output?

**Comment by DrDrij** [comment]
@mmcky Having trouble locating an example. I did find the following which looked ok:

![image](https://user-images.githubusercontent.com/5886045/46352851-71511000-c663-11e8-8a0f-217eda7e8781.png)

**Comment by mmcky** [comment]
the outs in the following section don't seem to appear: 
http://compare-lectures.quantecon.org/python_advanced_features.html#Name-Resolution

**Comment by DrDrij** [comment]
@mmcky I've made all the prompt markers CSS based. The "In" and "Out" labels are added by the CSS where respective classes exist. This is regardless of the labels appearing in the HTML, any that exist are hidden.

So any inputs (prompt areas) that don't have a label now are missing both appropriate classes to hook onto and HTML labels. If we wan't to add labels to those I think it will need some work in jupinx.

**Comment by mmcky** [comment]
roger that -- thanks @DrDrij I will dig a bit further into this one. Not sure why they are different.

**Comment by mmcky** [comment]
thanks @DrDrij I think this is actually working. There are a couple of things that look like `out` but are in fact not generated out blocks, but rather located in the source RST.

Thanks for your help on this. Closing now.
