### ISSUE TITLE
Bring code closer to PEP8 when there's no good reason to do otherwise

### ISSUE THREAD

**Issue by jstac** [QuantEcon/lecture-source-py#470]
In general, our code should conform to PEP8, unless there's a good reason to do otherwise.

One example of the latter (i.e, one good reason to deviate from PEP8) would be to get closer to the mathematics.  For example, if a lecture refers to a matrix denoted by A, then it makes sense to call it `A` in the code, rather than `a`, say.

But if there is no good reason to deviate, we should follow PEP8.  

Here's an example of something we should correct.  In https://lectures.quantecon.org/py/cattle_cycles.html it says

`Info1 = Information(a22, c2, ub, ud)`

But PEP8 says that instances should have lowercase names.  So `Info1` should be `info1`.

There's no good reason to deviate from PEP8 here.

@AnjuJoon, please read PEP8 carefully,

1. add this convention to the README of this repo under "Style guide", so that others know, along with a link to https://www.python.org/dev/peps/pep-0008/
2. move our code towards PEP8 as much as possible.

**Comment by AnjuJoon** [comment]
@jstac yeah, I will work on it. Thanks

**Comment by AnjuJoon** [comment]
@jstac These changes are implemented in all the lectures so closing this issue!
