### ISSUE TITLE
Issues while converting ipynb's to pdfs

### ISSUE THREAD

**Issue by AnjuJoon** [QuantEcon/lecture-source-py#478]
- [ ]  The labels(for math equations and for sections) are reflected as a link in ipynb's which are completely ignored by the Pandoc

- [ ]  "(" opening bracket is replaced by "%28" and the closing bracket is replaced by "%29" for the headings which are reflected in the contents section in .tex 

- [ ] Images should be in markdown

- [ ] I am not sure how is " ` " (only for headings) replaced while conversion to ipynb's

- [ ] Anything written in between "[ ]" (for internal links of the lectures) is replaced by the word "section" in .tex files so if we could write it as it is then it could be very helpful

- [ ] Citations (keys could be removed) and the link like  "zreferences.html#" could be removed

**Comment by mmcky** [comment]
thanks @AnjuJoon are these the only prepossessing items needed for `pdf` source notebooks?

**Comment by AnjuJoon** [comment]
@mmcky there are some more things but I am not able to decide if it should be preprocessed in latex or ipynb's will be  a better option to preprocess in but I will keep adding to it if I feel that it would be better to preprocess in ipynb's

**Comment by mmcky** [comment]
@AnjuJoon if you can document what needs to be changed from the current `baseline` then we can work together on figuring out which level the change should take place at. So a big table of what needs to be changed would be good and then we can go through it and think through the best place to make that change.

**Comment by mmcky** [comment]
@AnjuJoon what would be helpful is a table such as the following:

| rst  |    ipynb  |  issue description | update | resolved |
|----|---------|-------------------|--------|----------|
| (   | %28 | html friendly %28 is used in preference to brackets, and no current option to pass through bracket to generated ipynb | sphinxcontrib-jupyter | no |

for all the edges cases you have come across. Don't need to filling the `update` column and we can all discuss where we should update to resolve the conversion issue. If there is not enough space in the `issue` for the table please start a `wiki` page.

**Comment by mmcky** [comment]
This issue has been moved to the wiki: https://github.com/QuantEcon/lecture-source-py/wiki/Conversion-to-PDF-(Edge-Cases-and-Conversion-Issues)

Please check there for updates

**Comment by mmcky** [comment]
The wiki page documents work and solutions to this issue. Closing.
