### ISSUE TITLE
Avoid spaces in file names

### ISSUE THREAD

**Issue by jstac** [QuantEcon/lecture-source-py#480]
Please avoid spaces and capitals in file names.

In particular, please change the name of "Quantitative Economics with Python.pdf" to "quantitative_economics_with_python.pdf".

CC @mmcky

**Comment by AnjuJoon** [comment]
@jstac I did not understand which files are you referring to? The pdf's on the website?

**Comment by AnjuJoon** [comment]
There are no capitals and spaces in individual lecture pdf's. Only the name of the global pdf is with spaces and capitals. @mmcky Can I do something about it?

**Comment by jstac** [comment]
At the moment it's fine --- not a big deal --- but please change your code so that next time you generate the file, it has the alternative file name that I requested.

Let's just always use this convention for file names, in any file associated with quantecon.

**Comment by AnjuJoon** [comment]
@jstac yeah sure. I will keep this in mind
