### ISSUE TITLE
Sphinx Warnings that need to be resolved

### ISSUE THREAD

**Issue by mmcky** [QuantEcon/lecture-source-py#49]
Here is a list of sphinx warnings that should be resolved.

**Comment by natashawatkins** [comment]
These issues seemed to be introduced when I ran jinja 'for the last time'

**Comment by natashawatkins** [comment]
What should I do when we want to reference an output figure?

**Comment by mmcky** [comment]
@natashawatkins I think the only thing we can do for now is add a label reference before the code block that generates the output figure? What do you think?

**Comment by natashawatkins** [comment]
Yeah i agree

**Comment by mmcky** [comment]
these are outdated. Closing and will open a new issue to track current state.
