### ISSUE TITLE
Issue with Compilation on master branch - `_pdf_class`

### ISSUE THREAD

**Issue by mmcky** [QuantEcon/lecture-source-py#507]
@AakashGfude the current `master` branch appears to have an issue with `_pdf_class` preventing it from executing and compiling the lectures. I am not sure why `pdf_class` is on the master branch as `pdf` branch hasn't been merged yet. It must have snuck in on another commit. 

@AakashGfude can you look at this with priority over other tasks. Thanks!

The error is:

```
Exception occurred:
  File "/Users/matthewmckay/repos-collab/sphinxcontrib-jupyter/sphinxcontrib/jupyter/writers/execute_nb.py", line 155, in check_execution_completion
    builderSelf._pdf_class.convertToLatex(executed_nb, filename)
AttributeError: 'JupyterBuilder' object has no attribute '_pdf_class'
The full traceback has been saved in /var/folders/1r/pjck6mns4qd24h7yw2g3fn500000gp/T/sphinx-err-fapioc80.log, if you want to report the issue to the developers.
```

**Comment by AakashGfude** [comment]
Hi @mmcky . I checked the master branch of `sphinxcontrib-jupyter` , I don't get this error and not able to see the `pdf_class` in there. Can you double check once at your end for any branch anomaly. Thanks.

**Comment by mmcky** [comment]
thanks @AakashGfude -- it is happening in the Docker environment. I will try and take a closer look at the Docker specification.

**Comment by mmcky** [comment]
@AakashGfude I think it might be because `Docker` isn't fully self contained as you mentioned. I had the `make-pdf` branch checked out on my local machine. That might be what happened.

**Comment by mmcky** [comment]
I am closing this as a non-reproducible error. `Docker` approach is changing to be self contained.
