### ISSUE TITLE
Most recent lectures require preamble installs to run on Google Colab

### ISSUE THREAD

**Issue by mmcky** [QuantEcon/lecture-source-py#536]
We need to update:

1. `tax_smoothing_1`
1. `tax_smoothing_2`
1. `tax_smoothing_3`

with 

`pip install quantecon` cell blocks.

**Comment by jstac** [comment]
Well spotted, thanks @mmcky !

@AnjuJoon, could you please address this (and try to remember to add in future)?

It would be great if we had a test for successful colab execution, although I can't think of any way to do it...   Perhaps it's worth opening an issue, @mmcky , as to the need for such a test if we can work out a good way?

**Comment by jstac** [comment]
@AnjuJoon Please cancel that request --- I just saw #537

**Comment by AnjuJoon** [comment]
> Well spotted, thanks @mmcky !
> 
> @AnjuJoon, could you please address this (and try to remember to add in future)?
> 
> It would be great if we had a test for successful colab execution, although I can't think of any way to do it... Perhaps it's worth opening an issue, @mmcky , as to the need for such a test if we can work out a good way?

@jstac Sure, I will remember that (missing that in new lectures was a big blunder from my side :( Won't happen in future)

**Comment by mmcky** [comment]
This has been fixed in #537
