### ISSUE TITLE
Numba error in PDFs

### ISSUE THREAD

**Issue by jstac** [QuantEcon/lecture-source-py#539]
Please see the `TypingError` on page 12 of

https://lectures.quantecon.org/_downloads/pdf/py/optgrowth.pdf

The issue will be the version of Numba on @AnjuJoon 's machine is different to that constructing the website.  I guess the best solution would be to build PDFs on the same machine.

CC @AnjuJoon @mmcky

**Comment by AnjuJoon** [comment]
@mmcky @jstac Is there a way to change the version of Numba on my machine?

**Comment by mmcky** [comment]
Hi Anju -- you could run:

conda install numba=0.44.1

to upgrade to next version after the default in Anaconda

**Comment by AnjuJoon** [comment]
Thankyou so much @mmcky. Running this solved the problem. 

Should I generate new pdfs free from Numba errors?

**Comment by mmcky** [comment]
Thanks Anju. That would be great.
