### ISSUE TITLE
Error while executing the notebooks

### ISSUE THREAD

**Issue by AnjuJoon** [QuantEcon/lecture-source-py#550]
@mmcky @AakashGfude when I am executing all the notebooks I am receiving these errors. 

<img width="1440" alt="Screenshot 2019-08-12 at 3 47 35 PM" src="https://user-images.githubusercontent.com/50222412/62858766-db712180-bd18-11e9-88b6-76a1cc8f7d3b.png">

**Comment by AnjuJoon** [comment]
@AakashGfude  after updating sphinxcontrib-jupyter, I executed the command - "make website parallel=2" in my terminal but again the following error occurred
<img width="1440" alt="Screenshot 2019-08-12 at 4 44 59 PM" src="https://user-images.githubusercontent.com/50222412/62861400-fe9fcf00-bd20-11e9-8ae5-8c3390611539.png">
:

**Comment by AakashGfude** [comment]
@AnjuJoon Thank you for the detailed error. 'Too many open files' is something new. Will keep in touch with you while tackling this.

**Comment by AnjuJoon** [comment]
@AakashGfude Thanks!

**Comment by mmcky** [comment]
In terminal can you run:

```bash
launchctl limit maxfiles
```

**Comment by AnjuJoon** [comment]
**ulimit -n 4096**  ---> running this in terminal resolved this issue. Thanks @mmcky for this great help!
