### ISSUE TITLE
[multiplicative functionals] issue with execution

### ISSUE THREAD

**Issue by mmcky** [QuantEcon/lecture-source-py#551]
The last run of the `master` branch is showing issues with `multiplicative_functionals` lecture

http://preview-lectures.quantecon.org.s3-website-ap-southeast-2.amazonaws.com/py/multiplicative_functionals.html

it appears there are some missing imports due to: https://github.com/QuantEcon/lecture-source-py/commit/4a13bf3f74430e988f0240e8d72050f6404667ff

**Comment by mmcky** [comment]
- [ ] imports need to be added similar to `additive_functionals` lecture now they have been removed from the underlying `py` file.

**Comment by AnjuJoon** [comment]
@mmcky just working on this now. Will let you know once done.
