### ISSUE TITLE
center-alignment for figures dismissed in Jupinx 

### ISSUE THREAD

**Issue by fkazemian** [QuantEcon/lecture-source-py#6]
![1](https://user-images.githubusercontent.com/20714542/44704289-1cf3c700-aade-11e8-8f00-b692a8831134.png)

![2](https://user-images.githubusercontent.com/20714542/44704382-63e1bc80-aade-11e8-93cb-95800577f626.png)

**Comment by mmcky** [comment]
thanks @fkazemian it looks like JupyterLab and Jupyter Notebook rendering differ on this. The same images test notebook are rendering differently.

**Comment by mmcky** [comment]
for each of these reports can you please add the lecture name to the description to help me locate the cases. Thanks.

**Comment by mmcky** [comment]
@fkazemian since we updated `nbconvert` do you still see oversized images on your end?

**Comment by mmcky** [comment]
@DrDrij we do have support for figure alignment pass through in the ``jupinx`` extension - it is just that none of the source files are using it at the moment. I could pretty easily setup a ``jupyter_align_figure`` global to change the default alignment to "center" when writing the figures in `html`. I am just wondering if you think this should be done at the theme level. The reason I ask is if I do this task in jupinx for figures included in the markdown this may not catch figures generated in the executed notebooks.

**Comment by mmcky** [comment]
- [ ] implement a global in ``jupinx`` to center included figures in markdown blocks
- [ ] change to default centered images in the ``quantecon`` template / theme

**Comment by fkazemian** [comment]
Hi @mmcky 
I just checked career.html and I still can see some figures are too big
![screenshot from 2018-09-17 15-05-00](https://user-images.githubusercontent.com/20714542/45606768-3b206780-ba8b-11e8-9804-6ef5d65366f2.png)

**Comment by DrDrij** [comment]
@mmcky I suggest we default to centred images and also set a max-width (addressing @fkazemian figures too big above). I've added a few styles to the compare site to address this.

![image](https://user-images.githubusercontent.com/5886045/45637872-3328ed80-bab4-11e8-856d-e9ead812a519.png)

**Comment by mmcky** [comment]
thanks @DrDrij I will add you as a collaborator to the repo that I am putting together to assemble all of these things through the various stages. Would you mind adding your css etc.

**Comment by mmcky** [comment]
thanks @DrDrij. I am closing this as I think this is now fixed based on compare-lectures.quantecon.org. 
I have opened https://github.com/mmcky/quantecon.build.lectures/pull/6 to add css into the build chain but can update that branch from the compare-lectures if that is easier.
