### ISSUE TITLE
Pandas: Update lecture to use pandas_datareader package

### ISSUE THREAD

**Issue by mmcky** [QuantEcon/lecture-source-py#615]
A suggestion provided via contact@quantecon.org

```
Hi, 

You mention the use of requests and quite a bit of parsing to gain access to economic and fiancial data.

May I suggest a re-write using the library `pandas_datareader` that is a super set of all the data retrieval tasks you present and that output directly to pandas.DataFrame instance type. 

```

**Comment by shlff** [comment]
Hey @mmcky , I find the lecture ``pandas`` has already been rewritten using the library ``pandas_datareader`` as suggested by this issue, please see [here](https://python-programming.quantecon.org/pandas.html#Using-pandas_datareader-to-Access-Data).

Shall we close it?
