### ISSUE TITLE
Text Such as "\alpha" in latex is ignored while building pdf due to "\" 

### ISSUE THREAD

**Issue by AnjuJoon** [QuantEcon/lecture-source-py#687]
The text such as \alpha and \beta (not in math environment) is not reflected in pdf because it is starting with a "\". For example the highlited line in both the below figures

<img width="1374" alt="Screenshot 2019-09-20 at 11 56 15 PM" src="https://user-images.githubusercontent.com/50222412/65350259-f0d44800-dc02-11e9-88d4-56420319c7de.png">
<img width="1407" alt="Screenshot 2019-09-20 at 11 56 46 PM" src="https://user-images.githubusercontent.com/50222412/65350261-f0d44800-dc02-11e9-8267-d80f9003b0b3.png">

**Comment by AnjuJoon** [comment]
@AakashGfude Would you mind to help me with this (as John suggested)

**Comment by AakashGfude** [comment]
sure @AnjuJoon , I will have a look

**Comment by AnjuJoon** [comment]
Thanks, @AakashGfude. Also, this is an issue with Julia lectures. In 3-4 lectures, there are symbols like `\$` or `\\$` in-between text for the demonstration, which are wrongly interpreted by latex of course because they symbolize the beginning and ending of math environment. This will also give an error while building the global pdf and individual pdfs and stop the process.

**Comment by AakashGfude** [comment]
Hi @jstac @AnjuJoon @mmcky , so regarding the issue of insering greek letters, the pdf in `julia` is working (you can see the `\alpha` being rendered ) :- 
![insertingUnicode](https://user-images.githubusercontent.com/6542997/66010226-67c1e880-e501-11e9-87a0-6b171d6b91d2.png)

whereas in python case, `\alpha` is not being rendered.

![pythonUnicode](https://user-images.githubusercontent.com/6542997/66010354-f2a2e300-e501-11e9-95bb-0dcf5ec2c138.png)
 

The difference is the way rst is written  :- 

julia - \`\`\alpha\`\` in  rst, \`\\\alpha\` in ipynb, and `\texttt{\textbackslash{}alpha}` in tex
python - \`\\\alpha\` in rst, `\\alpha` in ipynb, and `\alpha` in tex

so, my question is, is second also the correct way? should the python one be handled? or if handled it may break something else?

**Comment by AnjuJoon** [comment]
Hi @AakashGfude why should it be different for Julia and python lectures since the normal text(other than code) works the same way for Julia or Python and the conversion to ipynb is same too
