### ISSUE TITLE
some matplotlib figures not showing up

### ISSUE THREAD

**Issue by fkazemian** [QuantEcon/lecture-source-py#7]
![4](https://user-images.githubusercontent.com/20714542/44704788-00f12500-aae0-11e8-9a58-bb735b77623e.png)

**Comment by fkazemian** [comment]
![ai](https://user-images.githubusercontent.com/20714542/44771672-05d0da00-abaf-11e8-9b06-fd21ddd0fe7b.png)
aiyagari.html

**Comment by natashawatkins** [comment]
Yes.

This is a bug with either matplotlib or the jupyter notebook - if you re-run the cell, the image will show up. For some reason it seems that matplotlib needs to be initialised once before it displays images inline.

**Comment by natashawatkins** [comment]
I would recommend closing this issue - I don't think there's anything we can do to fix it - I've seen it only others' computers in workshops as well.

**Comment by natashawatkins** [comment]
Ah I see this is in the generated notebook... um yes ok this seems to be a recent bug with Jupyter notebooks.

Here is a discussion of the issue: https://github.com/ioam/holoviews/issues/68

Can we change the settings for matplotlib?

**Comment by mmcky** [comment]
@natashawatkins any changes are just required to be in a code-block for it to be contained in the notebook.

**Comment by natashawatkins** [comment]
No I was wondering whether it would be possible to edit the config file for matplotlib as suggested in the thread. The location should be `~/.matplotlibrc`. They suggest changing the default backend could fix the issue.

**Comment by fkazemian** [comment]
In amss.html, it seems codes that creat matplotlib figures, are not running. 
![screenshot from 2018-09-03 11-08-01](https://user-images.githubusercontent.com/20714542/44963641-4ba2ef00-af6f-11e8-8c06-64a3d1ebdee6.png)
 
![screenshot from 2018-09-03 11-08-58](https://user-images.githubusercontent.com/20714542/44963644-4e054900-af6f-11e8-8c1e-1428e19bcf5e.png)

![screenshot from 2018-09-03 11-09-21](https://user-images.githubusercontent.com/20714542/44963647-51003980-af6f-11e8-89ba-59c83bb9ef84.png)

**Comment by natashawatkins** [comment]
That's weird, maybe it's timing out...

We should definitely remove those print statements, on another note

**Comment by mmcky** [comment]
@fkazemian is this happening locally for you also? 

When I built the ``html`` via ``IPYNB`` for the compare-lectures site -- it might have timed out the execution for this specific lecture. Can you confirm if the ``amss2`` lecture works locally?

**Comment by fkazemian** [comment]
arma:

![screenshot from 2018-09-04 12-41-04](https://user-images.githubusercontent.com/20714542/45013906-1aeeb280-b060-11e8-98dc-005601149f4e.png)

![screenshot from 2018-09-04 13-25-33](https://user-images.githubusercontent.com/20714542/45013910-1d510c80-b060-11e8-992d-912133c7c4be.png)

Hi @mmcky I don't have this problem when I'm running it locally: 
![screenshot from 2018-09-04 16-30-27](https://user-images.githubusercontent.com/20714542/45013937-35c12700-b060-11e8-829e-89da5e95c472.png)

**Comment by fkazemian** [comment]
(career)

![screenshot from 2018-09-05 10-37-18](https://user-images.githubusercontent.com/20714542/45064769-f1359a00-b0f8-11e8-9d56-ff529a75f312.png)

but it works fine locally
![screenshot from 2018-09-05 10-42-22](https://user-images.githubusercontent.com/20714542/45064776-f98dd500-b0f8-11e8-8ad7-52f9eaa0fa61.png)

**Comment by fkazemian** [comment]
(debugging)
![screenshot from 2018-09-05 15-01-38](https://user-images.githubusercontent.com/20714542/45072147-fad0f900-b11c-11e8-8c8a-70a38cf3aab1.png)

but it works fine locally:

![screenshot from 2018-09-05 15-02-57](https://user-images.githubusercontent.com/20714542/45072151-058b8e00-b11d-11e8-8c73-441ed4a617dc.png)

**Comment by fkazemian** [comment]
discrete_dp:
![screenshot from 2018-09-05 15-22-29](https://user-images.githubusercontent.com/20714542/45072914-4b962100-b120-11e8-84fe-d5ac18968d38.png)

**Comment by mmcky** [comment]
hey @fkazemian when I run arma locally -- the first time I get the text output and the second run I get the figure. That is a bit strange. Do you get the same?

**Comment by fkazemian** [comment]
Hi @mmcky , no actually in the first time run I got the figure, and also I just checked arma locally again and I got the figure in my first run. I am using the computer in the lab ( Number1).

**Comment by fkazemian** [comment]
(estspec)
![screenshot from 2018-09-07 11-00-56](https://user-images.githubusercontent.com/20714542/45192926-cb41fe00-b28e-11e8-9fc7-609943c75e93.png)

![screenshot from 2018-09-07 11-02-35](https://user-images.githubusercontent.com/20714542/45192928-ce3cee80-b28e-11e8-9b68-cfdfd3a60b10.png)

![screenshot from 2018-09-07 11-02-47](https://user-images.githubusercontent.com/20714542/45192930-d09f4880-b28e-11e8-8732-fa435aa1492a.png)

**Comment by fkazemian** [comment]
(finite_markov)
![screenshot from 2018-09-07 11-18-22](https://user-images.githubusercontent.com/20714542/45193631-5bce0d80-b292-11e8-9e92-8686d1fffd2e.png)

**Comment by fkazemian** [comment]
(hist_dep_policies)
![screenshot from 2018-09-07 13-27-22](https://user-images.githubusercontent.com/20714542/45197120-f59db680-b2a2-11e8-9c3b-cf033a2bfaf1.png)

**Comment by fkazemian** [comment]
(ifp)
![screenshot from 2018-09-07 13-53-34](https://user-images.githubusercontent.com/20714542/45198560-757b4f00-b2aa-11e8-8fa6-0f417c7f210a.png)

**Comment by fkazemian** [comment]
(jv)
![screenshot from 2018-09-07 14-50-06](https://user-images.githubusercontent.com/20714542/45199172-b0cb4d00-b2ad-11e8-8c0c-ca580f266008.png)

![screenshot from 2018-09-07 14-49-28](https://user-images.githubusercontent.com/20714542/45199174-b2951080-b2ad-11e8-9e2d-fde6c07a94e1.png)

**Comment by fkazemian** [comment]
(kalman)
![screenshot from 2018-09-07 14-53-56](https://user-images.githubusercontent.com/20714542/45199417-e6bd0100-b2ae-11e8-8dcd-c425b609e6a5.png)

**Comment by fkazemian** [comment]
(lake_model)
![screenshot from 2018-09-07 15-04-05](https://user-images.githubusercontent.com/20714542/45199813-035a3880-b2b1-11e8-8071-c1fd8f07667b.png)
![screenshot from 2018-09-07 15-05-21](https://user-images.githubusercontent.com/20714542/45199814-03f2cf00-b2b1-11e8-826a-58bfa79bc65e.png)

**Comment by fkazemian** [comment]
(lln_clt)
![screenshot from 2018-09-10 11-20-33](https://user-images.githubusercontent.com/20714542/45271779-a2b73f80-b4ec-11e8-9c36-7ce6fa4c7718.png)

**Comment by fkazemian** [comment]
(lqcontrol)
![screenshot from 2018-09-10 11-51-54](https://user-images.githubusercontent.com/20714542/45272865-10666a00-b4f3-11e8-83ca-158c62ca5b75.png)

**Comment by fkazemian** [comment]
(lu_tricks)
![screenshot from 2018-09-10 16-03-40](https://user-images.githubusercontent.com/20714542/45279135-677c3700-b513-11e8-9172-1f047e6b8dad.png)

**Comment by fkazemian** [comment]
(lucas_model)
![screenshot from 2018-09-10 16-09-02](https://user-images.githubusercontent.com/20714542/45279443-731c2d80-b514-11e8-878e-879deb1d1111.png)

**Comment by fkazemian** [comment]
(markov_asset)
![screenshot from 2018-09-10 16-19-08](https://user-images.githubusercontent.com/20714542/45280417-9a282e80-b517-11e8-905c-102579b745d9.png)

**Comment by fkazemian** [comment]
(markov_perf)
![screenshot from 2018-09-11 09-58-56](https://user-images.githubusercontent.com/20714542/45330644-bffe1380-b5a9-11e8-8a1a-5da009baac9a.png)

**Comment by jstac** [comment]
@mmcky I've had similar problems.  Does it help if you put `matplotlib inline` at the top of the Jupyter notebook, like we used to a few years back?  Perhaps we need to return to the same convention?

**Comment by fkazemian** [comment]
(matplotlib)
![screenshot from 2018-09-11 10-06-04](https://user-images.githubusercontent.com/20714542/45330808-97c2e480-b5aa-11e8-8126-2bc9a6d8d668.png)

**Comment by fkazemian** [comment]
(mle)
![screenshot from 2018-09-11 10-24-24](https://user-images.githubusercontent.com/20714542/45340748-2fd8c200-b5db-11e8-8f4a-0811be06e6c2.png)

**Comment by fkazemian** [comment]
(numba)
![screenshot from 2018-09-11 16-22-44](https://user-images.githubusercontent.com/20714542/45342178-7846ae80-b5e0-11e8-891d-6531bcf0d85a.png)

**Comment by fkazemian** [comment]
odu
![screenshot from 2018-09-11 16-38-49](https://user-images.githubusercontent.com/20714542/45342544-a24ca080-b5e1-11e8-8e7f-98eb24c6bed1.png)

**Comment by fkazemian** [comment]
ols:
![screenshot from 2018-09-11 16-43-59](https://user-images.githubusercontent.com/20714542/45342877-944b4f80-b5e2-11e8-823e-c05eb19baba0.png)

**Comment by fkazemian** [comment]
opt_tax_recur:
![screenshot from 2018-09-11 16-57-26](https://user-images.githubusercontent.com/20714542/45343530-80085200-b5e4-11e8-844e-d1100491760e.png)

**Comment by fkazemian** [comment]
optgrowth:
![screenshot from 2018-09-11 17-10-53](https://user-images.githubusercontent.com/20714542/45344052-1721d980-b5e6-11e8-9f72-b10d52f5ab69.png)

**Comment by fkazemian** [comment]
pandas:
![screenshot from 2018-09-12 09-57-24](https://user-images.githubusercontent.com/20714542/45394272-2a2ebb00-b673-11e8-84dc-3faab599b244.png)

**Comment by fkazemian** [comment]
perm_income
![screenshot from 2018-09-12 10-34-33](https://user-images.githubusercontent.com/20714542/45395144-08840280-b678-11e8-9f39-764d012b1b66.png)

**Comment by fkazemian** [comment]
python_by_example
![screenshot from 2018-09-12 11-17-25](https://user-images.githubusercontent.com/20714542/45396993-636e2780-b681-11e8-9b88-25dae9544276.png)

**Comment by fkazemian** [comment]
python_oop
![screenshot from 2018-09-12 11-54-35](https://user-images.githubusercontent.com/20714542/45397421-45092b80-b683-11e8-8f00-c44227a559ab.png)

**Comment by fkazemian** [comment]
schelling
![screenshot from 2018-09-12 13-32-14](https://user-images.githubusercontent.com/20714542/45400671-6cb2c080-b690-11e8-9c22-bcbb7ae22aba.png)

**Comment by fkazemian** [comment]
scipy
![screenshot from 2018-09-12 13-47-16](https://user-images.githubusercontent.com/20714542/45401206-eb106200-b692-11e8-86fb-1f485d4b6f7a.png)

**Comment by fkazemian** [comment]
smoothing
![screenshot from 2018-09-12 14-00-31](https://user-images.githubusercontent.com/20714542/45401782-9fab8300-b695-11e8-97fb-30459808d04d.png)

**Comment by fkazemian** [comment]
stationary_densities
![screenshot from 2018-09-12 14-14-29](https://user-images.githubusercontent.com/20714542/45402367-a7205b80-b698-11e8-842c-c0f79cd177d7.png)

**Comment by fkazemian** [comment]
wald_friedman

![screenshot from 2018-09-12 14-45-43](https://user-images.githubusercontent.com/20714542/45402854-3dee1780-b69b-11e8-8e32-090b81ccbb7a.png)

**Comment by fkazemian** [comment]
writing_good_code
![screenshot from 2018-09-12 14-51-18](https://user-images.githubusercontent.com/20714542/45402911-77bf1e00-b69b-11e8-86e9-f19bc92cf6af.png)

**Comment by mmcky** [comment]
I have edited the builder to prepend `%matplotlib inline` prior to executing a notebook to ensure matplotlib is setup correctly. The prepended line is then removed prior to writing the executed notebook to disk.

**Comment by mmcky** [comment]
@fkazemian I have pushed the latest to compare-lectures.quantecon.org. Would you mind checking if this is fixed. There may still be a few missing if execution time takes longer than 1200s.

**Comment by fkazemian** [comment]
writing_good_code
![screenshot from 2018-09-18 10-22-28](https://user-images.githubusercontent.com/20714542/45657251-e2091000-bb2c-11e8-825c-64af6ef68c2d.png)
wald_friedman
![screenshot from 2018-09-18 10-24-05](https://user-images.githubusercontent.com/20714542/45657293-0a910a00-bb2d-11e8-952b-8a47ffcc87f0.png)
stationary_densities
![screenshot from 2018-09-18 10-25-07](https://user-images.githubusercontent.com/20714542/45657324-2dbbb980-bb2d-11e8-8ad0-d920c1a85acd.png)
smoothing
![screenshot from 2018-09-18 10-26-04](https://user-images.githubusercontent.com/20714542/45657347-55ab1d00-bb2d-11e8-9f8b-045a06b96f6d.png)
scipy
![screenshot from 2018-09-18 10-27-19](https://user-images.githubusercontent.com/20714542/45657368-7a06f980-bb2d-11e8-9fa3-9c999f234bfa.png)
schelling
![screenshot from 2018-09-18 10-28-47](https://user-images.githubusercontent.com/20714542/45657423-ade21f00-bb2d-11e8-9342-d55fd3a07489.png)
samuelson
![screenshot from 2018-09-18 10-29-44](https://user-images.githubusercontent.com/20714542/45657451-ce11de00-bb2d-11e8-9aee-4d24ebc99a72.png)
python_oop
![screenshot from 2018-09-18 10-31-05](https://user-images.githubusercontent.com/20714542/45657514-02859a00-bb2e-11e8-824f-5389a25a3549.png)
python_by_example
![screenshot from 2018-09-18 10-32-02](https://user-images.githubusercontent.com/20714542/45657542-2943d080-bb2e-11e8-81cd-05e89b9ec601.png)
perm_income
![screenshot from 2018-09-18 10-33-20](https://user-images.githubusercontent.com/20714542/45657572-50020700-bb2e-11e8-8827-e140f17a3c71.png)

**Comment by fkazemian** [comment]
pandas
![screenshot from 2018-09-18 10-34-36](https://user-images.githubusercontent.com/20714542/45657617-8049a580-bb2e-11e8-82b8-fff2a0503c83.png)

optgrowth
![screenshot from 2018-09-18 10-35-34](https://user-images.githubusercontent.com/20714542/45657655-a2432800-bb2e-11e8-9e1d-f602e4390a99.png)

opt_tax_recur
![screenshot from 2018-09-18 10-37-00](https://user-images.githubusercontent.com/20714542/45657710-d3bbf380-bb2e-11e8-89c9-ef02077b025c.png)

ols
![screenshot from 2018-09-18 10-37-52](https://user-images.githubusercontent.com/20714542/45657741-f2ba8580-bb2e-11e8-97d3-c68a345251b5.png)

odu
![screenshot from 2018-09-18 10-38-44](https://user-images.githubusercontent.com/20714542/45657775-11208100-bb2f-11e8-8327-f7f2e0d7526d.png)

numba
![screenshot from 2018-09-18 10-39-42](https://user-images.githubusercontent.com/20714542/45657798-331a0380-bb2f-11e8-8da0-075ec3cadbd6.png)

mle
![screenshot from 2018-09-18 10-40-33](https://user-images.githubusercontent.com/20714542/45657832-517fff00-bb2f-11e8-870f-b9ca201d3b09.png)

mccall_model_with_separation
![screenshot from 2018-09-18 10-41-24](https://user-images.githubusercontent.com/20714542/45657862-707e9100-bb2f-11e8-8498-f1d52e9e6cfa.png)

matplotlib
![screenshot from 2018-09-18 10-42-18](https://user-images.githubusercontent.com/20714542/45657888-91df7d00-bb2f-11e8-8997-96051d8ba4cd.png)

**Comment by fkazemian** [comment]
Hi @mmcky I checked about 20 of them (as you can see above) and all of them are fixed, so it seems this bug is fixed and I change the label to Fixed, Thanks

**Comment by mmcky** [comment]
thanks @fkazemian that's a big help. Good news.
