### ISSUE TITLE
Link update

### ISSUE THREAD

**Issue by jstac** [QuantEcon/lecture-source-py#711]
Thanks MG for the following:

This link appears to need updating:
https://github.com/pydata/pandas/blob/master/pandas/stats/math.py

From: "No problem: You can go ahead and read the code."

At this page:
https://python.quantecon.org/about_lectures.html

**Comment by mmcky** [comment]
@jstac this is a bit more involved than a link update. It looks like `pandas` has removed this functionality when I looked at this last week. So we may need to point to some other example. 

https://github.com/QuantEcon/lecture-source-py/issues/703
