### ISSUE TITLE
Typo in formula reference

### ISSUE THREAD

**Issue by Tatsu111** [QuantEcon/lecture-source-py#713]
I think in “geometric series for elementary economics” the section for Keynesian multiplier might have an error.
Li+Ri=Di
If you substitute Ri=rDi you can get
Li=(1-r)Di

Not from equation (2) and (3) because there are no common variables allowing for a combination.

**Comment by Patil2099** [comment]
@jstac  Can I work on this issue?

**Comment by jstac** [comment]
@Patil2099 Please go ahead.  It will be a matter of checking the algebra carefully.  You can generate notebooks from the lectures using this tool: https://jupinx.quantecon.org/

**Comment by shlff** [comment]
Hi @jstac , this issue has been solved by the merged PR #933 . I will close this issue.
