### ISSUE TITLE
NumPy issue at https://python.quantecon.org/numpy.html

### ISSUE THREAD

**Issue by lahemals** [QuantEcon/lecture-source-py#722]
It appears that the 'numpy' library has not been loaded here : https://python.quantecon.org/numpy.html 

As a result, all examples of the page throw associated errors.

(Apologies in advance if the styling of this question is not great, I just got started with GitHub).

**Comment by mmcky** [comment]
thanks for reporting @lahemals -- a fix should be released shortly.

**Comment by jstac** [comment]
Thanks for letting us know @lahemals!  No worries about styling :-)

**Comment by mmcky** [comment]
@lahemals this is now fixed on the `live` site. Cheers.
