### ISSUE TITLE
Clean up branches

### ISSUE THREAD

**Issue by jstac** [QuantEcon/lecture-source-py#729]
There are an awful lot of branches and not many PRs.

Is someone able to get rid of the ones that are no longer relevant (merged/abandoned)?

**Comment by mmcky** [comment]
there are a lot of `stale` branches. 

![image](https://user-images.githubusercontent.com/8263752/68551248-0164aa00-045f-11ea-9b0d-cdad769d8d1b.png)

Do you want me to get rid of them?

**Comment by jstac** [comment]
yes please :-)

But please give me an hour or so --- I'm being bad and editing in master right now.
