### ISSUE TITLE
update the @vectorize example in parallelization

### ISSUE THREAD

**Issue by jstac** [QuantEcon/lecture-source-py#735]
Replace it with standard @njit and @njit(parallel=True).

**Comment by mmcky** [comment]
hey @jstac I noticed this switch which made me question when to use `vectorize`

```
You might ask yourself, “why would I go through this instead of compiling a simple iteration loop using the @jit decorator?”. The answer is that NumPy ufuncs automatically get other features such as reduction, accumulation or broadcasting.
```
from https://numba.pydata.org/numba-doc/dev/user/vectorize.html

**Comment by jstac** [comment]
Thanks @mmcky .  In this particular case all those advantage still hold with a simple @njit, and I can also parallelize without adding type information.
