### ISSUE TITLE
some greek letters not being rendered by LiberationMono

### ISSUE THREAD

**Issue by AakashGfude** [QuantEcon/lecture-source-py#744]
For example, phi, as can be seen from this screenshot of about_py 
![image](https://user-images.githubusercontent.com/6542997/69017067-56bd3000-09f8-11ea-8b5f-ecb844a54f8c.png)

**Comment by AakashGfude** [comment]
This issue was targeted by using `CMU Serif` font only for greek and Latin letters, as it has support for more if not all characters. and keeping `Liberation Mono` as the mono font. `ucharclasses` package helps us to make this conditional switching of fonts.
```
\setmonofont{Liberation Mono}
\usepackage[Latin,Greek]{ucharclasses}
\newfontfamily\substitutefont{CMU Serif}
\setTransitionsForGreek{\begingroup\substitutefont}{\endgroup}
```

The result is :-
![image](https://user-images.githubusercontent.com/6542997/69017120-dc40e000-09f8-11ea-989d-f1f113e727df.png)

**Comment by mmcky** [comment]
nice lateral thinking @AakashGfude -- good work!

**Comment by jstac** [comment]
This is connected to #738 --- might it be a good idea to make that change first?

We need to implement #738 anyway, for execution.
