### ISSUE TITLE
One word needs changing to fix a name error in the SciPy lesson

### ISSUE THREAD

**Issue by Viishied** [QuantEcon/lecture-source-py#816]
![image](https://user-images.githubusercontent.com/49959990/70596354-b18b1700-1bb3-11ea-9555-88fb334118e2.png)

Just need "newton" changed to "brentq" in the scipy lesson. See Screenshot.
That's all.

Thanks

**Comment by jstac** [comment]
Thanks @Viishied !

This is fixed in #819
