### ISSUE TITLE
A typo in Default Risk and Income Fluctuations

### ISSUE THREAD

**Issue by zz273** [QuantEcon/lecture-source-py#849]
The model says 

![Screen Shot 2020-01-19 at 16 35 28](https://user-images.githubusercontent.com/60077140/72688883-b5c32200-3ad9-11ea-9da5-e755ddc9062a.png).

The code says:
```
        # Compute Vd
        Vd[iy] = u(def_y[iy], γ) + \
                β * (θ * EVc[iy, zero_ind] + (1 - θ) * EVd[iy])
```

I guess it should be `EV[iy, zero_ind]` instead of `EVc[iy, zero_ind]` in the code? 

But the country won't default when B = 0, so it actually does not matter?

**Comment by jstac** [comment]
Hi @ywang273 , I'm not sure why you think this is a mistake.  It seems to me that the code matches the mathematics...?

**Comment by zz273** [comment]
Math: θ*Ev(0,y')

But the code says `θ*EVc[iy, zero_ind]`

I guess Ev(0,y') and `EVc[iy, zero_ind]` are different? One is the maximum value of EVc and EVd, while the other one is just EVc.

**Comment by Flintro** [comment]
Hi @zz273. Regarding the original post, I take it when you said `EVd[iy,zero_ind]` you actually meant `EVd[iy,zero_ind]`. In this case, I think you are right. The code should read:
`        # Compute Vd
        Vd[iy] = u(def_y[iy], γ) + \
                β * (θ * EV[iy, zero_ind] + (1 - θ) * EVd[iy]) `

**Comment by zz273** [comment]
Hi @Flintro,  thank you for pointing out the typo in my original post. I have fixed it and hope no confusion anymore.

**Comment by jstac** [comment]
Hi @zz273 , we've just merged changes due to @cc7768 that fix this issue.  It will be live within a few days.  Thanks again for reporting.

**Comment by mmcky** [comment]
These fixes are now live.
