### ISSUE TITLE
Issues with top level index.html file

### ISSUE THREAD

**Issue by mmcky** [QuantEcon/lecture-source-py#88]
<img width="1860" alt="image" src="https://user-images.githubusercontent.com/8263752/46523020-cd1bd300-c8c7-11e8-8d58-b06d33e4df35.png">

@DrDrij is this a theme issue or do I need to dig into ``jupinx``?

**Comment by DrDrij** [comment]
@mmcky Yeah I think jupinx will need a look at. Not generating nested lists correctly. Should be something like:

```
<ul>
	<li>
		<a href="#">Introduction to Python</a>
		<ul>
			<li>
				<a href="#">About Python</a>
			</li>
			<li>
				<a href="#">Setting up Your Python Environment</a>
			</li>
			<li>
				<a href="#">An Introductory Example</a>
			</li>
			<li>
				<a href="#">Python Essentials</a>
			</li>
			<li>
				<a href="#">OOP I: Introduction to Object Oriented Programming</a>
			</li>
		</ul>
	</li>
	<li>
		<a href="#">The Scientific Libraries</a>
		<ul>
			<li>
				<a href="#">NumPy</a>
			</li>
			<li>
				<a href="#">Matplotlib</a>
			</li>
...			
```

**Comment by mmcky** [comment]
the issue was incorrect spacing after a `raw` directive being applied. This has been fixed in https://github.com/QuantEcon/sphinxcontrib-jupyter/pull/128
