### ISSUE TITLE
Additive functionals lecture showing a RuntimeWarning

### ISSUE THREAD

**Issue by jstac** [QuantEcon/lecture-source-py#903]
Search in https://python.quantecon.org/additive_functionals.html

**Comment by mtiley** [comment]
For anyone else interested in this issue I'm going to start breaking up the ``AMF_LSS_VAR`` class and restructuring things a bit which should as a bonus simplify debugging.  

The RuntimeWarning is triggered when the ``plot_additive`` function calculates upper and lower bounds for a functional using what seems to me to be a nonsensical value for the standard deviation (0.0) of a normal distribution. The warning is given when the ppf of this distribution is taken. 

Below is the relevant code from ``plot_additive`` (print statements have been added to clarify following image of output).
<img width="515" alt="additive1" src="https://user-images.githubusercontent.com/56301568/74893660-04b5ed00-53e1-11ea-8e12-125d933e2adc.PNG">

<img width="567" alt="additive2" src="https://user-images.githubusercontent.com/56301568/74893980-c53bd080-53e1-11ea-8947-4683e130b130.PNG">

i.e. we have the assignment ``madd_dist = norm([0.], 0.0)`` and then ``madd_dist.ppf([0.01, .99])`` is taken.


I have replicated the issue in a notebook [here](https://github.com/mtiley/QE-stuff-miles/blob/master/RuntimeWarning%20in%20additive_functionals%20minimal%20replication.ipynb).

@shlff and I were discussing simply starting the iteration through increasing values for standard deviation at a small positive number (like 0.000000001). This gets rid of the warning.
