### ISSUE TITLE
Colab live execution is broken -- urgent

### ISSUE THREAD

**Issue by jstac** [QuantEcon/lecture-source-py#904]
Clicking on "Launch notebook" leads to an error, at least for me.

If others can replicate then, as well as putting in a fix, can someone please tell me where and when the problem arose?  How long has it been like this?  Is there something we could have done differently?

I'm now very nervous about having that button without any automated test as to whether it's working.  Suggestions?

CC @mmcky @AakashGfude

**Comment by mmcky** [comment]
I think I know the issue. Is this on one of the more recent lectures? It looks like the backing repo hasn't been updated to match the release of the new lecture perhaps. 

"python_essentials" works for example.

**Comment by jstac** [comment]
Good to hear, thanks @mmcky.

Any ideas as to how we can make sure this doesn't happen again?

**Comment by mmcky** [comment]
We didn't have automatic publishing enabled for fear the repo would grow too large. But I think we just need to accept that as the repo really only acts as an online source. So I will re-enable automatic publishing so whenever there is a publish the collection of notebooks get's updated.
