### ISSUE TITLE
NameError in python lecture notes (pdf version)

### ISSUE THREAD

**Issue by FelixCW** [QuantEcon/lecture-source-py#908]
The codes displayed in python lecture notes (pdf version, page 157-159)
https://python.quantecon.org/_downloads/pdf/quantitative_economics_with_python.pdf 
seem to have unintended errors.

**Comment by jstac** [comment]
Hi @FelixCW , many thanks for reporting.  We appreciate it. The error was fixed in #906 and the PDF should be good again after the next upload.

(@mmcky , would you mind to build and publish again soon?)
