### ISSUE TITLE
Optimal growth lecture 1 issue

### ISSUE THREAD

**Issue by Harveyt47** [QuantEcon/lecture-source-py#937]
There is an error occurring in the optimal growth lecture. 
![optgrowth](https://user-images.githubusercontent.com/58153750/75203822-54baf800-57c3-11ea-88d2-abe030f6e376.png)
I believe that this error is originating from the ``minimize_scalar`` function in [scipy](https://docs.scipy.org/doc/scipy/reference/tutorial/optimize.html#univariate-function-minimizers-minimize-scalar) which is used in the ``maximize`` function in the optgrowth [lecture](https://python.quantecon.org/optgrowth.html#Scalar-Maximization). 
I also believe that the ``method='bounded'`` variable in the ``minimize_scalar`` function is causing this error. 

When I remove ``method='bounded'`` from being called I get the following output
![optgro](https://user-images.githubusercontent.com/58153750/75204203-60f38500-57c4-11ea-838d-2bef69e422bc.png)
This output is obviously not optimal.

**Comment by Harveyt47** [comment]
I believe it is a problem with the bounds. The initial bound in the ``maximize`` function is 1e-05. This is causing the error. the output below illustrates this.

![Screenshot from 2020-02-25 14-13-18](https://user-images.githubusercontent.com/58153750/75211731-07498580-57d9-11ea-8e88-02bed0f0eb9e.png)


changing the upper bound to 1e-04 fixes the bug. 

I am unsure why the ``minimize_scalar`` function can not take bounds so close to one another.

**Comment by Harveyt47** [comment]
Hi @jstac , I believe there may be a floating point error occurring within scipy function. 

I think that the best fix for now is to change the minimum of the [grid](https://python.quantecon.org/optgrowth.html#Optimal-Growth-Model) from 1e-5 to 1e-4.

**Comment by jstac** [comment]
Thanks @Harveyt47, good detective work.

Please put in a PR which fixes this issue using the technique you propose and ask someone to review it.
