### ISSUE TITLE
Broken maths in Black-Litterman lecture

### ISSUE THREAD

**Issue by jstac** [QuantEcon/lecture-source-py#940]
See https://python.quantecon.org/black_litterman.html#Curve-Decolletage

It looks like some maths is still marked by `$$`.

**Comment by shlff** [comment]
Good morning, @jstac . I found a weird thing about the maths here: when you open this lecture in Jupyter Notebook, then the maths looks fine without ``$$``, please see [here](https://colab.research.google.com/github/QuantEcon/quantecon-notebooks-python/blob/master/black_litterman.ipynb).

I am afraid that it is not a single case.

**Comment by jstac** [comment]
@mmcky, do you have any insight on what's happening here?  It's not obvious from the RST, which is

```
.. math::
  :label: info-curve

  \vec r_e = (\Sigma^{-1} + \lambda (\tau \Sigma)^{-1})^{-1} (\Sigma^{-1} \mu_{BL}
  + \lambda (\tau \Sigma)^{-1}\hat \mu )
```

**Comment by mmcky** [comment]
It’s the + at the beginning of the 3rd line that will cause an issue here.
