### ISSUE TITLE
Update AWS Infrastructure for Project Split

### ISSUE THREAD

**Issue by mmcky** [QuantEcon/lecture-source-py#953]
@DrDrij here are a list of infrastructure related tasks needed for Issue #950. 

- [x] Setup `aws buckets` and cloudfront for `three` new lecture series

    a. Python for Quantitative Economics (**bucket:** python-programming.quantecon.org)
    b. Introduction to Quantitative Economics with Python (**bucket:** python-intro.quantecon.org)
    c. Advanced Quantitative Economics with Python (**bucket:** python-advanced.quantecon.org)

we will want to setup `backup.` and `preview.` prefixed buckets for each as well.

**Comment by DrDrij** [comment]
**Live:**
http://python-programming.quantecon.org.s3-website-ap-southeast-2.amazonaws.com
http://python-intro.quantecon.org.s3-website-ap-southeast-2.amazonaws.com
http://python-advanced.quantecon.org.s3-website-ap-southeast-2.amazonaws.com

**Preivew:**
http://preview.python-programming.quantecon.org.s3-website-ap-southeast-2.amazonaws.com
http://preview.python-intro.quantecon.org.s3-website-ap-southeast-2.amazonaws.com
http://preview.python-advanced.quantecon.org.s3-website-ap-southeast-2.amazonaws.com

**Backup:**
http://backup.python-advanced.quantecon.org.s3-website-ap-southeast-2.amazonaws.com
http://backup.python-intro.quantecon.org.s3-website-ap-southeast-2.amazonaws.com
http://backup.python-programming.quantecon.org.s3-website-ap-southeast-2.amazonaws.com

**Comment by mmcky** [comment]
Nice! -- Thanks @DrDrij. Those cloudfront links is the same as the `distribution id`?
