### ISSUE TITLE
[contributors] update python landing page to include contributors

### ISSUE THREAD

**Issue by mmcky** [QuantEcon/lecture-source-py#955]
@DrDrij we would like to update the front page (the current python.quantecon.org) or the `index.rst` file for `lecture-source-py` to include `contributors. 

We would like to:

1. move the `commit` link to be an item below the `Last compiled: {DATE}`:
1. add another `contributors` item and link to contributors page on github https://github.com/QuantEcon/lecture-source-py/graphs/contributors (for now)

<img width="495" alt="image" src="https://user-images.githubusercontent.com/8263752/76051417-c7e01d80-5fbe-11ea-8d55-869cb408117a.png">

In the future we will want to make an `contributors.rst` page that is similar to https://datascience.quantecon.org/contributors.html. 

This will address Item 3 in https://github.com/QuantEcon/lecture-source-py/issues/946

**Comment by DrDrij** [comment]
Will put together the following and implement any feedback posted here:

![image](https://user-images.githubusercontent.com/5886045/76155677-41087d80-6143-11ea-98de-3a02e7e849e5.png)

**Comment by jstac** [comment]
Please feel free to ping me if you need input.

**Comment by mmcky** [comment]
thanks @DrDrij I like the solution you post above to include Contributors.

**Comment by jstac** [comment]
Thanks @DrDrij.  

I'd like to make the contributors more prominent.  How about we increase the font size and also take the bold off the date (so it doesn't steal all the attention).

**Comment by mmcky** [comment]
@DrDrij can we apply the final version to:

1. [lecture-python-programming](https://github.com/QuantEcon/lecture-python-programming.theme)
1. [lecture-python-intro](https://github.com/QuantEcon/lecture-python-intro.theme)
1. [lecture-python-advanced](https://github.com/QuantEcon/lecture-python-advanced.theme)

if `theme` related otherwise please update `index.rst` in the respective `public` repos.

**Comment by DrDrij** [comment]
> @DrDrij can we apply the final version to:
> 
> 1. [lecture-python-programming](https://github.com/QuantEcon/lecture-python-programming.theme)
> 2. [lecture-python-intro](https://github.com/QuantEcon/lecture-python-intro.theme)
> 3. [lecture-python-advanced](https://github.com/QuantEcon/lecture-python-advanced.theme)
> 
> if `theme` related otherwise please update `index.rst` in the respective `public` repos.

Will do.  It's all in the `index.rst` files.

**Comment by mmcky** [comment]
Please submit as PR's -- that will be helpful. Thanks.

**Comment by DrDrij** [comment]
PR is good to go: https://github.com/QuantEcon/lecture-source-py/pull/966

**Comment by jstac** [comment]
I'll let you close this when ready @mmcky .

**Comment by mmcky** [comment]
We are currently pointing to `github` but I think we will need to create a manual `contributors` page when we do the split as the new repos will have no history.
