### ISSUE TITLE
Assign lectures to new repository structure

### ISSUE THREAD

**Issue by mmcky** [QuantEcon/lecture-source-py#956]
A table to assign lectures to the new repository structure:

1. Python for Quantitative Economics (python-programming)
2. Introduction to Quantitative Economics with Python (python-intro)
3. Advanced Quantitative Economics with Python (python-advanced)

| Lecture | Future Repo | 
|:--------|:------------|
| about_lectures.rst | |
| about_py.rst | 1 |
| additive_functionals.rst | 3|
| aiyagari.rst | 2|
| amss.rst |3 |
| amss2.rst |3 |
| amss3.rst | 3|
| ar1_processes.rst | 2|
| arellano.rst | 3|
| arma.rst | 3|
| black_litterman.rst |3 |
| calvo.rst |3 |
| career.rst |3 |
| cattle_cycles.rst |3 |
| chang_credible.rst |3 |
| chang_ramsey.rst | 3|
| classical_filtering.rst | 3|
| coase.rst | 3|
| coleman_policy_iter.rst | 3|
| complex_and_trig.rst | 2|
| cons_news.rst | 3|
| debugging.rst | 1 |
| discrete_dp.rst | 3|
| dyn_stack.rst | 3|
| egm_policy_iter.rst | 3|
| estspec.rst | 3|
| exchangeable.rst | 2|
| finite_markov.rst | 2|
| functions.rst | 1|
| geom_series.rst | 2|
| getting_started.rst | 1 |
| growth_in_dles.rst | 3|
| harrison_kreps.rst | 2|
| heavy_tails.rst | 2|
| hs_invertibility_example.rst | 3|
| hs_recursive_models.rst | 3|
| ifp.rst | 3|
| inventory_dynamics.rst | 2|
| irfs_in_hall_model.rst | 3|
| jv.rst | 3|
| kalman.rst | 2|
| kesten_processes.rst | 2|
| lake_model.rst | 2|
| likelihood_ratio_process.rst | 2 |
| linear_algebra.rst | 2|
| linear_models.rst | 2|
| lln_clt.rst | 2|
| lq_inventories.rst | 2|
| lqcontrol.rst | 2|
| lqramsey.rst | 3|
| lu_tricks.rst | 3|
| lucas_asset_pricing_dles.rst | 3|
| lucas_model.rst | 3|
| markov_asset.rst | 2|
| markov_jump_lq.rst | 3|
| markov_perf.rst | 2|
| matplotlib.rst | 1 |
| matsuyama.rst | 3|
| mccall_correlated.rst | 2|
| mccall_fitted_vfi.rst | 2|
| mccall_model.rst | 2|
| mccall_model_with_separation.rst | 2|
| mle.rst | 2|
| muth_kalman.rst | 3|
| need_for_speed.rst | 1 |
| numba.rst | 1 |
| numpy.rst | 1 |
| odu.rst | 3|
| ols.rst | 2|
| oop_intro.rst | 1 |
| opt_tax_recur.rst | 3|
| optgrowth.rst | 3|
| optgrowth_fast.rst | 3|
| orth_proj.rst | 3|
| pandas.rst | 1 |
| pandas_panel.rst | 2|
| parallelization.rst | 1 |
| perm_income.rst | 2|
| perm_income_cons.rst | 2|
| permanent_income_dles.rst | 3|
| python_advanced_features.rst | 1 |
| python_by_example.rst | 1 |
| python_essentials.rst | 1 |
| python_oop.rst | 1 |
| rational_expectations.rst | 2|
| re_with_feedback.rst | 2 |
| rob_markov_perf.rst | 3|
| robustness.rst | 3|
| rosen_schooling_model.rst | 3|
| samuelson.rst | 2|
| scalar_dynam.rst | 2|
| schelling.rst | 2|
| scipy.rst | 1 |
| short_path.rst | 2|
| smoothing.rst | 3|
| smoothing_tax.rst | 3|
| stationary_densities.rst | 3|
| tax_smoothing_1.rst | 3|
| tax_smoothing_2.rst | 3|
| tax_smoothing_3.rst | 3|
| uncertainty_traps.rst | 2|
| von_neumann_model.rst | 3|
| wald_friedman.rst | 3|
| wealth_dynamics.rst | 2|
| writing_good_code.rst | 1 |

Helps address Issue #950

**Comment by jstac** [comment]
Thanks @mmcky , very helpful.

@thomassargent30, my assignment numbers (1-3) above are just a first pass.  Let's discuss the edge cases.

**Comment by mmcky** [comment]
hey @jstac let me know when you have had a chance to review these assignments. I should have `lecture-source-intro` up to preview.python-intro.quantecon.org soon.

**Comment by jstac** [comment]
Hi @mmcky, I've reviewed this and I think it's pretty good.  We might need to tweak at some point but for now you can go ahead.

**Comment by najuzilu** [comment]
Hi @mmcky @jstac, I want to confirm that the following two lectures appear in two repos:

* `rational_expectations.rst` which is labeled as `2` and appears under `2` and `3` in `index_multi_agent_models.rst`.  In `lecture-source-py` this file appears **only** once under `index_multi_agent_models_undergrad.rst`.

* `re_with_feedback.rst ` which is not in the table but appears under `2` and `3` in `index_multi_agent_models.rst`. In `lecture-source-py` this file appears **only** once under `index_multi_agent_models_undergrad.rst`.

If the organization of these files has not changed from the organization in `lecture-source-py`, I will make a PR.

I have confirmed with @mmcky  that the following should be removed for now and I will make a PR in the appropriate folder:
* `cass_koopmans.rst` which is not labeled in the table above but appears under `2` and `3` in `index_intro_dynam.rst`.

**Comment by jstac** [comment]
Hi @najuzilu, please ignore everything in `index_*_undergrad.rst` and `index_*_grad.rst`.

These files are completely out of date and can be deleted.

**Comment by mmcky** [comment]
thanks @jstac the `undergrad` and `grad` `index` files are not contained in the new repositories. So @najuzilu will add them to the prefixed versions (i.e. `index_multi_agent_models.rst`) -- sorry this discussion was via slack.

**Comment by mmcky** [comment]
@jstac should `likelihood_ratio_process.rst` be assigned `2` or `3`?

**Comment by jstac** [comment]
In 2 please.  Thanks @mmcky

**Comment by najuzilu** [comment]
@mmcky I'll move it over.

**Comment by mmcky** [comment]
thanks @jstac and @najuzilu -- this has been a really helpful way to assign the files.
