### ISSUE TITLE
Sanitize lectures of co-author / co-contributor statements

### ISSUE THREAD

**Issue by mmcky** [QuantEcon/lecture-source-py#958]
> remove all co-author statements --- has to be done carefully because the wording varies so it's hard to search.

As part of the transfer to new license we need to check all `rst` files and remove `co-author` statements. Presentations are varied so will require going through the first ~10% of each lecture `rst` file looking for statements like:

`pandas_panel.rst` contains `Most of this lecture was created by Natasha Watkins`

This will resolve item 2 in #946

**Comment by mmcky** [comment]
@sayaikegawa please let me know if you are available to help with this task. Thanks.

**Comment by sayaikegawa** [comment]
Hi @mmcky , I'm happy to do this.

**Comment by mmcky** [comment]
thanksk @sayaikegawa

**Comment by sayaikegawa** [comment]
Hi @mmcky , When I make PR, do you think that it is good idea to remove the names of all lectures's rst file for 1 PR? or removing a name of each rst file for each PR?

**Comment by mmcky** [comment]
hi @sayaikegawa I think in this case it would be ok to do a single PR that removes them all across the files. I think it is unlikely to cause merge conflicts with other work as they are usually on a single line. If a conflict arises I can help resolve it.

**Comment by sayaikegawa** [comment]
Thank you @mmcky , then I will make a single PR.

**Comment by sayaikegawa** [comment]
Hi @jstac and @mmcky , would it be ok to remove author of lectures and codes like below as well? And should I wait making PR until the split finishes?
![Screen Shot 2020-03-10 at 12 51 42 pm](https://user-images.githubusercontent.com/44494439/76272434-88237980-62cf-11ea-985b-fa0605fcb221.png)
![Screen Shot 2020-03-10 at 12 52 18 pm](https://user-images.githubusercontent.com/44494439/76272452-92de0e80-62cf-11ea-8ccc-8c59f7433fcb.png)

**Comment by mmcky** [comment]
> would it be ok to remove author of lectures and codes like below as well? 

hi @sayaikegawa good question. I think removal of all names (code and rst) is the way to go. Good find. 

> And should I wait making PR until the split finishes?

how far along are you? Feel free to keep going on this task as I can merge in the changes to the split repositories later on.

**Comment by sayaikegawa** [comment]
Thank you @mmcky , I think I can finish this by tomorrow evening at the latest.

**Comment by jstac** [comment]
Thanks @sayaikegawa.  Names are to be removed everywhere, as @mmcky says.

By the way, could you please keep a list of the names that you remove?  Then we can try to make sure that these people are recognized for their contribution in some way.

**Comment by sayaikegawa** [comment]
Thank you @jstac . I'll make the list.
