### ISSUE TITLE
Update quantecon.org for new structure

### ISSUE THREAD

**Issue by mmcky** [QuantEcon/lecture-source-py#962]
- [x] deploy updated `quantecon.org` frontpage
- [x]  migrate current `lectures.quantecon.org` to `quantecon.org` redesigned front page

    a. for the new `python` button it should direct to the landing page in #961  (above)

**Comment by DrDrij** [comment]
> * [x]  deploy updated `quantecon.org` frontpage
> * [x]   migrate current `lectures.quantecon.org` to `quantecon.org` redesigned front page

* [ ] The new `python` button it should direct to the landing page in #961  (above)

**Comment by mmcky** [comment]
@DrDrij I will close this issue as the `python` button redirect will be part of the deployment issue.
