### ISSUE TITLE
[Themes] Adjust to remove `undergrad` and `graduate` index support

### ISSUE THREAD

**Issue by mmcky** [QuantEcon/lecture-source-py#964]
- [x] adjust all themes to remove undergraduate and graduate tab index support

~~@DrDrij: @AakashGfude and I are treating `lecture-python-programming` as the source of truth for the `them` files. So Please make this edit (via PR) https://github.com/QuantEcon/lecture-python-programming.theme~~

Actually I have started customising the theme files for each project through title changes etc. Please raise a PR for each `lecture-python-programming.theme` + `lecture-python-intro` ...

**Comment by mmcky** [comment]
hey @DrDrij could you let me know when you think you'll get a chance to look at this? Thanks

**Comment by DrDrij** [comment]
> hey @DrDrij could you let me know when you think you'll get a chance to look at this? Thanks

https://github.com/QuantEcon/lecture-python-intro/pull/30
https://github.com/QuantEcon/lecture-python-intro.theme/pull/2

**Comment by mmcky** [comment]
thanks @DrDrij when you get the chance can you add these changes to:

1. `lecture-python-programming`
2. `lecture-python-advanced`

**Comment by mmcky** [comment]
Is this now closed?

**Comment by DrDrij** [comment]
The PR to remove tabs on `lecture-python-advanced`: https://github.com/QuantEcon/lecture-python-advanced/pull/71

@mmcky Could you please delete this branch, the tabs didn't exist so no need to remove from this repo: https://github.com/QuantEcon/lecture-python-programming/tree/remove-tabs

Thanks! Can be closed.
