### ISSUE TITLE
[lecture-issue, low-priority] Citation Missing in Inventory Dynamics Lecture

### ISSUE THREAD

**Issue by najuzilu** [QuantEcon/lecture-source-py#965]
Citation `[caplin1985variability]` is missing in the [Inventory Dynamics](https://python.quantecon.org/inventory_dynamics.html) lecture:
<img width="738" alt="Screen Shot 2020-03-13 at 2 57 15 PM" src="https://user-images.githubusercontent.com/33075058/76588695-bc02d700-653b-11ea-89b8-c4636aa29ec8.png">

**Comment by mtiley** [comment]
When I build locally I get this list of missing citations:
<img width="392" alt="citations" src="https://user-images.githubusercontent.com/56301568/76593381-4b16eb80-654a-11ea-96e0-726b608b06fe.PNG">
@thomassargent30 it seems like some of the labels were changed in [this commit](https://github.com/QuantEcon/lecture-source-py/commit/0fc4b113dfeb9fd7b7e8a2b57c338190acd93b1d#diff-3104805625d9c2f086d496618e0c0e6c) but haven't been changed where they're referenced in the lectures

**Comment by mmcky** [comment]
thanks for reporting these `sphinx` warnings @mtiley and @najuzilu. We will want a PR to fix these once we transfer over to the new repos.

**Comment by mmcky** [comment]
@najuzilu I will close this issue here as this will be captured by the `citation` warnings in the new lecture repositories. Would you mind to help fix these issues there?

**Comment by najuzilu** [comment]
@mmcky absolutely!
